{
  "hash": "7ff4d7d2ff1f0d21f9ac81ae110a7438",
  "result": {
    "markdown": "---\neditor_options: \n  markdown: \n    wrap: 72\n---\n\n\n# PCA {#sec-pca}\n \n![AI art generated from the text \"Principal component analysis\"](images/linmod/pcaart.jpg){width=50%}\n\nThis section introduces an advanced exploratory data analysis method called Principal component analysis (PCA). PCA summarizes the information[^1] in data that is composed of multiple variables.  Below is a scatterplot and correlation matrix of a dataset that consists of five variables. The scatterplot shows the pairwise relationships between the variables and they are useful for visualizing relationships, clusters, and outliers. The correlation matrix provides a numerical measure of the strength and direction of these relationships. This section only covers PCA on standardized data.\n\n[^1]: Here, information refers to the total amount of variation in the data. \n\n\n::: {.cell layout-ncol=\"1\" layout-align=\"center\"}\n::: {.cell-output-display}\n![Example of a linear relationship with the estimated or best fit SLR line with the predicted values shown as black points on the line](pca_files/figure-html/fig-pcaex-1.png){#fig-pcaex-1 fig-align='center' width=672}\n:::\n\n::: {.cell-output-display}\n![Example of a linear relationship with the estimated or best fit SLR line with the predicted values shown as black points on the line](pca_files/figure-html/fig-pcaex-2.png){#fig-pcaex-2 fig-align='center' width=672}\n:::\n:::\n\n\nGraphical and numerical summaries show positive and negative correlations between variables, and the strength of the linear relationship between them depends on which pair of variables is considered. With nine variables, there are 10 possible 3D scatterplots to examine, making it challenging to explore relationships beyond pairwise comparisons.  That is, when dealing with multiple variables, examining all possible pairwise relationships can be challenging, particularly in large datasets. Visualizing multidimensional relationships also becomes difficult as the number of variables increases, limiting the usefulness of graphical and numerical summaries. Therefore, more advanced exploratory data analysis methods, such as PCA may be needed to obtain meaningful insights from high-dimensional datasets.\n\nPCA is a powerful and widely used technique for extracting dominant modes of variation from a dataset. The data must consist of only numerical variables. The goal of PCA is to identify directions (or principal components or modes of variation) along which the variation in the data are maximal. The dominant modes of variation in PCA correspond to the principal components that explain most of the variation in the dataset. Thus, a few principal components (PCs) may capture almost as much of the variation as the original variables.  Such principal components capture the most important patterns or structures in the data. In some cases, the dominant modes of variation may be associated with specific features or facets in the data, allowing for a better understanding of the underlying variation processes that generates the data. \n\nTo better ensure that PCA provides meaningful results, several assumptions about about the data  are recommended.\n\n:::{.callout-warning}\n## Data assumptions\n\nPCA assumes assumption 1 and assumptions 2-4 are recommended for the data.\n\n- **Assumption 1**. *Independence*.  The variables are independent of one another. \n\n- **Assumption 2**. *Linearity*. Variables should generally be linearly related to each other to some extent, with moderate to strong correlations between some variables. However, the degree of linearity required for meaningful results may depend on the specific goals of the analysis and the structure of the data. While PCA can still be performed on data that shows weak correlations between variables or non-linear relationships[^2], the identification of underlying features or facets in the data may be more difficult. In general, stronger correlations and linearity in the data can make it easier for PCA to provide informative and meaningful results.\n\n[^2]: The lack of at least some moderate correlation between variables may lead PCA to provide as many PCs as there are variables in the data, which can result in a lack of dominant modes of variation. Non-linear relationships may be addressed by transforming variables so that the relationship in linear on the transformed scale (see @sec-remedmeasure).  \n\n- **Assumption 3**. *No clear outliers*. The data should not contain any extreme or influential outliers that deviate significantly from the majority of the data[^3]. The computations involved in PCA are dependent on the correlation matrix, and correlation is sensitive to outliers. This sensitivity can result in outliers having a large influence on the computed principal components, leading to misleading or incorrect interpretations of the underlying structure of the data. Therefore, it is important to identify and address any extreme or influential outliers before performing PCA to ensure that the results are accurate and reliable.\n\n[^3]: Potential outliers can be identified using graphical summaries, such as boxplots or scatterplots. If outliers are identified, one approach for dampening their effects is to apply transformations to the data, such as the logarithmic or square root transformation.\n\n- **Assumption 4**. *Adequate sample*.  The larger the sample, the easier it may be to identify dominate modes of variations and  meaningful structures in the data.  There is no strict requirement for a minimum sample size for performing PCA, and various rules-of-thumb have been proposed, such as 5 to 10 cases per variable have been recommended as minimum sample sizes. \n\nThis module introduces PCA as an exploratory method, not an inferential approach. Although there are inferential methods for PCA, those are not discussed here and be aware that inference using PCA require additional assumptions about the data. \n\n:::\n\n\n## The method of PCA\n\nIt is difficult to describe the method of PCA without some prior knowledge of matrix algebra and linear operators, but a basic overview of the technique is provided. In the simplest terms, PCA is a statistical technique that creates linear combinations of the original data to summarize variation and reduce the dimensionality of the data. We start with some essential notation and definitions for the PCA:\n\n:::{.callout-important}\n## Notation and definitions\n\n- We assume there are $p$ variables and $n$ observations so that $x_{ij}$ denotes the i$^{th}$ observed value under the j$^{th}$ variable for $i=1, ..., n$ and $j=1, 2, .., p$.  For example, $x_{34}$ denotes the 3rd observed value under the 4th variable. \n\n\n- The i$^{th}$ principal component (PC) is linear combination (weighted sum) of the variables, $e_{i1} x_{1}+ e_{i2} x_{2} + e_{i3} x_{3} + \\cdots + e_{ip} x_{p}$, and in total there will be $p$ PCs. $e_{i1}, e_{i2}, ..., e_{ip}$ are the weights assigned to each variable in the linear combination for the $i^{th}$ principal component and are generally referred as loadings.\n\n\n- The first PC is the linear combination of variables that provides the maximum variance (among all possible linear combinations considered) so that it accounts for as much variation in the data as possible.  That is, the values of $e_{11}, e_{12}, \\ldots, e_{1p}$ are chosen to maximize the variance[^4].\n\n- The second PC is also a linear combination of the variables, but with the constraint that it is uncorrelated with the first principal component, and that it accounts for as much of the remaining variation in the data as possible[^5].  \n\n- The third PC is also a linear combination of variables but that accounts for as much of the remaining variation as possible (not accounted for by the first two PCs), with this PC is  uncorrelated with between the rest of the PCs. \n\nThe process of computing the PCs continues until all $p$ principal components have been computed, with each component capturing a unique source of variation in the data that is uncorrelated with the other components. The first few principal components typically capture the majority of the variation in the data and retain as much information as possible from the original variables.\n\n:::\n\n[^4]: While the values $e_{11}, e_{12}, \\ldots, e_{1p}$ maximize the variance of the sum, it is subject to the constraint that these values must sum to 1. All subsequent PCs also have this constraint\n\n[^5]: With the PCs being uncorrelated, it signifies that each PC captures a unique aspect of the variation in the data.  \n\n \nIf the above description of PCA is too technical, think of PCA as providing a view of the data from a  different vantage point, where this vantage point[^6] focuses on maximizing the variability in the data that can highlight certain patterns or relationships. This is akin to say a real estate agent trying to sell a property.  Some pictures of the property may better highlight the most desirable or best features of the property. Of course, certain pictures will better highlight certain features more than others. In PCA, the data are viewed from a different vantage point in such a way to best reveal certain patterns or relationships not visible in the original data. This is just an attempt at an analogy but hopefully helps illustrate the idea of using PCA to create a different perspective on the data.\n\n\n[^6]: In the context of PCA, a new vantage point means the data are rotated to a new coordinate system that emphasizes different aspects of the data. However, it's important to note that PCA does not create new information; rather, it summarizes and reorganizes the existing information in a way that is potentially more informative and easier to interpret.\n\nThe equations or formulas for finding principal components will not be discussed here since the focus is on using software to conduct PCA. Specifically, we use R to obtain important elements of PCA, including\n\n- **Standard deviation for each PC:** It measures variability across a single component component (i.e. spread of data within a given PC). \n\n- **Proportion of Variance for each PC:** The amount of variance that a given PC accounts for.  This is provided by taking squared standard deviations (variance) of the given PC divided by sum of the variances. \n\n- **Cumulative Proportion for each PC:**  The cumulative variation represented by PCs up until a given component.\n\n- **Loadings for each PC:** If PCA computations are performed on standardized data, the loadings may be thought of as correlations in that they reflect the strength and direction of the relationship between each variable and each PC. These correlations help provide the coefficients of the linear combinations of the original variables that create the PCs.  If performed on non-standardized data, they represent the covariances rather than the correlations.\n\n\nIf the proportion of variation explained by the first, say $k$, PCs is large, then not much information is lost by considering only the first $k$ PCs instead of the whole dataset. However, determining the appropriate value of $k$ will be addressed later.\n\n\n## PCA comuptations using R\n\nThe function `gpairs()` (from the `gpairs` package) creates a scatterplot matrix for visualizing pairwise relationships between variables. The function `cor()` computes a basic correlation matrix, which show all pairwise correlations between variables, and the function `corrplot.mixed()` (from the `corrplot` package) creates a better visual representation of the correlation matrix.\n\n::: {.callout-tip icon=\"false\"}\n\n## R functions\n\n```\n### gpairs( dataframe,  diag.pars = list(fontsize = 9))\n# dataframe:  Replace with the name of the dataframe. \n#             All variables must be numerical.\n# diag.pars:  9 is the default font size for variables names. \n#             Decrease the number for smaller font sizes.\n#\n### cor( dataframe )\n# dataframe:  Replace with the name of the dataframe. \n#             All variables must be numerical.\n#\n#\n### corrplot.mixed( `cor object` )\n# cor object:  Replace with an object\n#              created from the cor() output\n#\n```\n\n:::\n\nThe function `principal()` from the `psych` package helps compute the required elements of PCA. By default, this function will standardized the data and conduct PCA computations on the standardized data. \n\n::: {.callout-tip icon=\"false\"}\n\n## R functions\n\n```\n### principal( dataframe, nfactors , rotate, cor )\n# dataframe: Replace with the name of the dataframe. \n#            All variables must be numerical.\n# nfactors: Set equal to the number of variables in the data.\n# rotate:  Set equal to \"none\". \n# cor: By default, it is set to \"cor\" so that computations\n#      are done on the standarized data. Set equal to \"cov\"\n#      to conduct PCA computation on the original centered data.\n```\n:::\n\n Although performing PCA on standardized data is not required, standardizing the data is recommended for PCA, especially when the variables in the dataset have different units or scales. Standardization transforms each variable to have a mean of 0 and a standard deviation of 1, and it prevents variables with larger scales from dominating the computed PCs.\n \nNote that the dataframe used for PCA must only contain numerical variables. The function `select()` from the `dplyr` package can assist with this task.\n\n::: {.callout-tip icon=\"false\"}\n## R functions\n\n```\n### select( dataframe ,'variable to remove', 'variable to remove' , ...)\n#  dataframe: Replace with the name of the  dataframe\n# 'variable to variable': Replace with the name of the variable remove or \n#                         the column number (negative version)\n# \n```\n\n:::\n\n\n\n::: callout-note\n\nThe case study provided in  @sec-casestudy6 provides various plant physiological measurements for 29 different plant species.  This data was used by by @pratt2021trade to investigate trade-offs (costs and benefits of different traits) among different xylem functions in shrub species and how they are influenced by minimum hydrostatic pressures  experienced by plants in the field. The objective here is to use PCA to identify dominant modes of variation among these measurements that are related to xylem structure, function, and properties, as well as underlying factors or dimensions that may be driving the variability in the data.\n\n![Arctostaphylos glauca (Big Berry Manzanita). It is one of shrub species considered in the study. Source:calscape.org](images/aeda/shrub.jpg){width=50%} \n\nBelow is a list and small description of each variable:\n\n- P75: the water potential at 75% loss of its hydraulic conductivity (MPa). \n\n- Ks: a measure of xylem-specific conductivity.  conductivity (kg s$^{-1}$ MPa$^{-1}$ m$^{-1}$).\n\n- Starch: amount of starch content in the xylem tissues (%). \n\n- Xylem density:  measure of the density of xylem (dry mass/tissue volume) .\n\n- Fiber percentage: the proportion of fibers in the xylem tissue. \n\n- Vessel percentage: the proportion of vessels in the xylem tissue.\n\n- Parenchyma percentage: the proportion of parenchyma cells in the xylem tissue. \n\n- Pmin: Minimum level of dehydration a plant can experience (MPa).\n\n- Water storage capacity: the capacity of the xylem tissue to store water ($\\triangle  \\text{Relative water content}/\\triangle \\text{MPa}$).  \n\n\nThese variables provide insight into how xylem functions. The goal here is to apply PCA to determine if key patterns in these data can be identified, as well as underlying factors or dimensions that may be driving the variation in the data. \n\n\nTo begin the analysis, the data are imported and explored using numerical and graphical data summaries.  \n\n::: {.panel-tabset}\n## R code\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Load the openxlsx package\nlibrary( openxlsx ) # Provides read.xlsx() \n\n# Import the .xlsx file\nxylemDF <- read.xlsx(\"datasets/PlantWaterPhysiology.xlsx\")\n\n# Print the names of the variables\nnames( xylemDF )\n#>  [1] \"Species\"       \"Family\"        \"P75\"           \"Ks\"           \n#>  [5] \"starch\"        \"xylem_density\" \"fiber_%\"       \"vessel_%\"     \n#>  [9] \"par_%\"         \"Pmin\"          \"water_storage\"\n\n# For PCA, only numerical variables can be present \n# in the data. We can either create a copy of the \n# sheet with non-numerical variables removed and \n# re-import the data, or remove the variables \n# in R as shown below.\n\n# Load the dplyr package\nlibrary(dplyr) # Provides the select() function\n\n# Create a new dataframe that only consists of numerical variables\n# Note: columns 1 and 2 denote the columns we need to remove.\nxylemDFnum <- select(xylemDF, \n                     -1 ,  # remove column 1 \n                     -2 )  # remove column 2\n\n\n# summarize the variables of interest \nsummary( xylemDFnum )\n#>       P75                Ks           starch       xylem_density   \n#>  Min.   :-15.360   Min.   :0.29   Min.   : 2.210   Min.   :0.4600  \n#>  1st Qu.: -7.760   1st Qu.:0.72   1st Qu.: 3.240   1st Qu.:0.5800  \n#>  Median : -3.920   Median :1.02   Median : 4.000   Median :0.6400  \n#>  Mean   : -5.399   Mean   :1.48   Mean   : 5.069   Mean   :0.6417  \n#>  3rd Qu.: -2.500   3rd Qu.:2.17   3rd Qu.: 5.980   3rd Qu.:0.7100  \n#>  Max.   : -1.380   Max.   :3.79   Max.   :12.900   Max.   :0.7900  \n#>     fiber_%         vessel_%         par_%            Pmin       \n#>  Min.   :42.22   Min.   : 7.78   Min.   : 7.11   Min.   :-8.250  \n#>  1st Qu.:60.28   1st Qu.:14.66   1st Qu.:14.95   1st Qu.:-5.710  \n#>  Median :64.91   Median :16.87   Median :17.30   Median :-3.900  \n#>  Mean   :64.25   Mean   :17.77   Mean   :17.46   Mean   :-4.267  \n#>  3rd Qu.:67.62   3rd Qu.:18.78   3rd Qu.:20.43   3rd Qu.:-2.830  \n#>  Max.   :84.30   Max.   :35.78   Max.   :31.28   Max.   :-1.670  \n#>  water_storage  \n#>  Min.   : 5.42  \n#>  1st Qu.: 9.08  \n#>  Median :13.28  \n#>  Mean   :12.64  \n#>  3rd Qu.:14.54  \n#>  Max.   :24.61\n\n# Load the gpairs package \nlibrary( gpairs ) # Provides gpairs()\n\n# Create scatterplot matrix with decreased font size\ngpairs( data.frame( xylemDFnum ) ,\n         diag.pars = list(fontsize = 6) )\n```\n\n::: {.cell-output-display}\n![](pca_files/figure-html/unnamed-chunk-2-1.png){fig-align='center' width=672}\n:::\n\n```{.r .cell-code}\n\n# Some potential outliers seen in the matrix. Examine them more closely \n# using a boxplot and do the same for other potential cases\n\n# Load the lattice package \nlibrary(lattice) # Provides bwplot()\n\n# Create a boxplot for the \"water_storage\" variable to \n# identify potential outliers\nbwplot(  ~ water_storage , \n           data= xylemDFnum ) \n```\n\n::: {.cell-output-display}\n![](pca_files/figure-html/unnamed-chunk-2-2.png){fig-align='center' width=672}\n:::\n\n```{.r .cell-code}\n\n# Compute standard correlation matrix \ncor( xylemDFnum )\n#>                      P75         Ks      starch xylem_density    fiber_%\n#> P75            1.0000000  0.6486291  0.50004669   -0.36963666 -0.4072020\n#> Ks             0.6486291  1.0000000  0.33916342   -0.26232492 -0.4217329\n#> starch         0.5000467  0.3391634  1.00000000   -0.22135129 -0.5299457\n#> xylem_density -0.3696367 -0.2623249 -0.22135129    1.00000000  0.3273450\n#> fiber_%       -0.4072020 -0.4217329 -0.52994575    0.32734503  1.0000000\n#> vessel_%       0.3151310  0.3337739  0.39992711   -0.53097026 -0.7522285\n#> par_%          0.2842809  0.1413345  0.33729586   -0.07180259 -0.7026932\n#> Pmin           0.8182375  0.5039328  0.56823143   -0.47661507 -0.4143263\n#> water_storage  0.2441534  0.2623565  0.09817602   -0.61754995 -0.2019742\n#>                 vessel_%       par_%       Pmin water_storage\n#> P75            0.3151310  0.28428093  0.8182375    0.24415343\n#> Ks             0.3337739  0.14133448  0.5039328    0.26235648\n#> starch         0.3999271  0.33729586  0.5682314    0.09817602\n#> xylem_density -0.5309703 -0.07180259 -0.4766151   -0.61754995\n#> fiber_%       -0.7522285 -0.70269315 -0.4143263   -0.20197421\n#> vessel_%       1.0000000  0.18413958  0.3928702    0.40577689\n#> par_%          0.1841396  1.00000000  0.1935726   -0.06949848\n#> Pmin           0.3928702  0.19357260  1.0000000    0.40564362\n#> water_storage  0.4057769 -0.06949848  0.4056436    1.00000000\n\n# Store the correlation matrix\nM <- cor( xylemDFnum )\n\n# Load the corrplot package \nlibrary( corrplot ) # Provides corrplot.mixed()\n\n# Better visualization  of the \n# correlation matrix\ncorrplot.mixed( M )\n```\n\n::: {.cell-output-display}\n![](pca_files/figure-html/unnamed-chunk-2-3.png){fig-align='center' width=672}\n:::\n:::\n\n\n## Video\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n```{=html}\n<div class=\"vembedr\">\n<div>\n<iframe src=\"https://www.youtube.com/embed/-7CfoXl2tv4\" width=\"533\" height=\"300\" frameborder=\"0\" allowfullscreen=\"\" data-external=\"1\"></iframe>\n</div>\n</div>\n```\n:::\n:::\n\n\n:::\n\nThe scatterplot and correlation matrix show  that the variables have both positive and negative correlations.  Many of the variables show clear linear associations, although the strength of the relationship varies depending on which variables are compared. The scatterplot matrix shows some potential outliers and such cases may be further explored using boxplots. In such cases, a transformation such as the natural log transformation may help reduce the influence of the outliers. Despite the presence of some potential outliers, we proceed with PCA without applying any transformations for the purpose of illustrating the method on this data. \n\nA good first step in PCA is it to compute the standard deviation for each PC and  determine how many PCs should be retained.  To compute the standard deviation for each PC, we conduct PCA computations on the data using `principal()`.\n\n::: {.panel-tabset}\n## R code\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Load the psych package\nlibrary( psych ) # Provides principal()\n\n# The function will require the following information:\n# dataframe: Replace with 'xylemDFnum'\n# nfactors: Set equal to 9\n# rotate: Set equal to \"none\"\n# cor: By default this is \"cor\", so it does not \n#      need to be provided.\n# Note: The result of principal() is saved to xylemPCA\nxylemPCA <- principal( xylemDFnum, \n                       nfactor= 9,\n                       rotate= \"none\") # 9 variables\n\nxylemPCA # Print xylemPCA object\n#> Principal Components Analysis\n#> Call: principal(r = xylemDFnum, nfactors = 9, rotate = \"none\")\n#> Standardized loadings (pattern matrix) based upon correlation matrix\n#>                 PC1   PC2   PC3   PC4   PC5   PC6   PC7   PC8   PC9 h2       u2\n#> P75            0.78  0.01  0.51 -0.03 -0.14 -0.17  0.12  0.24 -0.03  1  1.1e-16\n#> Ks             0.66 -0.04  0.39 -0.56  0.17  0.11 -0.21 -0.07  0.03  1  2.2e-16\n#> starch         0.67  0.31  0.16  0.49  0.27  0.24 -0.22  0.04  0.01  1  0.0e+00\n#> xylem_density -0.63  0.52  0.29 -0.11  0.21  0.28  0.34  0.02  0.02  1  4.4e-16\n#> fiber_%       -0.78 -0.43  0.39  0.14 -0.07 -0.01 -0.08  0.06  0.14  1  8.9e-16\n#> vessel_%       0.72 -0.08 -0.49 -0.05  0.41 -0.15  0.16  0.06  0.09  1  0.0e+00\n#> par_%          0.44  0.70 -0.24 -0.07 -0.48  0.06 -0.04  0.01  0.09  1 -6.7e-16\n#> Pmin           0.81 -0.14  0.38  0.23 -0.11 -0.07  0.23 -0.23  0.02  1  6.7e-16\n#> water_storage  0.50 -0.67 -0.24 -0.03 -0.21  0.42  0.11  0.06  0.00  1  8.9e-16\n#>               com\n#> P75           2.2\n#> Ks            3.2\n#> starch        3.5\n#> xylem_density 3.9\n#> fiber_%       2.3\n#> vessel_%      2.8\n#> par_%         2.9\n#> Pmin          2.1\n#> water_storage 3.3\n#> \n#>                        PC1  PC2  PC3  PC4  PC5  PC6  PC7  PC8  PC9\n#> SS loadings           4.14 1.52 1.18 0.65 0.63 0.39 0.32 0.13 0.04\n#> Proportion Var        0.46 0.17 0.13 0.07 0.07 0.04 0.04 0.01 0.00\n#> Cumulative Var        0.46 0.63 0.76 0.83 0.90 0.95 0.98 1.00 1.00\n#> Proportion Explained  0.46 0.17 0.13 0.07 0.07 0.04 0.04 0.01 0.00\n#> Cumulative Proportion 0.46 0.63 0.76 0.83 0.90 0.95 0.98 1.00 1.00\n#> \n#> Mean item complexity =  2.9\n#> Test of the hypothesis that 9 components are sufficient.\n#> \n#> The root mean square of the residuals (RMSR) is  0 \n#>  with the empirical chi square  0  with prob <  NA \n#> \n#> Fit based upon off diagonal values = 1\n```\n:::\n\n\n## Video\n\nSee previous video.\n\n:::\n\nThe printing the output of `xylemPCA` (a *principal* object) provides the following:\n\n- The squared standard deviation (variance) for each PC (denoted as `SS loadings` in the output).\n\n- The loadings for each PC. Recall that these can be interpreted as the  correlations between the variables and the components.  They are denoted as `Standardized loadings (pattern matrix) based upon correlation matrix`.\n\n- The proportion of variance for each PC (denoted as `Proportion Var`).\n\n- The  cumulative proportion of variance at a given PC (denoted as `Cumulative Var`)[^7]. \n\n[^7]: `SS loadings`, `Proportion Var`, and `Cumulative Var` are connected, as the proportion and cumulative proportion of variance are computed based on the squared standard deviation (variance) for each PC. \n\nNote that the first PC explains 46% of the variation, the first two PCs together explain about 63% of the variation, and the first three PCs explain about 76% of the variation, and so on. The next step in PCA is to determine an acceptably large percentage of variance that is explained by the PCs.\n \n:::\n\n\n## Determining the Number of PCs to retain\n\nThere are different methods to determine how many PCs to consider for retention, including:\n\n- Scree plot:  This plot displays the squared standard deviations (variance) explained by each principal component on the y-axis with the PCs shown on the x-axis. The variances are provided in descending order, so the amount of variance explained by each PC decreases  along the x-axis. The goal is to identify an \"elbow\" point  in the line and selects all components just before the line flattens out.\n\n- Kaiser's rule or  Kaiser-Guttman criterion: This rule retains the PC with  squared standard deviations greater than or equal to 1[^8]. \n\n[^8]: This rule assumes that the PCA is conducted using standardized data. If using un-standardized data, the variance will be affected by the units of measurement. With standardized data, all variables are on the same scale and the sum of the variances equals the number of variable.\n\nSimply note the size fo the variance of each PC to apply Kaiser's rule. To construct a screeplot, we use the function `fviz_eig.psych` which is a modified version of function called `fviz_eig` from the `factoextra` package. `fviz_eig.psych` was created to work with object created from `principal()`, where as `fviz_eig` does not work with such objects.\n\n::: {.callout-tip icon=\"false\"}\n\n## R functions\n\n```\n### fviz_eig.psych( `principal object` , choice , addlabels, ncp , xlab )\n# principal object:  Replace with the name of a  \n#                    principal object.\n# choice: Determine the scale of the height of the bars. \n#         Set equal to either \"variance\" or \"eigenvalue\". \n#         Default is \"variance\". \"eigenvalue\" will provide\n#         the square standard deviations of each PC. \"variance\"\n#         will provide the amount of variance explained by each PC\n# addlabels: If set to equal to TRUE, labels are added at the top of \n#            bars or points showing the information retained by each \n#            dimension. Default is FALSE.\n# ncp: Set equal the number of PCs to display. Default is 10.  \n# xlab: Label for x-axis. Default label is \"dimensions\"\n```\n:::\n \n\n::: callout-note\n\nHere we determine the number PCs to retain by applying Kaiser's rule and using a scree plot.  Recall that the \n*principal object* `xylemPCA` holds all the relevant PCA computations.   \n\nThe y-axis can either display the squared standard deviations (variances) of the PCs or the percentage of variance  explained but the shape does not change. Setting  `choice= \"variance\"` and `addlabels= TRUE` allows one to apply Kaiser's rule using the scree plot. \n\n::: {.panel-tabset}\n## R code\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# The function will require the following information:\n# dataframe: Replace with 'xylemDFnum'\n# center: By default this is true, so it is not required.\n# scale.: Set equal to TRUE.\n\nsource(\"rfuns/fviz_eig.psych.R\") # provides fviz_eig.psych()\n\n# Recall the principal object is `xylemPCA`\n# The plot displays the prop of variance \n# attributed to each PC.\nfviz_eig.psych(xylemPCA, \n         choice= \"variance\" , \n         addlabels= TRUE, \n         xlab= \"Principal components\")\n```\n\n::: {.cell-output-display}\n![](pca_files/figure-html/unnamed-chunk-5-1.png){fig-align='center' width=672}\n:::\n\n```{.r .cell-code}\n \n\n# The plot displays the squared\n# standard deviations of each PC, and \n# it can be used to apply Kaiser's rule.\n# Note: One can also examine the squared \n# standard deviations of each PC by printing \n# xylemPCA and noting the values for \"SS loadings\".\nfviz_eig.psych(xylemPCA, \n         choice= \"eigenvalue\" , \n         addlabels= TRUE, \n         xlab= \"Principal components\")\n```\n\n::: {.cell-output-display}\n![](pca_files/figure-html/unnamed-chunk-5-2.png){fig-align='center' width=672}\n:::\n:::\n\n\n## Video\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n```{=html}\n<div class=\"vembedr\">\n<div>\n<iframe src=\"https://www.youtube.com/embed/nqGom6SX7Is\" width=\"533\" height=\"300\" frameborder=\"0\" allowfullscreen=\"\" data-external=\"1\"></iframe>\n</div>\n</div>\n```\n:::\n:::\n\n\n:::\n\n\nNote that the scree plot shows that the squared standard deviations of the first three PCs are greater than 1. Further note that the first  three PC consist of the  components just before the line flattens out. In short, both the scree plot and Kaiser's rule suggest retaining the first 3 PCs. While Kaiser's rule is easy to apply, PCA must be done on the correlation matrix if applying this rule. The scree plot method does not rely on standardization, but identifying the elbow point may be subjective, and others may arrive at different conclusions based on their interpretation of the scree plot.\n\nNext, we focus on interpreting of the PCs. \n\n:::\n\n\n## Towards interpretating the PCs\n\nOnce the number of PCs to retain is determined, the PCs should be examined. Since PCA was performed on the standardized data, one approach to interpreting each component is to focus on the size of the loadings of a given PC, as they represent correlations between the  variables and the given PC. Here, we consider a loading at 0.7 or greater in magnitude as important[^9]. \n\n[^9]: There is no rule for determining how large loadings in a PC should be for them to be considered meaningful. Larger absolute values of loadings indicate a stronger association between the original variable and the principal component. Some researchers consider loadings with an absolute value greater than 0.4 or 0.5 to be significant, while others may require a higher threshold. Requiring a higher threshold, such as 0.7 represents a more stringent criterion, signifying that only variables with very strong relationships with a given PC would be interpreted, while variables with weaker relationships would not be considered. Setting a high threshold for factor loadings can be useful in some cases, such as when a high degree of assurance in identifying relationships between variables and a PC is sought. On the other hand, it may limit the ability to identify more subtle patterns or structures in the data.\n\nWe can examine the loadings by printing the *principal object* or using the function `loadings()` on *principal object*\n\n::: {.callout-tip icon=\"false\"}\n\n## R functions\n\n```\n### loadings( `principal object` )\n# principal object:  Replace with the name of a  \n#                    principal object.\n\n```\n:::\n\n\n::: callout-note\n\nRecall that the  *principal object*  `xylemPCA` holds all the relevant PCA computations.  \n\n \n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Recall the principal object is `xylemPCA`.\n# Save the result to an object\nPCAloadings <- loadings( xylemPCA )\n\n# display the loadings\nPCAloadings # loadings smaller than .1 are not displayed\n#> \n#> Loadings:\n#>               PC1    PC2    PC3    PC4    PC5    PC6    PC7    PC8    PC9   \n#> P75            0.783         0.511        -0.139 -0.175  0.122  0.243       \n#> Ks             0.661         0.394 -0.560  0.174  0.114 -0.209              \n#> starch         0.675  0.309  0.158  0.491  0.274  0.242 -0.218              \n#> xylem_density -0.630  0.521  0.287 -0.114  0.209  0.282  0.335              \n#> fiber_%       -0.781 -0.425  0.393  0.141                              0.143\n#> vessel_%       0.721        -0.492         0.408 -0.154  0.164              \n#> par_%          0.444  0.704 -0.242        -0.482                            \n#> Pmin           0.813 -0.142  0.376  0.230 -0.109         0.229 -0.234       \n#> water_storage  0.500 -0.672 -0.244        -0.210  0.422  0.112              \n#> \n#>                 PC1   PC2   PC3   PC4   PC5   PC6   PC7   PC8   PC9\n#> SS loadings    4.14 1.523 1.180 0.650 0.627 0.392 0.318 0.132 0.039\n#> Proportion Var 0.46 0.169 0.131 0.072 0.070 0.044 0.035 0.015 0.004\n#> Cumulative Var 0.46 0.629 0.760 0.832 0.902 0.946 0.981 0.996 1.000\n```\n:::\n\n\n \n\nHere, the loadings among the first three PC are nearly all large or close to being large for the first PC.  Such loadings means that the variables are highly correlated with the PCs, which can make it challenging to interpret the unique contribution of each variable to each PC. This makes it difficult to identify patterns or attributes  in data that may have interpretations or implications in the context of the data. In such instances, one can apply a rotation on the PCs.\n \n\n:::\n\nIt is not uncommon for the interpretation of loadings to be challenging, particularly when the retained principal components exhibit patterns of large or small loadings, making it difficult to interpret in the context of the data.  If most, if not all, of the loadings are large, this indicates that nearly all variables are highly correlated with the principal components, which can make it difficult to identify the unique contributions of individual variables to each component. On the other hand, if most, if not all, of the loadings are small, this may indicate that the data are too noisy.\nIf all the loadings are small, one may consider lowering the threshold for what is considered important. Applying a rotation on the retained PCs can help deal with instances in which the loadings are all large or small. \n\n## Rotating the PCs\n\nRotation transforms the retained PCs into a new set of linear combinations (i.e., leading to changes in the values of $e_{i1}, e_{i2}, ..., e_{ip}$) that may be easier to interpret. By rotating the retained PCs, a new set of loadings can be obtained  that may have a simpler structure and be easier to interpret compared to the original loadings. Varimax rotation[^10] is one commonly used rotation method in PCA. Here, we apply varimax rotation on the retained PCs. The varimax rotated PCs will still account for the same amount of information as the unrotated retained PCs. \n\n \n[^10]: Varimax rotation does not involve any additional computations to estimate the principal components, but rather takes the computed loadings and rotates them.  The loadings after rotation may have different magnitudes and signs compared to the original loadings, but they still represent the same underlying relationships between the variables and the components.   It is worth noting that there are several types of rotation methods available, including varimax, promax, and oblimin, each with their own strengths and limitations.\n\n\nTo provide a non-technical explanation of varimax rotating the PCs, recall the real estate analogy used earlier.  One deciding on a set of best pictures that better highlight the most desirable or best features of a property is akin to deciding how many PCs to retain.   However, some of the pictures that were selected may have similar or overlapping features, making it hard to tell them apart. Here, varimax rotation would be like the real estate agent taking the same pictures but using a different angle (\"rotating them\")  so that each  pictures better highlights distinct features and there is minimal overlap between the features in each picture. This new set of rotated pictures provides hopefully provides clearer and  better view of the property, making it easier to identify its unique features and characteristics. As before, this is just an attempt at an analogy but hopefully helps illustrate the idea of using varimax rotation on the PCs.\n \nThe function `principal()` by defaults applies a varimax rotation to the retained PC by setting `nfactors` equal to then number of retained PCs and having `rotate= \"varimax\"` (default `rotate` value).\n\n::: callout-note\n\n\nRecall Kaiser's rule suggested keeping the first three PCs.   Here we use varimax rotation to rotate the retained PCs.\n\n::: {.panel-tabset}\n## R code\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Note that nfactor is set to 3\n# since we retained 3 PCs. The argument\n# rotate is not needed since by default\n# is it \"varimax\"\nxylemPCAvmr <- principal( xylemDFnum, \n                       nfactor= 3) # The number of retained PC\n\nxylemPCAvmr\n#> Principal Components Analysis\n#> Call: principal(r = xylemDFnum, nfactors = 3)\n#> Standardized loadings (pattern matrix) based upon correlation matrix\n#>                 RC1   RC3   RC2   h2    u2 com\n#> P75            0.91  0.16  0.14 0.87 0.126 1.1\n#> Ks             0.74  0.12  0.17 0.59 0.406 1.2\n#> starch         0.58  0.49  0.05 0.58 0.424 2.0\n#> xylem_density -0.23 -0.09 -0.83 0.75 0.249 1.2\n#> fiber_%       -0.25 -0.89 -0.29 0.95 0.054 1.4\n#> vessel_%       0.14  0.55  0.67 0.77 0.232 2.0\n#> par_%          0.13  0.84 -0.15 0.75 0.249 1.1\n#> Pmin           0.83  0.13  0.33 0.82 0.178 1.4\n#> water_storage  0.18 -0.11  0.85 0.76 0.239 1.1\n#> \n#>                        RC1  RC3  RC2\n#> SS loadings           2.60 2.13 2.12\n#> Proportion Var        0.29 0.24 0.24\n#> Cumulative Var        0.29 0.53 0.76\n#> Proportion Explained  0.38 0.31 0.31\n#> Cumulative Proportion 0.38 0.69 1.00\n#> \n#> Mean item complexity =  1.4\n#> Test of the hypothesis that 3 components are sufficient.\n#> \n#> The root mean square of the residuals (RMSR) is  0.08 \n#>  with the empirical chi square  13.3  with prob <  0.35 \n#> \n#> Fit based upon off diagonal values = 0.96\n\n# xylemPCAvmr is a principal object\nvmrPCAloadings <- loadings( xylemPCAvmr )\n\n# display the loadings\nvmrPCAloadings # loadings smaller than .1 are not displayed\n#> \n#> Loadings:\n#>               RC1    RC3    RC2   \n#> P75            0.911  0.162  0.137\n#> Ks             0.742  0.121  0.168\n#> starch         0.578  0.490       \n#> xylem_density -0.233        -0.830\n#> fiber_%       -0.253 -0.892 -0.294\n#> vessel_%       0.144  0.550  0.667\n#> par_%          0.125  0.845 -0.148\n#> Pmin           0.835  0.134  0.327\n#> water_storage  0.176 -0.105  0.848\n#> \n#>                  RC1   RC3   RC2\n#> SS loadings    2.596 2.129 2.117\n#> Proportion Var 0.288 0.237 0.235\n#> Cumulative Var 0.288 0.525 0.760\n```\n:::\n\n\n\n## Video\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n```{=html}\n<div class=\"vembedr\">\n<div>\n<iframe src=\"https://www.youtube.com/embed/_lWGH46OJVg\" width=\"533\" height=\"300\" frameborder=\"0\" allowfullscreen=\"\" data-external=\"1\"></iframe>\n</div>\n</div>\n```\n:::\n:::\n\n\n:::\n\nNote that in the output, the rotated PCs presented in descending order in terms of the size of the squared standard deviations. The terms `SS loadings`, `Proportion Var`, and `Cumulative Var` mean the same as they did before.  The rotated PCs are given under `Loadings` and are labeled `RC1`, `RC3`, and `RC2` (note that they are presented based on their proportion of variance). Note that the total amount of variation explained by these three PCs remains the same as before.  \n \n:::\n\n\n\n\n## Interpretating  the PCs \n\nBelow, the rotated PCs are interpreted. It is important to note that the original principal components would have been interpreted in the same way if they were easily interpretable.  \n\n::: callout-note\n\n**The first PC**:  The first rotated PC shows a strong correlation with Pmin, P75, and Ks. This suggests that these variables vary in a similar way. Recall that we consider a correlation above 0.7 in magnitude (strong correlation) as important. This component explains 28.8% of the total variation in the data. Note, that the Pmin values represent how dehydrated a plant becomes on a seasonal basis (lower values denote greater tolerance of dehydration). Thus, shrub species with a lower Pmin  would be more tolerant to drought conditions and can tolerate greater water deficits than those with higher Pmin. Similarly, lower values of P75 indicate that water can be transported more safely during dry conditions, which is an adaptive trait in a semi-arid environment. However, higher levels of Ks can improve water transport efficiency by allowing water to move more easily through the xylem. This can help counter the negative effects of higher minimum hydrostatic pressure and higher P75 values on water efficiency since as Ks increases then Pmin and P75 tend to also increase. Hence, PC 1 may be viewed as an adaptability measure of plants to drought conditions with respect to water efficiency.\n\n**The second PC**:  The second rotated PC explains 23.5% of the variation in the data that is independent from the first PC[^11].  This PC shows a strong positive correlation with water storage capacity and vessel percentage, while showing a strong negative correlation with xylem density.  If a shrub has high xylem density then it has tissue that is strong and can resist damage from breaking; however, it will tend to have lower water storage capacity (capacitance). Water storage capacity can help provide water when it is limited, which can help maintain the shrub’s structural stability and prevent damage that can occur when dehydration is extreme. Therefore, this PC may be viewed as a measure of the adaptability of shrubs to drought conditions with respect to  mechanical strength and water storage.\n\n[^11]: Independent here means that PC 2 captures 23.5% of the remaining variation in the data that is not explained by the PC 1. Essentially, it represents a different aspect or pattern of variation within the data that is not covered by the first component.\n\n**The third PC**:  This component explains 23.7% of the remaining variation in the data that is not explained by either the first or second component. It exhibits a strong negative correlation with fiber percentage and a strong positive correlation with parenchyma percentage. The volume of space in the vascular tissue is occupied by three cell types: parenchyma, fibers, and vessels. Fibers are associated with mechanical strength of the plant and parenchyma are associated with starch storage so these cellular relationships can affect plant function.  This component suggests that species with a higher proportion of fibers tend to have a lower amount of parenchyma and vice versa, with vessels also loading positively on this axis but with a weaker correlation than the 0.7 cutoff.  This suggest that species in a water-limited environment compensate for having a lower percentage of fiber by having a higher percentage of parenchyma to maintain plant function.  Therefore, this PC can be considered as an indicator of the adaptability of shrubs to drought conditions, specifically in terms of their capacity to balance parenchyma and fiber to maintain essential plant functions.\n\n:::",
    "supporting": [
      "pca_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"site_libs/vembedr-0.1.5/css/vembedr.css\" rel=\"stylesheet\" />\r\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}