<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>13&nbsp; Analysis of variance (ANOVA) – Training modules on selected statistical methods</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./lr.html" rel="next">
<link href="./anovalin.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark-0a6b7249c26820e032cb0bd839ff02b1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-4b058e8f47af081303ddb0b93c0d0d5f.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="dark"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><link href="site_libs/vembedr-0.1.5/css/vembedr.css" rel="stylesheet">
<script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script><script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>
</head>
<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./anovalin.html">Module: ANOVA, linear regression, and logistic regression</a></li><li class="breadcrumb-item"><a href="./anova.html"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Analysis of variance (ANOVA)</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Training modules on selected statistical methods</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/emontoya2" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
    <div class="dropdown">
      <a href="" title="Share" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" role="link" aria-label="Share"><i class="bi bi-share"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-0">
<li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://twitter.com/intent/tweet?url=|url|">
              <i class="bi bi-twitter pe-1"></i>
            Twitter
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://www.facebook.com/sharer/sharer.php?u=|url|">
              <i class="bi bi-facebook pe-1"></i>
            Facebook
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://www.linkedin.com/sharing/share-offsite/?url=|url|">
              <i class="bi bi-linkedin pe-1"></i>
            LinkedIn
            </a>
          </li>
      </ul>
</div>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./casestudies.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module: Case Studies</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./datacs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Case study 1</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./datacs2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Case study 2</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./datacs3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Case study 3</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./datacs4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Case study 4</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./datacs5.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Case study 5</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./datacs6.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Case study 6</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module: Data basics and drawing statistical conclusions</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Basics of data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./drawingconclusions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Drawing statistical conclusions</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./summaries.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module:  Basic Exploratory  Data Analysis</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./catsum.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Summarizing categorical data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./numsum.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Summarizing numerical data</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./twosample.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module: Two sample methods</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./siframework.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Statistical inference framework via a case study</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./twoindptmeans.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Two sample methods</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./anovalin.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module: ANOVA, linear regression, and logistic regression</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./anova.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Analysis of variance (ANOVA)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./lr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Simple linear regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./logisticreg.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Simple logistic regression</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./eda.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module: Advanced Exploratory Data Analysis</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./pca.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">PCA</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./a1-startingR.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Installing or accessing R and RStudio</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./a2-firstR.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">A first session in RStudio</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./a3-basicsR.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Some basic tasks in R</span></span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Table of contents</h2>
   
  <ul>
<li><a href="#single-factor-or-one-way-anova" id="toc-single-factor-or-one-way-anova" class="nav-link active" data-scroll-target="#single-factor-or-one-way-anova"><span class="header-section-number">13.1</span> Single factor or one-way ANOVA</a></li>
  <li><a href="#kruskalwallis-test-single-factor-anova-for-ranks" id="toc-kruskalwallis-test-single-factor-anova-for-ranks" class="nav-link" data-scroll-target="#kruskalwallis-test-single-factor-anova-for-ranks"><span class="header-section-number">13.2</span> Kruskal–Wallis test (single-factor ANOVA for ranks)</a></li>
  <li>
<a href="#multiple-comparisons" id="toc-multiple-comparisons" class="nav-link" data-scroll-target="#multiple-comparisons"><span class="header-section-number">13.3</span> Multiple comparisons</a>
  <ul class="collapse">
<li><a href="#tukeys-hsd-method" id="toc-tukeys-hsd-method" class="nav-link" data-scroll-target="#tukeys-hsd-method"><span class="header-section-number">13.3.1</span> Tukey’s HSD method</a></li>
  <li><a href="#games-howell-test" id="toc-games-howell-test" class="nav-link" data-scroll-target="#games-howell-test"><span class="header-section-number">13.3.2</span> Games-Howell test</a></li>
  <li><a href="#dunn-test" id="toc-dunn-test" class="nav-link" data-scroll-target="#dunn-test"><span class="header-section-number">13.3.3</span> Dunn test</a></li>
  </ul>
</li>
  <li><a href="#sample-size-estimation-and-power-analysis-for-anova" id="toc-sample-size-estimation-and-power-analysis-for-anova" class="nav-link" data-scroll-target="#sample-size-estimation-and-power-analysis-for-anova"><span class="header-section-number">13.4</span> Sample size estimation and power analysis for ANOVA</a></li>
  </ul><div class="toc-actions"><ul><li><a href="https://github.com/emontoya2/edit/master/anova.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./anovalin.html">Module: ANOVA, linear regression, and logistic regression</a></li><li class="breadcrumb-item"><a href="./anova.html"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Analysis of variance (ANOVA)</span></a></li></ol></nav><div class="quarto-title">
<h1 class="title"><span id="sec-anova" class="quarto-section-identifier"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Analysis of variance (ANOVA)</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header><div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="images/linmod/anovaart.jpg" class="img-fluid figure-img" style="width:50.0%"></p>
<figcaption>AI-generated artwork inspired by “Analysis of variance”.</figcaption></figure>
</div>
<p>Analysis of Variance (ANOVA) is a statistical method that analyzes the variability of the observations in a dataset and compares it between groups or factor levels to determine if there is a statistically significant difference among them. This section covers the basics of ANOVA, and the following inferential methods for ANOVA:</p>
<ul>
<li><p>An F-test to determine whether there is a statistically significant difference among three or more treatments or groups.</p></li>
<li><p>A non-parametric alternative to the F-test.</p></li>
<li><p>Multiple comparison methods to determine which specific groups or treatments have significant differences.</p></li>
</ul>
<p>Equations/formulas used in hypothesis testing or confidence intervals will be kept at a minimum as the focus is on the use of software to carry out these methods. That being said, those new to or not comfortable with hypothesis testing or confidence intervals may want to consider reviewing <a href="siframework.html" class="quarto-xref"><span>Chapter 11</span></a>.</p>
<p>To ensure that statistical inferential methods provide meaningful results, several assumptions are made about the data on which the method is intended to be used.</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Data assumptions
</div>
</div>
<div class="callout-body-container callout-body">
<p>The methods discussed here assume one or more of the following assumptions about the data:</p>
<ul>
<li><p><strong>Assumption 1</strong>. <em>Independence of the observations</em>. Each subject or observation is independent within and across the factor levels or groups or treatments.</p></li>
<li><p><strong>Assumption 2</strong>. <em>No clear outliers</em> under each factor level or groups or treatments.</p></li>
<li><p><strong>Assumption 3</strong>. <em>Normality</em> or <em>large sample</em>. The data under each factor level or group or treatment should be roughly normally distributed or the sample for each factor level or group or treatment should be large.</p></li>
<li><p><strong>Assumption 4</strong>. <em>Equal variance or spread</em>. The variability in each factor level or groups or treatments should be approximately that of any other factor level or group.</p></li>
</ul>
<p>While these assumptions are addressed in the illustrations below using a case study, assumption 1 is assessed by considering how the study was conducted. Assumption 2 can be examined using histograms or boxplots for each group. For assumption 3, use QQ-plots within each group or a QQ-plot of the model residuals. Combining all groups in one QQ-plot can hide differences among them. Assumption 4 can be assessed using boxplots and sample standard deviations for each group.</p>
</div>
</div>
<p>The terms “factor levels”, “treatments”, and “groups” mean the same thing and will be used interchangeably, although “factor levels” or “treatments” are terms more associated with experiments and “groups” is a term more associated with observational studies. In these sections, R functions provided for conducting the aforementioned inferential methods are used and described. Other functions to import data, numerically or graphically summarize the data, and other tasks may be used but such functions are not described as they have been described and illustrated in detail in previous modules.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Notation
</div>
</div>
<div class="callout-body-container callout-body">
<p>For readability, we define the following notation for ANOVA:</p>
<ul>
<li><p><span class="math inline">\(\mu_1\)</span>, <span class="math inline">\(\mu_2\)</span>, …, <span class="math inline">\(\mu_k\)</span> denote the population or true mean response under each treatment <span class="math inline">\(1\)</span>, <span class="math inline">\(2\)</span>, …, <span class="math inline">\(k\)</span>, respectively.</p></li>
<li><p><span class="math inline">\(\mu\)</span> denote the population or true mean response across all treatments.</p></li>
<li><p><span class="math inline">\(\bar{y}_1\)</span>, <span class="math inline">\(\bar{y}_2\)</span>, …, <span class="math inline">\(\bar{y}_k\)</span> denote the sample mean response under treatment <span class="math inline">\(1\)</span>, <span class="math inline">\(2\)</span>, …, <span class="math inline">\(k\)</span>, respectively.</p></li>
<li><p><span class="math inline">\(s_1\)</span>, <span class="math inline">\(s_2\)</span>, …, <span class="math inline">\(s_k\)</span> denote the sample standard deviation under each treatment <span class="math inline">\(1\)</span>, <span class="math inline">\(2\)</span>, …, <span class="math inline">\(k\)</span>, respectively.</p></li>
<li><p><span class="math inline">\(\bar{y}=\)</span> sample mean response (across all treatments)</p></li>
<li><p><span class="math inline">\(n_1\)</span>, <span class="math inline">\(n_2\)</span>, …, <span class="math inline">\(n_k\)</span> denote the number of observations under each treatment <span class="math inline">\(1\)</span>, <span class="math inline">\(2\)</span>, …, <span class="math inline">\(k\)</span>, respectively.</p></li>
<li><p><span class="math inline">\(n=n_1+n_2+\cdots+ n_k\)</span> denote the total number of observations (across all treatment).</p></li>
<li><p><span class="math inline">\(\eta_1\)</span>, <span class="math inline">\(\eta_2\)</span>, …, <span class="math inline">\(\eta_k\)</span> denote the population or true median response under each treatment <span class="math inline">\(1\)</span>, <span class="math inline">\(2\)</span>, …, <span class="math inline">\(k\)</span>, respectively.</p></li>
</ul>
</div>
</div>
<section id="single-factor-or-one-way-anova" class="level2" data-number="13.1"><h2 data-number="13.1" class="anchored" data-anchor-id="single-factor-or-one-way-anova">
<span class="header-section-number">13.1</span> Single factor or one-way ANOVA</h2>
<p>ANOVA partitions the total variability in the data (the sample variance of the all the data) in terms of variability between treatments and the variability within treatments. The variability between groups may be quantified by a measure called the mean square between treatments, denoted by <span class="math inline">\(MST\)</span> or MS(Treatment)<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>. The variability within each treatment or group is quantified by the mean square error, denoted by <span class="math inline">\(MSE\)</span> or MS(Error). The higher the MS(Treatment), the more the variability in the data are due to the differences among factor levels or groups. The higher the MS(Error), the more the variability in the data are due to differences within the groups. In ANOVA, the hypothesis are</p>
<p><span class="math inline">\(H_0: \mu_1= \cdots=\mu_k\)</span> (The mean response is the same across all factor levels or treatments)</p>
<p><span class="math inline">\(H_a:\)</span> Not all treatment means are equal; at least one pair differs.</p>
<p>To test the hypothesis, ANOVA compares the variability between groups to the variability within groups and it assesses whether the differences between group means are statistically significant. The ratio of these two measures provides the test statistic for the F-test in single factor ANOVA:</p>
<p><span class="math display">\[F=\frac{ MS(Treatment)}{ MS(Error)}\]</span></p>
<p>If the assumptions hold and the group means are equal, MS(Treatment) and MS(Error) should be similar, so their ratio tends to be near 1. If the group means differ, MS(Treatment) tends to be larger and the ratio increases. Under <span class="math inline">\(H_0\)</span>, we use an F distribution with <span class="math inline">\(k-1\)</span> and <span class="math inline">\(n-k\)</span> degrees of freedom to compute the p-value.</p>
<p>Welch’s ANOVA is used when the group variances are not assumed equal. It adjusts for differences in group sizes and variability. Its test statistic, <span class="math inline">\(F_w\)</span>, and degrees of freedom are computed differently from those of the standard F-test<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a>. R does these calculations for us. The observations still need to be independent.</p>
<p>The function <code>sfaov()</code><a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a> obtains the information needed to conduct an F-test or Welch’s F-test and more using the data.</p>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>R functions
</div>
</div>
<div class="callout-body-container callout-body">
<pre><code>### sfaov( y ~ x , data , welch )
# y: Replace y with the name of the response (measured)
#  variable of interest.
# x: Replace x with the name of the factor or grouping
#  variable that distinguishes the different populations 
#  or treatments.
# data: Set equal to the data frame name
# welch: Set to TRUE for Welch's unequal-variance ANOVA.
#        The default FALSE uses the common-variance ANOVA.
#</code></pre>
</div>
</div>
<p>Many of the R functions used in these modules will have identical arguments. Therefore, while the arguments will be provided for any functions used, arguments such as <code>y</code>, <code>x</code>, <code>data</code>, and <code>welch</code> will generally no longer be described in this module.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>We use the data in <a href="datacs.html" class="quarto-xref"><span>Chapter 1</span></a> to compare mean survival percentages among the three light groups at <span class="math inline">\(\alpha=.10\)</span>. Keep in mind that the light groups also differ in turbidity. Therefore, the examples illustrate the methods, but cannot tell us whether light alone caused a difference.</p>
<p>To begin, we import the data, and then one would explore the data using numerical and graphical data summaries. Numerical and graphical data explorations were covered in other modules. However, we also use these type of summaries to assess model assumptions.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist">
<li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-1-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-1" role="tab" aria-controls="tabset-1-1" aria-selected="true" href="" aria-current="page">R code</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-2" role="tab" aria-controls="tabset-1-2" aria-selected="false" href="">Video</a></li>
</ul>
<div class="tab-content">
<div id="tabset-1-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-1-1-tab">
<div class="cell" data-layout-align="center">
<details open="" class="code-fold"><summary>Code</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Import data </span></span>
<span><span class="va">survdf</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/utils/read.table.html">read.csv</a></span><span class="op">(</span><span class="st">"datasets/dssurv.csv"</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Obtain the names of the variables in the data frame</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span> <span class="va">survdf</span> <span class="op">)</span></span>
<span><span class="co">#&gt; [1] "Light"     "Turbidity" "Survival"</span></span>
<span></span>
<span><span class="co"># Load the dplyr package</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://dplyr.tidyverse.org">dplyr</a></span><span class="op">)</span> <span class="co"># provides the mutate() function</span></span>
<span></span>
<span><span class="co"># Convert the "Light" and "Turbidity" variables to factors </span></span>
<span><span class="co"># using the mutate() function. </span></span>
<span><span class="va">survdf</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span><span class="va">survdf</span>, </span>
<span>         Light <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">as.factor</a></span><span class="op">(</span> <span class="va">Light</span> <span class="op">)</span>, </span>
<span>         Turbidity <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">as.factor</a></span><span class="op">(</span> <span class="va">Turbidity</span> <span class="op">)</span> <span class="op">)</span></span>
<span></span>
<span><span class="co"># Summarize the variables in the data frame using the summary() function</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span> <span class="va">survdf</span> <span class="op">)</span></span>
<span><span class="co">#&gt;   Light   Turbidity    Survival    </span></span>
<span><span class="co">#&gt;  high:8   high:8    Min.   :45.02  </span></span>
<span><span class="co">#&gt;  low :8   low :8    1st Qu.:55.79  </span></span>
<span><span class="co">#&gt;  med :4   med :4    Median :59.56  </span></span>
<span><span class="co">#&gt;                     Mean   :62.22  </span></span>
<span><span class="co">#&gt;                     3rd Qu.:67.24  </span></span>
<span><span class="co">#&gt;                     Max.   :89.09</span></span>
<span> </span>
<span><span class="co"># Load the lattice package for graphing functions</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://lattice.r-forge.r-project.org/">lattice</a></span><span class="op">)</span>  </span>
<span><span class="fu"><a href="https://rdrr.io/pkg/lattice/man/xyplot.html">bwplot</a></span><span class="op">(</span> <span class="va">Survival</span> <span class="op">~</span> <span class="va">Light</span> ,              <span class="co"># y ~ x</span></span>
<span>    data<span class="op">=</span> <span class="va">survdf</span> ,                      <span class="co"># Specify data frame</span></span>
<span>    xlab<span class="op">=</span> <span class="st">"Light intensity level"</span> ,     <span class="co"># Set x-axis label</span></span>
<span>    ylab<span class="op">=</span> <span class="st">"Survival rate"</span> ,             <span class="co"># Set y-axis label</span></span>
<span>    main<span class="op">=</span> <span class="st">"Survival vs Light intensity"</span> , <span class="co"># Specify plot title</span></span>
<span>    fill<span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"gray"</span>, <span class="st">"brown"</span>, <span class="st">"cyan"</span><span class="op">)</span> <span class="op">)</span>  <span class="co"># Specify color for each plot</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details><div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="anova_files/figure-html/unnamed-chunk-1-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
<details open="" class="code-fold"><summary>Code</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb3"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span></span>
<span></span>
<span><span class="co"># Source the function "normqqplot.R" so that </span></span>
<span><span class="co"># it's in R's memory.</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/source.html">source</a></span><span class="op">(</span><span class="st">"rfuns/normqqplot.R"</span><span class="op">)</span> <span class="co"># this function creates a normal QQ-plot</span></span>
<span></span>
<span><span class="co"># Create a normal QQ-plot under each group</span></span>
<span><span class="fu">normqqplot</span><span class="op">(</span> <span class="op">~</span> <span class="va">Survival</span> <span class="op">|</span> <span class="va">Light</span> ,    <span class="co"># ~ x | gfactor</span></span>
<span>       data<span class="op">=</span> <span class="va">survdf</span> , </span>
<span>       ylab<span class="op">=</span><span class="st">"Sample quantiles of survival percentage by light intensity"</span> <span class="op">)</span> </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details><div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="anova_files/figure-html/unnamed-chunk-1-2.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
<details open="" class="code-fold"><summary>Code</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb4"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span></span>
<span><span class="co"># Create a normal QQ-plot across all groups</span></span>
<span><span class="fu">normqqplot</span><span class="op">(</span> <span class="op">~</span> <span class="va">Survival</span>,             <span class="co"># ~ x  </span></span>
<span>      data<span class="op">=</span> <span class="va">survdf</span> , </span>
<span>      ylab<span class="op">=</span><span class="st">"Sample quantiles of survival percentage"</span> <span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details><div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="anova_files/figure-html/unnamed-chunk-1-3.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
<details open="" class="code-fold"><summary>Code</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb5"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span></span>
<span><span class="co"># Load the mosaic package </span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span> <span class="va"><a href="https://github.com/ProjectMOSAIC/mosaic">mosaic</a></span> <span class="op">)</span> <span class="co"># provides formula expression in sd()</span></span>
<span></span>
<span><span class="co"># Calculate the mean "Survival" for each "Light" level</span></span>
<span><span class="fu">mean</span><span class="op">(</span> <span class="va">Survival</span> <span class="op">~</span> <span class="va">Light</span> , </span>
<span>       data<span class="op">=</span> <span class="va">survdf</span> <span class="op">)</span></span>
<span><span class="co">#&gt;     high      low      med </span></span>
<span><span class="co">#&gt; 58.18500 59.60625 75.51750</span></span>
<span></span>
<span><span class="co"># Calculate the standard deviation "Survival" for each "Light" level</span></span>
<span><span class="fu"><a href="https://www.mosaic-web.org/mosaic/reference/aggregating.html">sd</a></span><span class="op">(</span> <span class="va">Survival</span> <span class="op">~</span> <span class="va">Light</span> , </span>
<span>    data<span class="op">=</span> <span class="va">survdf</span> <span class="op">)</span></span>
<span><span class="co">#&gt;      high       low       med </span></span>
<span><span class="co">#&gt;  6.345415 12.809045 12.242073</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</div>
<div id="tabset-1-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-2-tab">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="vembedr">
<div>
<iframe src="https://www.youtube.com/embed/yyDMj_Gjoys" width="533" height="300" frameborder="0" allowfullscreen="" data-external="1"></iframe>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
<p>The medium-light group has a different sample mean from the low- and high-light groups. The group sizes are small, so it is difficult to assess normality. We should also check whether the groups were measured independently. The examples below show the calculations, but the study design and assumptions need further assessment before drawing firm conclusions.</p>
<p>The boxplots suggest that the variability is not the same for the three groups. To further assess this assumption numerically, we use the sample standard deviations. The sample standard deviations under light intensity 4.5 and 6.75 are similar (12.809 and 12.242), but the sample standard deviation under high light intensity is much less. To determine if the variability in both groups is similar enough, we can use a rule of thumb - take the ratio of the largest and smallest sample standard deviations (12.809/6.345 or 6.345/12.809), and if the ratio is between .5 and 2, then the variability in both groups is considered similar enough. Both graphical and numerical assessments suggest that assumption 4 is not reasonable for the data. However, keep in mind that graphical assessments of assumptions are generally enough, and this rule of thumb should not be used if outliers are present.</p>
<p>For illustration, we carry out the standard F-test even though some assumptions are uncertain. Let <span class="math inline">\(\mu_1\)</span>, <span class="math inline">\(\mu_2\)</span>, and <span class="math inline">\(\mu_3\)</span> denote the true mean survival percentages for low, medium, and high light, respectively. The hypotheses are:</p>
<p><span class="math display">\[H_0: \mu_1=\mu_2=\mu_3 \qquad H_a: \text{Not all } μ_i\text{'s are equal}\]</span></p>
<p>In the context of ANOVA, we may also define the hypothesis in terms of an effect. Let <span class="math inline">\(\tau_i= \mu - \mu_i\)</span>, where <span class="math inline">\(\tau_i\)</span> measures the effect of the <span class="math inline">\(i\)</span>th factor level. The <span class="math inline">\(i\)</span>th effect is the difference between the overall mean and the mean of <span class="math inline">\(i\)</span>th factor level. In terms of effects, the hypothesis is</p>
<p><span class="math display">\[H_0: \tau_1=\tau_2=\tau_3=0 \qquad H_a: \text{Not all }\tau_i\text{'s are 0}\]</span></p>
<p>The following code uses <code>sfaov()</code> to compute the test statistic and the corresponding p-value for an F-test in single factor ANOVA:</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist">
<li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-2-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-1" role="tab" aria-controls="tabset-2-1" aria-selected="true" href="">R code</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-2-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-2" role="tab" aria-controls="tabset-2-2" aria-selected="false" href="">Video</a></li>
</ul>
<div class="tab-content">
<div id="tabset-2-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-2-1-tab">
<details open="" class="code-fold"><summary>Code</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb6"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Source the function so that it's R's memory.</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/source.html">source</a></span><span class="op">(</span><span class="st">"rfuns/sfaov.R"</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># The function will require the following information:</span></span>
<span><span class="co"># y: Replace with 'Survival'.</span></span>
<span><span class="co"># x: Replace with 'Light'.</span></span>
<span><span class="co"># data: set equal to a 'survdf'.</span></span>
<span><span class="co"># welch: default is FALSE so it does not </span></span>
<span><span class="co">#    need to be provided.</span></span>
<span><span class="fu">sfaov</span><span class="op">(</span> <span class="va">Survival</span> <span class="op">~</span> <span class="va">Light</span> , </span>
<span>       data<span class="op">=</span> <span class="va">survdf</span> <span class="op">)</span></span>
<span><span class="co">#&gt; One-way analysis of means (assuming equal variances) </span></span>
<span><span class="co">#&gt;  </span></span>
<span><span class="co">#&gt; data:  Survival ~ Light </span></span>
<span><span class="co">#&gt; ============== </span></span>
<span><span class="co">#&gt; ANOVA Table </span></span>
<span><span class="co">#&gt;           Df Sum Sq Mean Sq F value  p-value</span></span>
<span><span class="co">#&gt; Treatment  2  892.2  446.10   4.034 0.036839</span></span>
<span><span class="co">#&gt; Error     17 1880.0  110.59                 </span></span>
<span><span class="co">#&gt; ============== </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; R-squared=  0.322</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details><div class="cell quarto-layout-panel" data-layout-ncol="1" data-layout-align="center">

</div>
</div>
<div id="tabset-2-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-2-2-tab">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="vembedr">
<div>
<iframe src="https://www.youtube.com/embed/YlIIqzksOTg" width="533" height="300" frameborder="0" allowfullscreen="" data-external="1"></iframe>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
<p>The R output provides part of what is called an ANOVA table. An ANOVA table is a table that summarizes the results of an ANOVA test. It displays the sources of variation (Treatment [between groups], Error [within groups]), degrees of freedom, sums of squares, mean squares, F-test test statistic, and p-value<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a>. Below is a general form of ANOVA table.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 18%">
<col style="width: 21%">
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 7%">
</colgroup>
<thead><tr class="header">
<th>Source of Variation</th>
<th>Sum of Squares (SS)</th>
<th>Degrees of Freedom (df)</th>
<th>Mean Square (MS)</th>
<th>F-test Statistic</th>
<th>p-value</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>Treatment (Between)</td>
<td>SS(Treatment)</td>
<td>df(Treatment)</td>
<td>MS(Treatment)</td>
<td>F</td>
<td>p-value</td>
</tr>
<tr class="even">
<td>Error (Within)</td>
<td>SS(Error)</td>
<td>df(Error)</td>
<td>MS(Error)</td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>Total</td>
<td>SS(Total)</td>
<td>df(Total)</td>
<td></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<p>The output also provides the coefficient of determination or <span class="math inline">\(R^2\)</span>. <span class="math inline">\(R^2\)</span> is a number between 0 and 1, and it measures the proportion of variability in the response that can be explained or accounted for by the factor variable, and it is defined as SS(Treatment)/SS(Total). The higher <span class="math inline">\(R^2\)</span>, the larger the proportion of the total variation that is accounted for by the factor variable. However, either a high or low value of <span class="math inline">\(R^2\)</span> does not necessarily imply statistical significance.</p>
<p>The observed test statistic is <span class="math inline">\(F=4.034\)</span>, with a p-value of approximately <span class="math inline">\(.037\)</span>. Since the p-value is less than <span class="math inline">\(\alpha=.10\)</span>, we reject <span class="math inline">\(H_0\)</span> if the assumptions hold. This suggests that the group means differ. However, the concerns noted above limit this conclusion, and the result does not show that light alone caused the difference.</p>
<p>Recall that not all data assumptions are met (assumptions 3 and 4 are questionable). Welch’s F-test does not require assumption 4. We will assume assumption 3 is met for the data to illustrate Welch’s F-test. To carry out Welch’s F-test, we use <code>sfaov()</code> but with an additional argument of <code>welch=TRUE</code>:</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist">
<li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-3-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-1" role="tab" aria-controls="tabset-3-1" aria-selected="true" href="">R code</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-3-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-2" role="tab" aria-controls="tabset-3-2" aria-selected="false" href="">Video</a></li>
</ul>
<div class="tab-content">
<div id="tabset-3-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-3-1-tab">
<details open="" class="code-fold"><summary>Code</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb7"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span> </span>
<span><span class="co"># The function will require the following information:</span></span>
<span><span class="co"># y: Replace with 'Survival'.</span></span>
<span><span class="co"># x: Replace with 'Light'.</span></span>
<span><span class="co"># data: Set equal to a 'survdf'.</span></span>
<span><span class="co"># welch: Set equal to TRUE.</span></span>
<span><span class="fu">sfaov</span><span class="op">(</span> <span class="va">Survival</span> <span class="op">~</span> <span class="va">Light</span> , </span>
<span>       data<span class="op">=</span> <span class="va">survdf</span>, </span>
<span>       welch <span class="op">=</span> <span class="cn">TRUE</span> <span class="op">)</span></span>
<span><span class="co">#&gt; One-way analysis of means (not assuming equal variances) </span></span>
<span><span class="co">#&gt;  </span></span>
<span><span class="co">#&gt; data:  Survival ~ Light </span></span>
<span><span class="co">#&gt; ============== </span></span>
<span><span class="co">#&gt; ANOVA Table </span></span>
<span><span class="co">#&gt;              Df Sum Sq Mean Sq F value p-value</span></span>
<span><span class="co">#&gt; Treatment 2.000  892.2  446.10   3.236 0.10081</span></span>
<span><span class="co">#&gt; Error     7.037 1880.0  110.59                </span></span>
<span><span class="co">#&gt; ============== </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; R-squared=  0.322 </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Note: The Df for the Error component, F value and p-value provided are for Welch's F-test</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details><div class="cell quarto-layout-panel" data-layout-ncol="1" data-layout-align="center">

</div>
</div>
<div id="tabset-3-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-3-2-tab">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="vembedr">
<div>
<iframe src="https://www.youtube.com/embed/GzHeCMTftfo" width="533" height="300" frameborder="0" allowfullscreen="" data-external="1"></iframe>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
<p>The output is similar to that of the standard F-test. The F value, p-value, and df(Error) now correspond to Welch’s F-test. The df(Treatment) remains <span class="math inline">\(k-1\)</span>. The other summaries, including <span class="math inline">\(R^2\)</span>, have the same meaning as before.</p>
<p>Welch’s ANOVA gives <span class="math inline">\(F_w=3.236\)</span> and a p-value of approximately .10081. Since the p-value is slightly greater than <span class="math inline">\(\alpha=.10\)</span>, we fail to reject <span class="math inline">\(H_0\)</span>. This means there is not enough evidence of a difference at the chosen significance level; it does not prove that the means are equal. Welch’s method allows unequal variances, but the other study limitations still apply.</p>
</div>
</div>
</section><section id="kruskalwallis-test-single-factor-anova-for-ranks" class="level2" data-number="13.2"><h2 data-number="13.2" class="anchored" data-anchor-id="kruskalwallis-test-single-factor-anova-for-ranks">
<span class="header-section-number">13.2</span> Kruskal–Wallis test (single-factor ANOVA for ranks)</h2>
<p>The Kruskal–Wallis test uses the ranks of the observations to compare independent groups. It does not require normally distributed data. If the groups have distributions with similar shapes and spreads, the test can be used to compare medians. If their shapes or spreads differ, a significant result may reflect those differences instead.</p>
<p>Like ANOVA, it partitions the total variability in the data but when using the ranks of the data (not the data themselves). For the Kruskal–Wallis test, the hypotheses are</p>
<p><span class="math inline">\(H_0: \eta_1= \cdots=\eta_k\)</span> (The median response is the same across all factor levels or treatments)<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a></p>
<p><span class="math inline">\(H_a:\)</span> Not all group medians are equal, assuming the group distributions have similar shapes and spreads.</p>
<p>The Kruskal–Wallis test statistic is:</p>
<p><span class="math display">\[H=\frac{MSranks(Treatment)\times (k-1)}{ (SSranks(Total))/(n-1)}\]</span></p>
<p>Here MSranks(Treatment) describes differences among the groups using ranks, and SSranks(Total) describes the overall variation in the ranks. The test also accounts for tied observations. We use a chi-square distribution with <span class="math inline">\(k-1\)</span> degrees of freedom to approximate the p-value.</p>
<p>The function <code>sfkw()</code><a href="#fn6" class="footnote-ref" id="fnref6" role="doc-noteref"><sup>6</sup></a> obtains the information needed to conduct the Kruskal–Wallis test using the data.</p>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>R functions
</div>
</div>
<div class="callout-body-container callout-body">
<pre><code>### sfkw( y ~ x , data )
#</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>We use the Kruskal–Wallis test to compare survival among the three light groups at <span class="math inline">\(\alpha=.10\)</span>. As before, the observations need to be independent, and the light and turbidity differences cannot be separated in these data.</p>
<p>The data were imported and data assumptions were assessed when the F-test was applied in the previous section. Below we examine the medians and further explore the distribution of the data.</p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold"><summary>Code</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb9"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://lattice.r-forge.r-project.org/">lattice</a></span><span class="op">)</span> <span class="co"># provides the bwplot() function</span></span>
<span></span>
<span><span class="co"># Create violin boxplot</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/lattice/man/xyplot.html">bwplot</a></span><span class="op">(</span> <span class="va">Survival</span> <span class="op">~</span> <span class="va">Light</span> , </span>
<span>     data<span class="op">=</span> <span class="va">survdf</span> , </span>
<span>     xlab<span class="op">=</span> <span class="st">"Light intensity"</span>, </span>
<span>     ylab<span class="op">=</span> <span class="st">"Survival"</span> ,</span>
<span>     main<span class="op">=</span> <span class="st">"Survival vs Light intensity"</span> , </span>
<span>     panel<span class="op">=</span> <span class="va">panel.violin</span>, </span>
<span>     ylim<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">30</span>, <span class="fl">120</span><span class="op">)</span> <span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details><div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="anova_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
<details open="" class="code-fold"><summary>Code</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb10"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span></span>
<span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span> <span class="va"><a href="https://github.com/ProjectMOSAIC/mosaic">mosaic</a></span> <span class="op">)</span> <span class="co"># allows formula expression in median and iqr</span></span>
<span></span>
<span><span class="fu"><a href="https://www.mosaic-web.org/mosaic/reference/aggregating.html">median</a></span><span class="op">(</span> <span class="va">Survival</span> <span class="op">~</span> <span class="va">Light</span> , </span>
<span>        data<span class="op">=</span> <span class="va">survdf</span> <span class="op">)</span></span>
<span><span class="co">#&gt;   high    low    med </span></span>
<span><span class="co">#&gt; 58.720 56.420 75.525</span></span>
<span></span>
<span><span class="fu"><a href="https://www.mosaic-web.org/mosaic/reference/aggregating.html">iqr</a></span><span class="op">(</span> <span class="va">Survival</span> <span class="op">~</span> <span class="va">Light</span> , </span>
<span>     data<span class="op">=</span> <span class="va">survdf</span> <span class="op">)</span></span>
<span><span class="co">#&gt;    high     low     med </span></span>
<span><span class="co">#&gt;  6.2400  9.7375 16.3225</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>The difference in samples medians under intensity level 6.75 differs from intensity levels 4.5 and 9. The violin plots suggest that the data under each treatment do not all follow the same distribution. This means we cannot assess if the medians under each treatment differ but we formulate the hypothesis in terms of the mean of the ranks:</p>
<p><span class="math inline">\(H_0:\)</span> The mean ranks of survival under each light intensity are the same</p>
<p><span class="math inline">\(H_a:\)</span> Not all the mean ranks of survival under each light intensity are the same</p>
<p>The following code uses <code>sfkw()</code> to compute the test statistic and the corresponding p-value for the Kruskal–Wallis test:</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist">
<li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-4-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-4-1" role="tab" aria-controls="tabset-4-1" aria-selected="true" href="">R code</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-4-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-4-2" role="tab" aria-controls="tabset-4-2" aria-selected="false" href="">Video</a></li>
</ul>
<div class="tab-content">
<div id="tabset-4-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-4-1-tab">
<details open="" class="code-fold"><summary>Code</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb11"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Source the function so that it's R's memory.</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/source.html">source</a></span><span class="op">(</span><span class="st">"rfuns/sfkw.R"</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># The function will require the following information:</span></span>
<span><span class="co"># y: Replace with 'Survival'</span></span>
<span><span class="co"># x: Replace with 'Light'</span></span>
<span><span class="co"># data: Set equal to a 'survdf'</span></span>
<span><span class="fu">sfkw</span><span class="op">(</span> <span class="va">Survival</span> <span class="op">~</span> <span class="va">Light</span> , </span>
<span>      data<span class="op">=</span> <span class="va">survdf</span> <span class="op">)</span></span>
<span><span class="co">#&gt; Kruskal-Wallis test (single-factor ANOVA on ranks) </span></span>
<span><span class="co">#&gt;  </span></span>
<span><span class="co">#&gt; data:  Survival ~ Light </span></span>
<span><span class="co">#&gt; ============== </span></span>
<span><span class="co">#&gt; Kruskal-Wallis test statistic=  5.668 </span></span>
<span><span class="co">#&gt; p-value=  0.05878 </span></span>
<span><span class="co">#&gt; Approximate null distribution is chi-squared with df=  2 </span></span>
<span><span class="co">#&gt; ============== </span></span>
<span><span class="co">#&gt;  </span></span>
<span><span class="co">#&gt; Eta-squared=  0.2157563</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details><div class="cell quarto-layout-panel" data-layout-ncol="1" data-layout-align="center">

</div>
</div>
<div id="tabset-4-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-4-2-tab">

</div>
</div>
</div>
<p>The output provides the Kruskal-Wallis test statistic and corresponding p-value. The output also provides a measure akin coefficient of determination in traditional ANOVA called rank Eta or eta-squared. The measure eta-squared is appropriate for when the data are ranks, and it provides the proportion of the total variation in the response variable that is explained by the explanatory variable. Again, Eta-squared can be considered a non-parametric analogue to <span class="math inline">\(R^2\)</span>.</p>
<p>The observed test statistic is <span class="math inline">\(H=5.668\)</span>, with a p-value of approximately .05878. Since the p-value is less than <span class="math inline">\(\alpha=.10\)</span>, we reject <span class="math inline">\(H_0\)</span> if the assumptions hold. This suggests that the group distributions differ. Because their shapes differ, we cannot conclude from this test alone that their medians differ.</p>
</div>
</div>
</section><section id="multiple-comparisons" class="level2" data-number="13.3"><h2 data-number="13.3" class="anchored" data-anchor-id="multiple-comparisons">
<span class="header-section-number">13.3</span> Multiple comparisons</h2>
<p>If <span class="math inline">\(H_0\)</span> is rejected, it implies significant differences between the treatments or groups. However, this result does not indicate which specific groups differ from each other. Multiple comparisons refer to the process of making all pairwise comparisons between two or more groups when there are significant differences between the groups. These comparisons can be accomplished using a two-sample methods on all possible pairs. The scenario of testing many pairs of groups is called multiple comparisons.</p>
<p>There are a few problems associated with blindly carrying out two-sample methods on all possible pairwise comparisons</p>
<ul>
<li><p>The comparisons are not being done simultaneously and are being carried out individually with no regard to the other tests (comparisons).</p></li>
<li><p>The more pairwise comparisons conducted, the higher the chances of making at least one type I error among all the comparisons.</p></li>
</ul>
<p>Multiple comparisons in ANOVA are used to determine which specific groups or treatments are significantly different from each other. These procedures adjust the p-value and confidence level of each comparison so that the family-wise error rate (the probability of making at least one Type I error across all multiple comparisons), is at most <span class="math inline">\(\alpha\)</span>. We discuss a few multiple comparison methods that control the family wise error rate (FWER).</p>
<section id="tukeys-hsd-method" class="level3" data-number="13.3.1"><h3 data-number="13.3.1" class="anchored" data-anchor-id="tukeys-hsd-method">
<span class="header-section-number">13.3.1</span> Tukey’s HSD method</h3>
<p>In ANOVA, the most common method for multiple comparisons is called Tukey’s Honest Significant Difference (HSD) method. Tukey’s HSD method is used in single-factor ANOVA, and it adjusts the p-value or confidence level for each pairwise comparison to control the FWER for all possible pairwise comparisons, rather than for individual comparisons.</p>
<p>Recall that the function <code>sfaov()</code> can be used to conduct single-factor ANOVA. This function can also then conduct Tukey’s HSD method to adjust the p-values or confidence intervals for all pairwise comparisons among group or treatment means.</p>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>R functions
</div>
</div>
<div class="callout-body-container callout-body">
<pre><code>### sfaov( y ~ x , data , PWC, conf.level )
# PWC: Set equal to true to conduct all pairwise comparisons using
#   Tukey's HSD method. Default is FALSE 
# conf.level: Set equal to desired confidence level for all pairwise comparison. Default is .95
# </code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>The standard F-test gave evidence of a difference at <span class="math inline">\(\alpha=.10\)</span>. To illustrate how to identify which group means differ, we use Tukey’s HSD at the same significance level. The study limitations discussed above still apply.</p>
<p>The following code uses <code>sfaov()</code> to help conduct the ANOVA F-test and pairwise multiple comparisons using Tukey’s HSD method at <span class="math inline">\(\alpha=.10\)</span><a href="#fn7" class="footnote-ref" id="fnref7" role="doc-noteref"><sup>7</sup></a>.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist">
<li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-5-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-5-1" role="tab" aria-controls="tabset-5-1" aria-selected="true" href="">R code</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-5-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-5-2" role="tab" aria-controls="tabset-5-2" aria-selected="false" href="">Video</a></li>
</ul>
<div class="tab-content">
<div id="tabset-5-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-5-1-tab">
<div class="cell" data-layout-align="center">
<details open="" class="code-fold"><summary>Code</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb13"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Source the function so that it's R's memory.</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/source.html">source</a></span><span class="op">(</span><span class="st">"rfuns/sfaov.R"</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># The function will require the following information:</span></span>
<span><span class="co"># y: Replace with 'Survival'.</span></span>
<span><span class="co"># x: Replace with 'Light'.</span></span>
<span><span class="co"># data: Set equal to a 'survdf'.</span></span>
<span><span class="co"># PWC: Set equal to TRUE.</span></span>
<span><span class="co"># conf.level: Set equal to .90.</span></span>
<span><span class="fu">sfaov</span><span class="op">(</span> <span class="va">Survival</span> <span class="op">~</span> <span class="va">Light</span> , </span>
<span>    data<span class="op">=</span> <span class="va">survdf</span> , </span>
<span>    PWC<span class="op">=</span> <span class="cn">TRUE</span> , </span>
<span>    conf.level<span class="op">=</span><span class="fl">.90</span> <span class="op">)</span></span>
<span><span class="co">#&gt; One-way analysis of means (assuming equal variances) </span></span>
<span><span class="co">#&gt;  </span></span>
<span><span class="co">#&gt; data:  Survival ~ Light </span></span>
<span><span class="co">#&gt; ============== </span></span>
<span><span class="co">#&gt; ANOVA Table </span></span>
<span><span class="co">#&gt;           Df Sum Sq Mean Sq F value  p-value</span></span>
<span><span class="co">#&gt; Treatment  2  892.2  446.10   4.034 0.036839</span></span>
<span><span class="co">#&gt; Error     17 1880.0  110.59                 </span></span>
<span><span class="co">#&gt; ============== </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; R-squared=  0.322 </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Sample group means: high-58.18  low-59.61  med-75.52  </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Tukey multiple comparisons of means </span></span>
<span><span class="co">#&gt;              diff        lwr      upr      p adj</span></span>
<span><span class="co">#&gt; low-high  1.42125 -10.142221 12.98472 0.96061638</span></span>
<span><span class="co">#&gt; med-high 17.33250   3.170198 31.49480 0.03898149</span></span>
<span><span class="co">#&gt; med-low  15.91125   1.748948 30.07355 0.06006956</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</div>
<div id="tabset-5-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-5-2-tab">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="vembedr">
<div>
<iframe src="https://www.youtube.com/embed/KKJChWLo6ZI" width="533" height="300" frameborder="0" allowfullscreen="" data-external="1"></iframe>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
<p>The output from <code>sfaov()</code> now provides the results of Tukey’s HSD method which displays the difference in the sample treatment means, confidence interval, and p-value for each pairwise comparison. Note that the first confidence interval compares low to medium light intensity (CI for <span class="math inline">\(\mu_1-\mu_2\)</span> and p-value for testing <span class="math inline">\(\mu_1-\mu_2\neq 0\)</span>). The comparisons that follow are for <span class="math inline">\(\mu_1-\mu_3\)</span> and <span class="math inline">\(\mu_2-\mu_3\)</span>. Tukey’s HSD pairwise comparisons reveal significant differences in mean survival rates between different levels of light intensity at FWER of <span class="math inline">\(.10\)</span>. Specifically, the mean survival rate under medium light intensity is significantly different from both low and high light intensity (in terms of pairwise comparisons). Additionally, the mean survival rates between low and high light intensity were not significantly different from each other.</p>
</div>
</div>
</section><section id="games-howell-test" class="level3" data-number="13.3.2"><h3 data-number="13.3.2" class="anchored" data-anchor-id="games-howell-test">
<span class="header-section-number">13.3.2</span> Games-Howell test</h3>
<p>The Games-Howell test is a method for performing pairwise multiple comparisons when using Welch’s F-test. This test is somewhat similar to Tukey’s HSD method. Recall that the function <code>sfaov()</code> can be used to conduct Welch’s F-test. This function can also then conduct the Games-Howell test to adjust the p-values or confidence intervals for all pairwise comparisons among group or treatment means.</p>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>R functions
</div>
</div>
<div class="callout-body-container callout-body">
<pre><code>### sfaov( y ~ x , data , PWC, conf.level, welch )
# PWC: Set equal to true to conduct all pairwise comparisons using
#      Tukey's HSD method. Default is FALSE.
# conf.level: Set equal to desired confidence level for all pairwise comparison. Default is .95.
# welch: Set equal to TRUE for Welch's F-test.
#</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Welch’s F-test did not give enough evidence of different group means at <span class="math inline">\(\alpha=.10\)</span>. For illustration, we show how to carry out Games–Howell comparisons with 90% confidence intervals. The same study limitations apply.</p>
<p>The following code uses <code>sfaov()</code> to conduct the Welch’s F-test and all pairwise multiple comparisons using the Games-Howell test at <span class="math inline">\(\alpha=.10\)</span>:</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist">
<li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-6-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-6-1" role="tab" aria-controls="tabset-6-1" aria-selected="true" href="">R code</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-6-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-6-2" role="tab" aria-controls="tabset-6-2" aria-selected="false" href="">Video</a></li>
</ul>
<div class="tab-content">
<div id="tabset-6-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-6-1-tab">
<div class="cell" data-layout-align="center">
<details open="" class="code-fold"><summary>Code</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb15"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Source the function so that it's in R's memory.</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/source.html">source</a></span><span class="op">(</span><span class="st">"rfuns/sfaov.R"</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># The function will require the following information:</span></span>
<span><span class="co"># y: Replace with 'Survival'.</span></span>
<span><span class="co"># x: Replace with 'Light'.</span></span>
<span><span class="co"># data: Set equal to a 'survdf'.</span></span>
<span><span class="co"># PWC: Set equal to TRUE.</span></span>
<span><span class="co"># conf.level: Set equal to .90.</span></span>
<span><span class="co"># welch: Set equal to TRUE.</span></span>
<span><span class="fu">sfaov</span><span class="op">(</span> <span class="va">Survival</span> <span class="op">~</span> <span class="va">Light</span> , </span>
<span>       data<span class="op">=</span> <span class="va">survdf</span> , </span>
<span>       PWC<span class="op">=</span> <span class="cn">TRUE</span>, </span>
<span>       conf.level<span class="op">=</span> <span class="fl">.90</span>, </span>
<span>       welch<span class="op">=</span> <span class="cn">TRUE</span> <span class="op">)</span></span>
<span><span class="co">#&gt; One-way analysis of means (not assuming equal variances) </span></span>
<span><span class="co">#&gt;  </span></span>
<span><span class="co">#&gt; data:  Survival ~ Light </span></span>
<span><span class="co">#&gt; ============== </span></span>
<span><span class="co">#&gt; ANOVA Table </span></span>
<span><span class="co">#&gt;              Df Sum Sq Mean Sq F value p-value</span></span>
<span><span class="co">#&gt; Treatment 2.000  892.2  446.10   3.236 0.10081</span></span>
<span><span class="co">#&gt; Error     7.037 1880.0  110.59                </span></span>
<span><span class="co">#&gt; ============== </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; R-squared=  0.322 </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Note: The Df for the Error component, F value and p-value provided are for Welch's F-test </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Sample group means: high-58.18  low-59.61  med-75.52  </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Games-Howell multiple comparisons of means </span></span>
<span><span class="co">#&gt;       groups      diff       lwr       upr     p adj</span></span>
<span><span class="co">#&gt; 1 low : high   1.42125 -10.23181 13.074308 0.9575207</span></span>
<span><span class="co">#&gt; 2  low : med -15.91125 -34.83432  3.011821 0.1680024</span></span>
<span><span class="co">#&gt; 3 high : med -17.33250 -35.93898  1.273985 0.1203842</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</div>
<div id="tabset-6-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-6-2-tab">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="vembedr">
<div>
<iframe src="https://www.youtube.com/embed/SOMRHhyeI_M" width="533" height="300" frameborder="0" allowfullscreen="" data-external="1"></iframe>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
<p>The R output from <code>sfaov()</code> now provides the results of the Games-Howell test and it displays the difference in the sample treatment means, confidence interval, and p-value for each pairwise comparison. Note that the first confidence interval compares low to high light intensity (CI for <span class="math inline">\(\mu_1-\mu_3\)</span> and p-value for testing <span class="math inline">\(\mu_1-\mu_3\neq 0\)</span>). The comparisons that follow are for <span class="math inline">\(\mu_1-\mu_2\)</span> and <span class="math inline">\(\mu_3-\mu_2\)</span>. The Games-Howell test for pairwise comparisons reveal that there are no significant differences in mean survival rates between different levels of light intensity at FWER=<span class="math inline">\(.10\)</span>.</p>
</div>
</div>
</section><section id="dunn-test" class="level3" data-number="13.3.3"><h3 data-number="13.3.3" class="anchored" data-anchor-id="dunn-test">
<span class="header-section-number">13.3.3</span> Dunn test</h3>
<p>Dunn’s test compares the average ranks for each pair of groups. Holm’s correction adjusts the p-values to account for making several comparisons. The <code>sfkw()</code> function provides these results after the Kruskal–Wallis test<a href="#fn8" class="footnote-ref" id="fnref8" role="doc-noteref"><sup>8</sup></a>.</p>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>R functions
</div>
</div>
<div class="callout-body-container callout-body">
<pre><code>### sfkw( y ~ x , data , PWC )
# PWC: Set equal to true to conduct all pairwise comparisons using
#      Tukey's HSD method. Default is FALSE 
#</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>The Kruskal–Wallis test gave evidence that the group distributions differ at <span class="math inline">\(\alpha=.10\)</span>. The following Dunn comparisons help identify which pairs differ in their average ranks. These comparisons still cannot separate the effects of light and turbidity.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist">
<li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-7-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-7-1" role="tab" aria-controls="tabset-7-1" aria-selected="true" href="">R code</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-7-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-7-2" role="tab" aria-controls="tabset-7-2" aria-selected="false" href="">Video</a></li>
</ul>
<div class="tab-content">
<div id="tabset-7-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-7-1-tab">
<div class="cell" data-layout-align="center">
<details open="" class="code-fold"><summary>Code</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb17"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Source the function so that it's in R's memory.</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/source.html">source</a></span><span class="op">(</span><span class="st">"rfuns/sfkw.R"</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># The function will require the following information:</span></span>
<span><span class="co"># y: replace with 'Survival'</span></span>
<span><span class="co"># x: replace with 'Light'</span></span>
<span><span class="co"># data: set equal to a 'survdf'</span></span>
<span><span class="co"># PWC: set equal to TRUE</span></span>
<span><span class="fu">sfkw</span><span class="op">(</span> <span class="va">Survival</span> <span class="op">~</span> <span class="va">Light</span> , </span>
<span>      data<span class="op">=</span> <span class="va">survdf</span> , </span>
<span>      PWC<span class="op">=</span> <span class="cn">TRUE</span> <span class="op">)</span></span>
<span><span class="co">#&gt; Kruskal-Wallis test (single-factor ANOVA on ranks) </span></span>
<span><span class="co">#&gt;  </span></span>
<span><span class="co">#&gt; data:  Survival ~ Light </span></span>
<span><span class="co">#&gt; ============== </span></span>
<span><span class="co">#&gt; Kruskal-Wallis test statistic=  5.668 </span></span>
<span><span class="co">#&gt; p-value=  0.05878 </span></span>
<span><span class="co">#&gt; Approximate null distribution is chi-squared with df=  2 </span></span>
<span><span class="co">#&gt; ============== </span></span>
<span><span class="co">#&gt;  </span></span>
<span><span class="co">#&gt; Eta-squared=  0.2157563</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Sample group medians: high-58.72  low-56.42  med-75.525</span></span>
<span><span class="co">#&gt;   Comparison         Z    P.unadj      P.adj</span></span>
<span><span class="co">#&gt; 1 high - low  0.295804 0.76737978 0.76737978</span></span>
<span><span class="co">#&gt; 2 high - med -2.035693 0.04178115 0.08356230</span></span>
<span><span class="co">#&gt; 3  low - med -2.277216 0.02277331 0.06831993</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</div>
<div id="tabset-7-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-7-2-tab">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="vembedr">
<div>
<iframe src="https://www.youtube.com/embed/LTkiGkxMuKc" width="533" height="300" frameborder="0" allowfullscreen="" data-external="1"></iframe>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
<p>The output from <code>sfkw()</code> now provides the results of Dunn’s test, displaying adjusted p-values (<code>P.adj</code>) for each comparison. Note that the first comparison is comparing low to medium light intensity with the last comparison being between medium and high light intensity. Dunn’s test for pairwise comparisons reveals significant differences in survival rates between different levels of light intensity at FWER of <span class="math inline">\(.10\)</span>. Specifically, the survival rate under medium light intensity is significantly different from both low and high light intensity (in terms of pairwise comparisons). Additionally, survival rates between low and high light intensity were not significantly different from each other. Note that the comparisons are being done in terms of mean ranks since the data distribution under each treatment did not follow the same shape.</p>
</div>
</div>
</section></section><section id="sample-size-estimation-and-power-analysis-for-anova" class="level2" data-number="13.4"><h2 data-number="13.4" class="anchored" data-anchor-id="sample-size-estimation-and-power-analysis-for-anova">
<span class="header-section-number">13.4</span> Sample size estimation and power analysis for ANOVA</h2>
<p>Ideally, estimating the sample size for a study is one of the first things that researchers do prior to collecting data. Knowing the required sample size to detect a desired effect at the beginning of a project allows one to manage their data collection efforts. Furthermore, this allows for one to determine how much statistical power the test will have to detect an effect if it exists.</p>
<p>The R function <code><a href="https://rdrr.io/pkg/pwr/man/pwr.anova.test.html">pwr.anova.test()</a></code> from the <code>pwr</code> R package calculates statistical power for a balanced single-factor ANOVA, given the sample size, significance level (<span class="math inline">\(\alpha\)</span>), and effect size. Note that all treatments are assumed to have the same number of observations, which is known as a “balanced” design. It is assumed that the appropriate assumptions about the data are met<a href="#fn9" class="footnote-ref" id="fnref9" role="doc-noteref"><sup>9</sup></a>.</p>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>R functions
</div>
</div>
<div class="callout-body-container callout-body">
<pre><code>### pwr.anova.test( n , delta , sd1 , sd2 , sig.level , 
###           power, alternative)
# k: Set equal to the number of groups/treatments.
# n: Set equal to the number of observations per group.
# f: Set equal to the effect size.
# sig.level: Set equal to the desired alpha value (significance level).
# power: Set equal to the desired power (a number between 0 and 1). 
#</code></pre>
</div>
</div>
<p>Cohen’s <span class="math inline">\(f\)</span> describes how much the group means differ relative to the variation within the groups. Larger values indicate a larger effect. The standard deviation used here describes variation within groups, rather than variation in all observations combined. Common guidelines are:</p>
<ul>
<li><p>Small effect size: <span class="math inline">\(f = 0.10\)</span></p></li>
<li><p>Medium effect size: <span class="math inline">\(f = 0.25\)</span></p></li>
<li><p>Large effect size: <span class="math inline">\(f = 0.40\)</span> or higher.</p></li>
</ul>
<p>These are suggested guidelines and may vary slightly depending on the specific field of research or context of the study.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Suppose we want to determine the statistical power to detect a medium-sized effect assuming five observations per group and at significance level of <span class="math inline">\(\alpha=.01\)</span> and <span class="math inline">\(\alpha=.10\)</span>. Recall that there are three groups:</p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold"><summary>Code</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb19"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Load the "pwr" package</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/heliosdrm/pwr">pwr</a></span><span class="op">)</span> <span class="co"># Provides pwr.anova.test</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/pwr/man/pwr.anova.test.html">pwr.anova.test</a></span><span class="op">(</span>k <span class="op">=</span> <span class="fl">3</span> , </span>
<span>               n <span class="op">=</span> <span class="fl">5</span> , </span>
<span>               f <span class="op">=</span> <span class="fl">.25</span> , </span>
<span>               sig.level <span class="op">=</span> <span class="fl">.01</span> <span class="op">)</span> </span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;      Balanced one-way analysis of variance power calculation </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;               k = 3</span></span>
<span><span class="co">#&gt;               n = 5</span></span>
<span><span class="co">#&gt;               f = 0.25</span></span>
<span><span class="co">#&gt;       sig.level = 0.01</span></span>
<span><span class="co">#&gt;           power = 0.02811243</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; NOTE: n is number in each group</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>The statistical power of this test is low. To increase the power, one may increase the effect size (the larger it is, the easier it is to detect), increase <span class="math inline">\(\alpha\)</span> (make it easier to reject <span class="math inline">\(H_0\)</span> and find a significant effect), and/or increase the number of observations per group.</p>
</div>
</div>


</section><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><hr>
<ol>
<li id="fn1"><p>The MST is also commonly referred to as the mean square between groups (MSG).<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>The exact calculation used here is implemented by R’s <code>oneway.test(..., var.equal=FALSE)</code>.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p><code>sfaov()</code> is a wrapper function for <code><a href="https://rdrr.io/r/stats/aov.html">aov()</a></code>, <code><a href="https://rdrr.io/r/stats/oneway.test.html">oneway.test()</a></code>, and <code><a href="https://rdrr.io/r/stats/TukeyHSD.html">TukeyHSD()</a></code> and it incorporates additional options. A wrapper function is a function that calls another function or a set of functions to simplify or extend tasks<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>SS(Treatment) refers to the sum of squares Treatment. The rest of table elements are defined in an analogous manner for the SS, df, and MS. SS(Total) is a measure of the total variation in the data, ignoring the groups or treatments. The sum of squares treatment or SS(Treatment) measures how far the individual sample means are from the overall sample mean, and the sum of squares error or SS(Error) measures how far observations are from the sample mean of its group.<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p>If the groups have different shapes or spreads, interpret a significant result as evidence that their distributions differ, rather than only their medians.<a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn6"><p><code>sfkw()</code> is a wrapper function for <code><a href="https://rdrr.io/r/stats/kruskal.test.html">kruskal.test()</a></code> but it incorporates additional options.<a href="#fnref6" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn7"><p>Significance or <span class="math inline">\(\alpha\)</span> level equals one minus the confidence level. For example, if <span class="math inline">\(\alpha=.05\)</span>, the corresponding confidence level is <span class="math inline">\(1-\alpha=1-.05=.95\)</span>.<a href="#fnref7" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn8"><p>The function reports adjusted p-values for the comparisons, rather than confidence intervals.<a href="#fnref8" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn9"><p>There are R functions to compute for the Kruskal-Wallis test or Welch’s F-test, these functions may be difficult to use for those not familiar with power analysis.<a href="#fnref9" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol></section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/emontoya2\.github\.io\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./anovalin.html" class="pagination-link" aria-label="Module: ANOVA, linear regression, and logistic regression">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Module: ANOVA, linear regression, and logistic regression</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./lr.html" class="pagination-link" aria-label="Simple linear regression">
        <span class="nav-page-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Simple linear regression</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/emontoya2/edit/master/anova.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li></ul></div></div></div></footer></body></html>