<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>14&nbsp; Simple linear regression – Training modules on selected statistical methods</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./logisticreg.html" rel="next">
<link href="./anova.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark-0a6b7249c26820e032cb0bd839ff02b1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-4b058e8f47af081303ddb0b93c0d0d5f.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="dark"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><link href="site_libs/vembedr-0.1.5/css/vembedr.css" rel="stylesheet">
<script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script><script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>
</head>
<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./anovalin.html">Module: ANOVA, linear regression, and logistic regression</a></li><li class="breadcrumb-item"><a href="./lr.html"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Simple linear regression</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Training modules on selected statistical methods</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/emontoya2" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
    <div class="dropdown">
      <a href="" title="Share" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" role="link" aria-label="Share"><i class="bi bi-share"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-0">
<li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://twitter.com/intent/tweet?url=|url|">
              <i class="bi bi-twitter pe-1"></i>
            Twitter
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://www.facebook.com/sharer/sharer.php?u=|url|">
              <i class="bi bi-facebook pe-1"></i>
            Facebook
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://www.linkedin.com/sharing/share-offsite/?url=|url|">
              <i class="bi bi-linkedin pe-1"></i>
            LinkedIn
            </a>
          </li>
      </ul>
</div>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./casestudies.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module: Case Studies</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./datacs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Case study 1</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./datacs2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Case study 2</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./datacs3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Case study 3</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./datacs4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Case study 4</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./datacs5.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Case study 5</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./datacs6.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Case study 6</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module: Data basics and drawing statistical conclusions</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Basics of data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./drawingconclusions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Drawing statistical conclusions</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./summaries.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module:  Basic Exploratory  Data Analysis</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./catsum.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Summarizing categorical data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./numsum.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Summarizing numerical data</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./twosample.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module: Two sample methods</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./siframework.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Statistical inference framework via a case study</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./twoindptmeans.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Two sample methods</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./anovalin.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module: ANOVA, linear regression, and logistic regression</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./anova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Analysis of variance (ANOVA)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./lr.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Simple linear regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./logisticreg.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Simple logistic regression</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./eda.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module: Advanced Exploratory Data Analysis</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./pca.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">PCA</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./a1-startingR.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Installing or accessing R and RStudio</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./a2-firstR.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">A first session in RStudio</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./a3-basicsR.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Some basic tasks in R</span></span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Table of contents</h2>
   
  <ul>
<li><a href="#fitting-the-slr-model-and-model-diagnostics." id="toc-fitting-the-slr-model-and-model-diagnostics." class="nav-link active" data-scroll-target="#fitting-the-slr-model-and-model-diagnostics."><span class="header-section-number">14.1</span> Fitting the SLR model and model diagnostics.</a></li>
  <li><a href="#testing-the-significance-of-the-linear-relationship-using-t-based-methods." id="toc-testing-the-significance-of-the-linear-relationship-using-t-based-methods." class="nav-link" data-scroll-target="#testing-the-significance-of-the-linear-relationship-using-t-based-methods."><span class="header-section-number">14.2</span> Testing the significance of the linear relationship using t-based methods.</a></li>
  <li><a href="#testing-the-significance-of-the-linear-relationship-using-a-randomization-test" id="toc-testing-the-significance-of-the-linear-relationship-using-a-randomization-test" class="nav-link" data-scroll-target="#testing-the-significance-of-the-linear-relationship-using-a-randomization-test"><span class="header-section-number">14.3</span> Testing the significance of the linear relationship using a randomization test</a></li>
  <li><a href="#sec-remedmeasure" id="toc-sec-remedmeasure" class="nav-link" data-scroll-target="#sec-remedmeasure"><span class="header-section-number">14.4</span> Remedial measures</a></li>
  <li><a href="#sample-size-estimation-and-power-analysis-for-slr" id="toc-sample-size-estimation-and-power-analysis-for-slr" class="nav-link" data-scroll-target="#sample-size-estimation-and-power-analysis-for-slr"><span class="header-section-number">14.5</span> Sample size estimation and power analysis for SLR</a></li>
  </ul><div class="toc-actions"><ul><li><a href="https://github.com/emontoya2/edit/master/lr.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./anovalin.html">Module: ANOVA, linear regression, and logistic regression</a></li><li class="breadcrumb-item"><a href="./lr.html"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Simple linear regression</span></a></li></ol></nav><div class="quarto-title">
<h1 class="title"><span id="sec-regression" class="quarto-section-identifier"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Simple linear regression</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header><div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="images/linmod/regpic.jpg" class="img-fluid figure-img" style="width:50.0%"></p>
<figcaption>AI art generated by keywords “linear regression”</figcaption></figure>
</div>
<p><a href="numsum.html#sec-multinumvar" class="quarto-xref"><span>Section 10.2</span></a> addresses how to investigate the relationship between two numerical variables by looking at a scatterplot. Simple linear regression (SLR) is a statistical method used to model the linear relationship between two numerical variables, where one variable is the response variable and the other is the explanatory variable. SLR is a special case of linear regression, which models the relationship between two or more variables by fitting a linear equation to the observed data. This section focuses on SLR, which involves only one explanatory variable.</p>
<div class="cell quarto-layout-panel" data-layout-ncol="1" data-layout-align="center">
<div class="quarto-layout-row">
<div class="cell-output-display quarto-layout-cell" style="flex-basis: 100.0%;justify-content: center;">
<div id="fig-lrex" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-lrex-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="lr_files/figure-html/fig-lrex-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-lrex-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;14.1: Example of a linear relationship with the estimated or best fit SLR line with the predicted values shown as black points on the line
</figcaption></figure>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Notation
</div>
</div>
<div class="callout-body-container callout-body">
<p>We start with some required notation and definitions: Let <span class="math inline">\(y\)</span> denote the response variable and <span class="math inline">\(x\)</span> denote the explanatory variable. The SLR model is of the form:</p>
<p><span class="math display">\[y = \beta_0 + \beta_1 x + \varepsilon\]</span></p>
<p>where:</p>
<ul>
<li><p><span class="math inline">\(\beta_0\)</span> is the true intercept, the conditional mean of <span class="math inline">\(y\)</span> when <span class="math inline">\(x=0\)</span>. Individual responses can differ from this mean.</p></li>
<li><p><span class="math inline">\(\beta_1\)</span> is the true slope, which represents the average change in <span class="math inline">\(y\)</span> for a unit increase in <span class="math inline">\(x\)</span>.</p></li>
<li><p><span class="math inline">\(\varepsilon\)</span> is the random error term, which represents the random variability about the line in the relationship between <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span> that is not accounted for by the linear regression model.</p></li>
</ul>
</div>
</div>
<p>The SLR model assumes that the value of <span class="math inline">\(y\)</span> is linearly related to <span class="math inline">\(x\)</span> via the line <span class="math inline">\(\beta_0 + \beta_1 x\)</span>. However, the observed <span class="math inline">\(y\)</span> values deviate randomly from this line, as quantified by an error term. On average, the value of <span class="math inline">\(y\)</span> for a given value of <span class="math inline">\(x\)</span> is <span class="math inline">\(\beta_0 + \beta_1 x\)</span>. The random error term signifies that other factors, such as measurement errors, unmeasured variables, or inherent variability in the data, may influence the response variable and are not captured or explained by the estimated SLR line</p>
<p>Note that the line shown in the above scatterplot is the estimated SLR line denoted by <span class="math inline">\(\hat{y} = b_0 + b_1 x\)</span>.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Notation
</div>
</div>
<div class="callout-body-container callout-body">
<p>Note the following notation regarding the estimated SLR line:</p>
<ul>
<li>
<p><span class="math inline">\(\hat{y}\)</span> is the predicted/fitted value of <span class="math inline">\(y\)</span> for a given value of <span class="math inline">\(x\)</span>.</p>
<ul>
<li>A value of <span class="math inline">\(\hat{y}\)</span> represent the estimated expected/average/mean value of the response (<span class="math inline">\(y\)</span>) at a given value of <span class="math inline">\(x\)</span>.</li>
</ul>
</li>
<li><p><span class="math inline">\(b_0\)</span> is the estimated intercept</p></li>
<li>
<p><span class="math inline">\(b_1\)</span> is the estimated slope.</p>
<ul>
<li>The slope estimate represents the change in <span class="math inline">\(\hat{y}\)</span> corresponding to a 1-unit increase in <span class="math inline">\(x\)</span><a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>.</li>
</ul>
</li>
</ul>
</div>
</div>
<p>Due to the random error in the relationship between the explanatory and response variables, the estimated line may not pass through every data point. The estimates of <span class="math inline">\(b_0\)</span> and <span class="math inline">\(b_1\)</span> are obtained using the method of least squares, which minimizes the sum of squared differences between the observed values of <span class="math inline">\(y\)</span> and predicted values <span class="math inline">\(\hat{y}\)</span>.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Notation
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>
<span class="math inline">\(e\)</span> is the difference between the observed value of the dependent variable (<span class="math inline">\(y\)</span>) and the predicted value (<span class="math inline">\(\hat{y}\)</span>) and it is called a residual.
<ul>
<li>The residuals represent the unexplained variation in the dependent variable that is not accounted for by the estimated SLR line.</li>
</ul>
</li>
</ul>
</div>
</div>
<p>Now that some basic of SLR have been covered, this section illustrates common key aspects of SLR, including:</p>
<ul>
<li><p>Fitting the SLR model to data using R, model diagnostics, and interpreting the fit.</p></li>
<li><p>Performing a t-based test or a randomization test to determine the significance of the linear relationship between the two variables.</p></li>
<li><p>Constructing a t-based confidence interval for the slope of the regression line.</p></li>
<li><p>Applying basic remediation approaches.</p></li>
</ul>
<p>For inferential methods to provide meaningful results, several assumptions are made about the data on which the method is intended to be used.</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Data assumptions
</div>
</div>
<div class="callout-body-container callout-body">
<p>The methods discussed here assume one or more of the following assumptions about the data:</p>
<ul>
<li><p><strong>Assumption 1</strong>. <em>Independence of errors</em>. Errors for different observational units are independent, conditional on the explanatory variable. Repeated measurements or shared conditions can violate this assumption.</p></li>
<li><p><strong>Assumption 2</strong>. <em>No influential outliers</em>. The data should not contain any influential outliers<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a> that significantly affect the estimate SLR line.</p></li>
<li><p><strong>Assumption 3</strong>. <em>Normality for exact small-sample inference</em>. Errors are normally distributed at each predictor value. A QQ-plot of residuals is a diagnostic proxy. Large-sample approximations require suitable regularity conditions and do not resolve dependence or nonconstant variance.</p></li>
<li><p><strong>Assumption 4</strong>. <em>Constant error variance</em>. The spread of responses about their conditional mean is approximately constant across predictor values.</p></li>
<li><p><strong>Assumption 5</strong>. The variables are <em>linearly related</em>, meaning that a straight line can accurately represent the trend in the scatterplot.</p></li>
</ul>
<p>While these assumptions are assessed below with a case study, assumption 1 can be assessed using residual plots along with the study design. Assumption 2 can be examined using a histogram or boxplot of the data or residuals, assumption 3 with normal QQ-plot of the residuals, assumption 4 with a scatterplot of the residuals against the predicted values, and assumption 5 with a scatterplot of the data.</p>
</div>
</div>
<section id="fitting-the-slr-model-and-model-diagnostics." class="level2" data-number="14.1"><h2 data-number="14.1" class="anchored" data-anchor-id="fitting-the-slr-model-and-model-diagnostics.">
<span class="header-section-number">14.1</span> Fitting the SLR model and model diagnostics.</h2>
<p>The function <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code> is used to fit the SLR model to the data.</p>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>R functions
</div>
</div>
<div class="callout-body-container callout-body">
<pre><code>### lm( y ~ x , data )
# y: replace y with the name of the response (measured)
#  variable of interest
# x: replace x with the name of the explantory variable
# data: set equal to a data frame that is in tidy form
#</code></pre>
</div>
</div>
<p>Note that the R functions used in these modules often have identical arguments, which will no longer be described in this module. The <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code> function provides more than just the values of <span class="math inline">\(b_0\)</span> and <span class="math inline">\(b_1\)</span>, and the illustrations below show how to use it to create an <em>lm object</em> that contains useful information. To summarize the SLR model fit, extract fitted values, or extract residuals from the <em>lm object</em>, we use the <code><a href="https://rdrr.io/r/base/summary.html">summary()</a></code>, <code><a href="https://rdrr.io/r/stats/predict.html">predict()</a></code>, and <code><a href="https://rdrr.io/r/stats/residuals.html">residuals()</a></code> functions on the <em>lm object</em>, respectively. The function <code><a href="https://rdrr.io/pkg/lattice/man/xyplot.html">xyplot()</a></code> can be used to plot the data along with the estimated SLR line by specifying an argument called <code>type</code>:</p>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>R functions
</div>
</div>
<div class="callout-body-container callout-body">
<pre><code>### summary( lm object )
# lm object: An object saving the result of usuing 
#      the lm function.
#
### predict( lm object )
#
### residuals( lm object )
#
### xyplot( y ~ x, data, type=c("p", "r") )
#</code></pre>
</div>
</div>
<p>The <code><a href="https://rdrr.io/r/base/summary.html">summary()</a></code> function will provide a lot of information, including the values of <span class="math inline">\(b_0\)</span> and <span class="math inline">\(b_1\)</span>.</p>
<p>Model diagnostics assess whether the model’s assumptions are reasonable. The <code>tactile</code> package extends <code><a href="https://rdrr.io/pkg/lattice/man/xyplot.html">xyplot()</a></code> to display diagnostic plots for an <em>lm object</em>. The plots below address different aspects of fit:</p>
<ul>
<li><p><strong>Residuals vs.&nbsp;predicted values</strong>: Look for curvature in the conditional mean, changing spread, and unusual residuals. Absence of a visible pattern does not establish independence. Dependence should also be assessed using the study design and residuals plotted in time or observation order, where applicable.</p></li>
<li><p><strong>Normal QQ-plot of the residuals</strong>: The plot helps to assess assumption 3. If the residuals are normally distributed, the points on the plot will roughly follow a straight line.</p></li>
<li><p><strong>Scale-location plot</strong>: This plots the square root of the absolute standardized residual against the predicted value. It helps assess whether residual spread changes across fitted values. The plotted square roots are nonnegative and do not have mean zero.</p></li>
<li><p><strong>Residuals vs.&nbsp;leverage plot</strong>: Leverage measures how unusual a predictor value is relative to the other predictor values. Large residuals combined with high leverage can identify influential observations. Cook’s distance summarizes the effect on the fitted coefficients; this plot does not establish independence or constant variance.</p></li>
</ul>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>We fit the SLR model to the data described in the case study provided in <a href="datacs3.html" class="quarto-xref"><span>Chapter 3</span></a> to model the linear relationship between Pm10 and temperature. The data provided in the case study consists of several variables (<code>PM10</code>, <code>AQI</code>, …, <code>county</code>, and <code>City.Name</code>) with <code>PM10</code> and <code>temp</code> being the variables of interest.</p>
<p>To begin, we import the data, and then one would explore the data using numerical and graphical data summaries. Numerical and graphical data exploration for bivariate data are covered in other modules but we start by assessing the linearity of the relationship.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist">
<li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-1-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-1" role="tab" aria-controls="tabset-1-1" aria-selected="true" href="" aria-current="page">R code</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-2" role="tab" aria-controls="tabset-1-2" aria-selected="false" href="">Video</a></li>
</ul>
<div class="tab-content">
<div id="tabset-1-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-1-1-tab">
<div class="cell" data-layout-align="center">
<details open="" class="code-fold"><summary>Code</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb3"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Import data </span></span>
<span><span class="va">PM10df</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/utils/read.table.html">read.csv</a></span><span class="op">(</span><span class="st">"datasets/DailyPM10.2021.csv"</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># obtain the names of the variables</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span> <span class="va">PM10df</span> <span class="op">)</span></span>
<span><span class="co">#&gt; [1] "PM10"      "AQI"       "temp"      "Latitude"  "Longitude" "windspeed"</span></span>
<span><span class="co">#&gt; [7] "state"     "county"    "City.Name"</span></span>
<span></span>
<span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://lattice.r-forge.r-project.org/">lattice</a></span><span class="op">)</span> <span class="co"># provides the xyplot() function</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/lattice/man/xyplot.html">xyplot</a></span><span class="op">(</span> <span class="va">PM10</span> <span class="op">~</span> <span class="va">temp</span> , </span>
<span>    data<span class="op">=</span> <span class="va">PM10df</span> , </span>
<span>    xlab<span class="op">=</span> <span class="st">"Temperature"</span> , </span>
<span>    ylab<span class="op">=</span> <span class="st">"Particulate matter 10 micrometers or less (PM10)"</span> ,</span>
<span>    main<span class="op">=</span> <span class="st">"PM10 vs Temperature"</span> ,</span>
<span>    col<span class="op">=</span><span class="st">"black"</span> <span class="op">)</span> <span class="co"># default color is "blue")</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details><div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="lr_files/figure-html/unnamed-chunk-1-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</div>
<div id="tabset-1-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-2-tab">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="vembedr">
<div>
<iframe src="https://www.youtube.com/embed/d1LI4eSXKGU" width="533" height="300" frameborder="0" allowfullscreen="" data-external="1"></iframe>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
<p>The scatterplot reflect a positive linear trend with some outlying PM10 measurements. To address the presence of outliers when conducting inference, we will consider some approaches in the last section. For now, we will proceed with fitting the SLR model in R for the purpose of illustration. This will involve using the <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code> to fit the model and <code><a href="https://rdrr.io/pkg/lattice/man/xyplot.html">xyplot()</a></code> to show the estimated SLR line:</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist">
<li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-2-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-1" role="tab" aria-controls="tabset-2-1" aria-selected="true" href="">R code</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-2-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-2" role="tab" aria-controls="tabset-2-2" aria-selected="false" href="">Video</a></li>
</ul>
<div class="tab-content">
<div id="tabset-2-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-2-1-tab">
<div class="cell" data-layout-align="center">
<details open="" class="code-fold"><summary>Code</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb4"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># The function will require the following information:</span></span>
<span><span class="co"># y: replace with 'PM10'</span></span>
<span><span class="co"># x: replace with 'temp'</span></span>
<span><span class="co"># data: set equal to a 'PM10df'</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span> <span class="va">PM10</span> <span class="op">~</span> <span class="va">temp</span>,</span>
<span>  data<span class="op">=</span> <span class="va">PM10df</span> <span class="op">)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Call:</span></span>
<span><span class="co">#&gt; lm(formula = PM10 ~ temp, data = PM10df)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Coefficients:</span></span>
<span><span class="co">#&gt; (Intercept)         temp  </span></span>
<span><span class="co">#&gt;    -12.7702       0.8053</span></span>
<span></span>
<span><span class="co"># xyplot now includes a new argument called type. </span></span>
<span><span class="co"># Set type=c("p", "r"). This tells xyplot() to plot both the </span></span>
<span><span class="co"># points and the estimated line. A few additional</span></span>
<span><span class="co"># aesthetic arguments are provided below as well. </span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/lattice/man/xyplot.html">xyplot</a></span><span class="op">(</span> <span class="va">PM10</span> <span class="op">~</span> <span class="va">temp</span>,</span>
<span>  data<span class="op">=</span> <span class="va">PM10df</span>,</span>
<span>  type<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"p"</span>, <span class="st">"r"</span><span class="op">)</span>, <span class="co"># ensures both data points and est. reg. line is plotted</span></span>
<span>  col.line <span class="op">=</span> <span class="st">"red"</span>, <span class="co"># make the line red </span></span>
<span>  lwd<span class="op">=</span> <span class="fl">2</span> <span class="op">)</span> <span class="co"># make the line wider</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details><div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="lr_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</div>
<div id="tabset-2-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-2-2-tab">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="vembedr">
<div>
<iframe src="https://www.youtube.com/embed/oLqPQjRUKhg" width="533" height="300" frameborder="0" allowfullscreen="" data-external="1"></iframe>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
<p>The output provides <span class="math inline">\(b_0=-12.77\)</span> and <span class="math inline">\(b_1=0.8053\)</span>. With <span class="math inline">\(b_1=0.8053\)</span>, it is estimated that PM10 levels (the response), on average, changes by <span class="math inline">\(.8053\)</span> when temperature (the explanatory) is increased by 1 degree. The <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code> function provides much more than just these values. To extract other information, the result from <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code> must be stored. Below the resulting <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code> fit is stored and then the <code><a href="https://rdrr.io/r/base/summary.html">summary()</a></code> is applied to this object. The functions <code><a href="https://rdrr.io/r/stats/residuals.html">residuals()</a></code> and <code><a href="https://rdrr.io/r/stats/predict.html">predict()</a></code> are also illustrated below.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist">
<li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-3-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-1" role="tab" aria-controls="tabset-3-1" aria-selected="true" href="">R code</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-3-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-2" role="tab" aria-controls="tabset-3-2" aria-selected="false" href="">Video</a></li>
</ul>
<div class="tab-content">
<div id="tabset-3-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-3-1-tab">
<div class="cell" data-layout-align="center">
<details open="" class="code-fold"><summary>Code</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb5"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Store lm() fit in an object, call it PM10fit</span></span>
<span><span class="va">PM10fit</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span> <span class="va">PM10</span> <span class="op">~</span> <span class="va">temp</span>,</span>
<span>         data<span class="op">=</span> <span class="va">PM10df</span> <span class="op">)</span></span>
<span></span>
<span><span class="co"># PM10fit is called an lm object</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span> <span class="va">PM10fit</span> <span class="op">)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Call:</span></span>
<span><span class="co">#&gt; lm(formula = PM10 ~ temp, data = PM10df)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Residuals:</span></span>
<span><span class="co">#&gt;    Min     1Q Median     3Q    Max </span></span>
<span><span class="co">#&gt; -47.88 -16.94  -7.25   8.58 401.17 </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Coefficients:</span></span>
<span><span class="co">#&gt;              Estimate Std. Error t value Pr(&gt;|t|)    </span></span>
<span><span class="co">#&gt; (Intercept) -12.77025    2.67450  -4.775 1.89e-06 ***</span></span>
<span><span class="co">#&gt; temp          0.80532    0.03899  20.655  &lt; 2e-16 ***</span></span>
<span><span class="co">#&gt; ---</span></span>
<span><span class="co">#&gt; Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Residual standard error: 30.77 on 2722 degrees of freedom</span></span>
<span><span class="co">#&gt;   (391 observations deleted due to missingness)</span></span>
<span><span class="co">#&gt; Multiple R-squared:  0.1355, Adjusted R-squared:  0.1352 </span></span>
<span><span class="co">#&gt; F-statistic: 426.6 on 1 and 2722 DF,  p-value: &lt; 2.2e-16</span></span>
<span></span>
<span><span class="co"># extract the residuals from PMfit</span></span>
<span><span class="co"># and store in an object called PM10res</span></span>
<span><span class="va">PM10res</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/residuals.html">residuals</a></span><span class="op">(</span> <span class="va">PM10fit</span> <span class="op">)</span></span>
<span></span>
<span><span class="co"># extract the predicted values from PMfit</span></span>
<span><span class="co"># and store in an object called PM10predict</span></span>
<span><span class="va">PM10predict</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span> <span class="va">PM10fit</span> <span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</div>
<div id="tabset-3-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-3-2-tab">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="vembedr">
<div>
<iframe src="https://www.youtube.com/embed/QnGjWGY5znE" width="533" height="300" frameborder="0" allowfullscreen="" data-external="1"></iframe>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
<p>Note that the <code><a href="https://rdrr.io/r/base/summary.html">summary()</a></code> provides the following table:</p>
<table class="caption-top table">
<thead><tr class="header">
<th></th>
<th>Estimate</th>
<th>Std. Error</th>
<th>t-value</th>
<th>p-value</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>(Intercept)</td>
<td><span class="math inline">\(b_0\)</span></td>
<td><span class="math inline">\(SE_{b_0}\)</span></td>
<td><span class="math inline">\(T_{b_0}\)</span></td>
<td>p-value<span class="math inline">\(_{b_0}\)</span>
</td>
</tr>
<tr class="even">
<td>explanatory</td>
<td><span class="math inline">\(b_1\)</span></td>
<td><span class="math inline">\(SE_{b_1}\)</span></td>
<td><span class="math inline">\(T_{b_1}\)</span></td>
<td>p-value<span class="math inline">\(_{b_1}\)</span>
</td>
</tr>
</tbody>
</table>
<p>The terms <span class="math inline">\(SE_{b_0}\)</span> and <span class="math inline">\(SE_{b_1}\)</span> are the standard errors for <span class="math inline">\(b_0\)</span> and <span class="math inline">\(b_1\)</span>. The table also provides the coefficient of determination or <span class="math inline">\(R^2\)</span> (<code>Multiple R-squared: 0.1355</code>). The value of <span class="math inline">\(R^2\)</span> is the sample correlation, <span class="math inline">\(r\)</span>, squared. In terms of its interpretation, <span class="math inline">\(R^2\)</span>, measures how well the estimated SLR line fits the data. A higher value of <span class="math inline">\(R^2\)</span> indicates a better fit, meaning that more of the variance in the response variable can be explained by the explanatory variable. However, a high or low value of does not necessarily imply a significant linear relationship. Here, temperature explains <span class="math inline">\(13.55\)</span>% of the total variation observed in PM10 measurements. In other words, the SLR model accounts for only a small fraction of the variability in PM10 measurements, and there may be other variables that are not included in the model that also affect PM10 levels. The rest of the information provided by <code><a href="https://rdrr.io/r/base/summary.html">summary()</a></code> will be addressed as needed throughout the rest of these sections.</p>
<p>The next sections cover different inferential methods for a SLR, and they require for the assumptions of the data to be reasonable. Next, we perform model diagnostics to assess the model assumptions with the help of <code><a href="https://rdrr.io/pkg/lattice/man/xyplot.html">xyplot()</a></code> after loading the <code>tactile</code> R package:</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist">
<li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-4-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-4-1" role="tab" aria-controls="tabset-4-1" aria-selected="true" href="">R code</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-4-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-4-2" role="tab" aria-controls="tabset-4-2" aria-selected="false" href="">Video</a></li>
</ul>
<div class="tab-content">
<div id="tabset-4-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-4-1-tab">
<details open="" class="code-fold"><summary>Code</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb6"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span></span>
<span><span class="co"># This package provides diagnostic </span></span>
<span><span class="co"># plots using xyplot()</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span> <span class="va"><a href="https://github.com/jolars/tactile">tactile</a></span> <span class="op">)</span> </span>
<span></span>
<span><span class="co"># To create a set of pre-specified </span></span>
<span><span class="co"># residual plots, provide the lm object</span></span>
<span><span class="co"># to xyplot()</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/lattice/man/xyplot.html">xyplot</a></span><span class="op">(</span> <span class="va">PM10fit</span> <span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details><div class="cell quarto-layout-panel" data-layout-ncol="1" data-layout-align="center">
<div class="quarto-layout-row">
<div class="cell-output-display quarto-layout-cell" style="flex-basis: 100.0%;justify-content: center;">
<div id="fig-usingtactile" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-usingtactile-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="lr_files/figure-html/fig-usingtactile-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-usingtactile-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;14.2: Diagnostic plots
</figcaption></figure>
</div>
</div>
</div>
</div>
</div>
<div id="tabset-4-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-4-2-tab">
<p>See previous video.</p>
</div>
</div>
</div>
<p>The scatterplot showed a linear trend in the data, so assumption 5 (linearity) is reasonable. The residual plots provided by <code><a href="https://rdrr.io/pkg/lattice/man/xyplot.html">xyplot()</a></code> (excluding the normal QQ-plot) will have a black (not necessarily linear) trend line that is lowess smoother<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a>. Each plot is analyzed and interpreted below:</p>
<ul>
<li>
<p>The upper and lower left plots display the residuals against the predicted value and the square roots of absolute standardized residuals against the predicted values, respectively. The plot shows the following characteristics:</p>
<ul>
<li>Neither plot shows an obvious mean trend, but these plots alone do not establish independence of the daily measurements.</li>
<li>There are a few potential outliers and the variability of the residuals is not constant across the predicted values, so assumptions 2 and 4 are questionable.</li>
</ul>
</li>
<li><p>The upper-right normal QQ-plot<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a> suggests departures from normality. A large sample may support an approximation under additional conditions, but it does not resolve temporal dependence or nonconstant error variance.</p></li>
<li><p>The lower-right plot compares standardized residuals with leverage. Cook’s distance<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a> contours, if shown, help identify observations that affect the coefficients. Leverage and Cook’s distance measure different quantities. A visual threshold alone should not be used to declare the model valid.</p></li>
</ul>
<p>Overall, not all data assumptions are met for the SLR model. In such cases, we say the model did not pass the model diagnostics. Possible remedial measures will be discussed in the last section. For now, we will proceed with this model for the purpose of illustrating inferential methods, as if it were appropriate for the data.</p>
</div>
</div>
</section><section id="testing-the-significance-of-the-linear-relationship-using-t-based-methods." class="level2" data-number="14.2"><h2 data-number="14.2" class="anchored" data-anchor-id="testing-the-significance-of-the-linear-relationship-using-t-based-methods.">
<span class="header-section-number">14.2</span> Testing the significance of the linear relationship using t-based methods.</h2>
<p>The focus in this section is on inference for <span class="math inline">\(\beta_1\)</span> (the true slope), where <span class="math inline">\(\beta_1\)</span> represents the change in the average value of <span class="math inline">\(y\)</span> when <span class="math inline">\(x\)</span> is increased by 1-unit. The t-test for the slope of a regression line is a widely used hypothesis test to assess the significance of a linear relationship between two variables. Specifically, the test is used to determine if the true slope <span class="math inline">\(\beta_1\)</span> is significantly different from zero, based on the observed value of <span class="math inline">\(b_1\)</span>. It is important to note that the observed value of <span class="math inline">\(b_1\)</span> can vary. If a study were replicated, the value of <span class="math inline">\(b_1\)</span> would likely be different. The use of inferential methods allows us to account for this variability and make statistically valid conclusions about the true slope <span class="math inline">\(\beta_1\)</span>. A t-based confidence interval can be constructed for <span class="math inline">\(\beta_1\)</span> and it provides a range of plausible values for the true slope at a specified significance level. These methods are generally referred to as t-based methods for the slope.</p>
<p>The t-test for the slope of a regression line requires that certain assumptions (1, 2, 3, 4, and 5<a href="#fn6" class="footnote-ref" id="fnref6" role="doc-noteref"><sup>6</sup></a>) about the data are reasonable. The test statistic for this t-test is given by:</p>
<p><span class="math display">\[T=\frac{b_1-\beta_1}{SE_{b_1}} \]</span></p>
<p>Here, <span class="math inline">\(SE_{b_1}\)</span> represents the standard error of <span class="math inline">\(b_1\)</span><a href="#fn7" class="footnote-ref" id="fnref7" role="doc-noteref"><sup>7</sup></a>. Our primary interest is in determining if there is a significant linear relationship (association) between the explanatory variable and response variable, which translate to <span class="math inline">\(\beta_1\neq 0\)</span>. Consequently, the null and alternative hypotheses are:</p>
<p><span class="math display">\[H_0: \beta_1=0 \qquad H_a: \beta_1 \neq 0\]</span></p>
<p>Note that when two variables are linearly related or associated, it means that they are correlated, and when two variables are correlated and linearly related, it implies that they have a linear relationship or association. Under <span class="math inline">\(H_0\)</span>, the null distribution of the test statistic <span class="math inline">\(T\)</span> follows a t-distribution with <span class="math inline">\(n-2\)</span> degrees of freedom, where <span class="math inline">\(n\)</span> is the sample size. This distribution is used to compute the p-value. The function <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code> computes the test statistic and p-value for the t-test for a linear association in a SLR, and the results are provided by the <code><a href="https://rdrr.io/r/base/summary.html">summary()</a></code> output. Recall that the <code><a href="https://rdrr.io/r/base/summary.html">summary()</a></code> function provides a table with relevant information, including the test statistic and p-value for the t-test, as well as other statistics like the coefficient estimates and standard errors:</p>
<table class="caption-top table">
<thead><tr class="header">
<th></th>
<th>Estimate</th>
<th>Std. Error</th>
<th>t-value</th>
<th>p-value</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>(Intercept)</td>
<td><span class="math inline">\(b_0\)</span></td>
<td><span class="math inline">\(SE_{b_0}\)</span></td>
<td><span class="math inline">\(T_{b_0}\)</span></td>
<td>p-value<span class="math inline">\(_{b_0}\)</span>
</td>
</tr>
<tr class="even">
<td>explanatory</td>
<td><span class="math inline">\(b_1\)</span></td>
<td><span class="math inline">\(SE_{b_1}\)</span></td>
<td><span class="math inline">\(T_{b_1}\)</span></td>
<td>p-value<span class="math inline">\(_{b_1}\)</span>
</td>
</tr>
</tbody>
</table>
<p>Here, <span class="math inline">\(T_{b_1}\)</span> and p-value<span class="math inline">\(_{b_1}\)</span> refer to the test statistic for the slope and two-sided p-value<span class="math inline">\(_{b_1}\)</span>, respectively for testing if <span class="math inline">\(\beta_1\neq 0\)</span>. The function <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code> can also be utilized to obtain a confidence interval (CI) for the true slope <span class="math inline">\(\beta_1\)</span>. To obtain a CI, apply the <code><a href="https://rdrr.io/r/stats/confint.html">confint()</a></code> function to the resulting <em>lm object</em>.</p>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>R functions
</div>
</div>
<div class="callout-body-container callout-body">
<pre><code>### confint( lm object , parm , level)
# lm object: An object saving the result of usuing 
#      the lm function.
# parm: Set equal to 2 
# level: Set to desired confidence level.
#</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>We apply a t-test to the data described in the case study from <a href="datacs3.html" class="quarto-xref"><span>Chapter 3</span></a> to determine if there is a significant linear association between PM10 and temperature levels at <span class="math inline">\(\alpha=.05\)</span>. Recall that not all the required assumptions are met, but we perform the test for the purpose of illustration. Let <span class="math inline">\(\beta_1\)</span> denote the true slope in the linear association between PM10 and temperature. Since the aim is to determine if there is a significant linear relationship or association, the hypothesis is</p>
<p><span class="math display">\[H_0: \beta_1=0 \qquad H_a: \beta_1 \neq 0\]</span></p>
<p>The following code uses <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code> and <code><a href="https://rdrr.io/r/base/summary.html">summary()</a></code> to compute the test statistic and the corresponding p-value for a t-test:</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist">
<li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-5-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-5-1" role="tab" aria-controls="tabset-5-1" aria-selected="true" href="">R code</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-5-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-5-2" role="tab" aria-controls="tabset-5-2" aria-selected="false" href="">Video</a></li>
</ul>
<div class="tab-content">
<div id="tabset-5-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-5-1-tab">
<div class="cell" data-layout-align="center">
<details open="" class="code-fold"><summary>Code</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb8"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># PM10fit was created in the previous section</span></span>
<span><span class="co"># but the code is given here as reminder. </span></span>
<span><span class="co"># Below, the result from lm() is </span></span>
<span><span class="co"># stored in an object, called PM10fit</span></span>
<span><span class="va">PM10fit</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span> <span class="va">PM10</span> <span class="op">~</span> <span class="va">temp</span>,</span>
<span>         data<span class="op">=</span> <span class="va">PM10df</span> <span class="op">)</span></span>
<span></span>
<span><span class="co"># summarize the lm object, PM10fit. </span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span> <span class="va">PM10fit</span> <span class="op">)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Call:</span></span>
<span><span class="co">#&gt; lm(formula = PM10 ~ temp, data = PM10df)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Residuals:</span></span>
<span><span class="co">#&gt;    Min     1Q Median     3Q    Max </span></span>
<span><span class="co">#&gt; -47.88 -16.94  -7.25   8.58 401.17 </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Coefficients:</span></span>
<span><span class="co">#&gt;              Estimate Std. Error t value Pr(&gt;|t|)    </span></span>
<span><span class="co">#&gt; (Intercept) -12.77025    2.67450  -4.775 1.89e-06 ***</span></span>
<span><span class="co">#&gt; temp          0.80532    0.03899  20.655  &lt; 2e-16 ***</span></span>
<span><span class="co">#&gt; ---</span></span>
<span><span class="co">#&gt; Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Residual standard error: 30.77 on 2722 degrees of freedom</span></span>
<span><span class="co">#&gt;   (391 observations deleted due to missingness)</span></span>
<span><span class="co">#&gt; Multiple R-squared:  0.1355, Adjusted R-squared:  0.1352 </span></span>
<span><span class="co">#&gt; F-statistic: 426.6 on 1 and 2722 DF,  p-value: &lt; 2.2e-16</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</div>
<div id="tabset-5-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-5-2-tab">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="vembedr">
<div>
<iframe src="https://www.youtube.com/embed/9CG0vvg016k" width="533" height="300" frameborder="0" allowfullscreen="" data-external="1"></iframe>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
<p>The nominal slope statistic is <span class="math inline">\(T=20.655\)</span> with a very small p-value under the independent, constant-variance error model. At <span class="math inline">\(\alpha=.05\)</span>, that model-based test rejects a zero slope. The fitted association is positive, but the earlier diagnostics and repeated daily sampling raise concerns about the standard errors. Treat this as an illustration of the procedure, not as a validated causal or population-wide conclusion.</p>
<p>The function <code><a href="https://rdrr.io/r/stats/confint.html">confint()</a></code> is used to obtain a 95% CI for <span class="math inline">\(\beta_1\)</span>:</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist">
<li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-6-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-6-1" role="tab" aria-controls="tabset-6-1" aria-selected="true" href="">R code</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-6-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-6-2" role="tab" aria-controls="tabset-6-2" aria-selected="false" href="">Video</a></li>
</ul>
<div class="tab-content">
<div id="tabset-6-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-6-1-tab">
<div class="cell" data-layout-align="center">
<details open="" class="code-fold"><summary>Code</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb9"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span> </span>
<span><span class="co"># summarize the lm object, PM10fit. </span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/confint.html">confint</a></span><span class="op">(</span> <span class="va">PM10fit</span> ,</span>
<span>     parm<span class="op">=</span> <span class="fl">2</span> , <span class="co"># Setting parm =1 will provide CI for beta0</span></span>
<span>     level<span class="op">=</span> <span class="fl">.95</span> <span class="op">)</span></span>
<span><span class="co">#&gt;          2.5 %    97.5 %</span></span>
<span><span class="co">#&gt; temp 0.7288668 0.8817716</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</div>
<div id="tabset-6-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-6-2-tab">
<p>See previous video.</p>
</div>
</div>
</div>
<p>Under the same model, the nominal 95% interval for <span class="math inline">\(\beta_1\)</span> is approximately (0.729, 0.882) <span class="math inline">\(\mu g/m^3\)</span> per <span class="math inline">\(^\circ F\)</span>. It estimates the change in mean PM10 associated with a one-degree increase in temperature. Its coverage depends on the model assumptions, including the error variance and dependence structure.</p>
<p>The interval describes the fitted association at the represented monitoring sites. It does not establish a causal temperature effect or justify generalization beyond the measured sites and conditions.</p>
</div>
</div>
</section><section id="testing-the-significance-of-the-linear-relationship-using-a-randomization-test" class="level2" data-number="14.3"><h2 data-number="14.3" class="anchored" data-anchor-id="testing-the-significance-of-the-linear-relationship-using-a-randomization-test">
<span class="header-section-number">14.3</span> Testing the significance of the linear relationship using a randomization test</h2>
<p>A randomization or permutation test compares an observed slope statistic with values obtained by reallocating responses under a justified null model. Under a sharp no-treatment-effect null in a randomized experiment, the allocation must follow the actual treatment assignment. In an observational regression, unrestricted shuffling requires that responses be exchangeable with respect to predictor values under the null. A zero slope alone does not imply exchangeability: nonlinear dependence or changing variance can remain.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist">
<li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-7-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-7-1" role="tab" aria-controls="tabset-7-1" aria-selected="true" href="">R code</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-7-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-7-2" role="tab" aria-controls="tabset-7-2" aria-selected="false" href="">Video</a></li>
</ul>
<div class="tab-content">
<div id="tabset-7-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-7-1-tab">
<div class="cell quarto-layout-panel" data-layout-ncol="1" data-layout-align="center">
<div class="quarto-layout-row">
<div class="cell-output-display quarto-layout-cell" style="flex-basis: 100.0%;justify-content: center;">
<div id="fig-randlrex" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-randlrex-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="lr_files/figure-html/fig-randlrex-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-randlrex-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;14.3: Example of a linear relationship with the estimated or best fit SLR line. The red circle denote the third observation in the data.
</figcaption></figure>
</div>
</div>
</div>
</div>
</div>
<div id="tabset-7-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-7-2-tab">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="vembedr">
<div>
<iframe src="https://www.youtube.com/embed/QnGjWGY5znE" width="533" height="300" frameborder="0" allowfullscreen="" data-external="1"></iframe>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
<p>When responses are exchangeable under the null, permuting their pairings with the predictor provides a reference distribution. This condition must be justified from the design and model; lack of a linear trend is not sufficient.</p>
<p>The aim is still to see if there is a significant linear relationship or association:</p>
<p><span class="math display">\[H_0: \beta_1=0 \qquad H_a: \beta_1 \neq 0\]</span></p>
<p>For illustration, the code below permutes the observed responses while holding predictor values fixed. This targets an exchangeable-response null. If observations are temporally correlated, clustered, or have predictor-dependent error variances, unrestricted permutations need not produce a valid test.</p>
<p>The figure illustrates one such permutation. A valid reference distribution is formed by repeating permutations allowed by the null model and recomputing the statistic.</p>
<div class="cell quarto-layout-panel" data-layout-ncol="1" data-layout-align="center">
<div class="quarto-layout-row">
<div class="cell-output-display quarto-layout-cell" style="flex-basis: 100.0%;justify-content: center;">
<div id="fig-randlrexshuff" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-randlrexshuff-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="lr_files/figure-html/fig-randlrexshuff-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-randlrexshuff-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;14.4: The resulting scatterplot after permuting the observed response values without replacement
</figcaption></figure>
</div>
</div>
</div>
</div>
<p>Permutation methods can be useful when a normal-error model is unsuitable, but they do not automatically repair nonconstant variance or dependence. Use a method justified for the specific design and null. Here the statistic is the usual slope t-statistic:</p>
<p><span class="math display">\[T=\frac{b_1-\beta_1}{SE_{b_1}} \]</span> To obtain the null distribution of <span class="math inline">\(T\)</span>, the randomization process is repeated many times, each time computing the value of <span class="math inline">\(T\)</span>. We then obtain the null distribution of <span class="math inline">\(T\)</span> by randomly shuffling (randomization) the observed values of the response variable many times, each time computing the value of the test statistic for the randomized data. The R function <code>slr.randtest()</code> computes the test statistic and p-value for the randomization test.</p>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>R functions
</div>
</div>
<div class="callout-body-container callout-body">
<pre><code>### slr.randtest( y ~ x, data, nshuffles, direction )
# nshuffles: Set equal to the desired number of randomizations. 
# x: replace x with the name of the explantory variable
# direction: the sign in the alternative, "two.sided", "greater" , or "less"
#</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>We demonstrate the calculation on the PM10 and temperature records at <span class="math inline">\(\alpha=.05\)</span>. The unrestricted permutations shown here are a computational illustration: repeated measurements, shared weather, and possible nonconstant variance mean exchangeability has not been established. A substantive analysis should account for those features before interpreting a p-value.</p>
<p><span class="math display">\[H_0: \beta_1=0 \qquad H_a: \beta_1 \neq 0\]</span></p>
<p>The following code uses <code>slr.randtest</code> to compute the test statistic and the corresponding p-value for the randomization test:</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist">
<li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-8-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-8-1" role="tab" aria-controls="tabset-8-1" aria-selected="true" href="">R code</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-8-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-8-2" role="tab" aria-controls="tabset-8-2" aria-selected="false" href="">Video</a></li>
</ul>
<div class="tab-content">
<div id="tabset-8-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-8-1-tab">
<div class="cell" data-layout-align="center">
<details open="" class="code-fold"><summary>Code</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb11"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Source the function so that it's R's memory.</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/source.html">source</a></span><span class="op">(</span><span class="st">"rfuns/slr.randtest.R"</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># The function will require the following information:</span></span>
<span><span class="co"># y: replace with 'PM10'</span></span>
<span><span class="co"># x: replace with 'temp'</span></span>
<span><span class="co"># data: set equal to a 'PM10df'</span></span>
<span><span class="co"># nshuffles: Set to 30000 randomization </span></span>
<span><span class="co"># direction: Set to "two.sided"</span></span>
<span><span class="fu">slr.randtest</span><span class="op">(</span> <span class="va">PM10</span> <span class="op">~</span> <span class="va">temp</span> ,</span>
<span>       data<span class="op">=</span> <span class="va">PM10df</span> , </span>
<span>       nshuffles<span class="op">=</span><span class="fl">30000</span> , </span>
<span>       direction <span class="op">=</span> <span class="st">"two.sided"</span> <span class="op">)</span></span>
<span><span class="co"># Randomization test for a linear association in SLR </span></span>
<span><span class="co">#</span></span>
<span><span class="co">#&gt; data: PM10 ~ temp </span></span>
<span><span class="co">#&gt; Obs. test statistic= 20.65466    </span></span>
<span><span class="co">#&gt; Obs. slope estimate= 0.8053192    </span></span>
<span><span class="co">#&gt; R-squared = 0.135493 </span></span>
<span><span class="co">#&gt; p-value = 0 </span></span>
<span><span class="co">#&gt; </span></span>
<span> </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</div>
<div id="tabset-8-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-8-2-tab">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="vembedr">
<div>
<iframe src="https://www.youtube.com/embed/p0LXHWTX7lI" width="533" height="300" frameborder="0" allowfullscreen="" data-external="1"></iframe>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
<div class="cell quarto-layout-panel" data-layout-ncol="1" data-layout-align="center">

</div>
<p>The observed statistic is approximately 20.655. The permutation output estimates the tail probability under the exchangeable-response null used by this calculation. A small value indicates incompatibility with that null, provided its assumptions hold; the previously noted dependence and variance concerns prevent treating this illustration as a validated inferential conclusion.</p>
</div>
</div>
</section><section id="sec-remedmeasure" class="level2" data-number="14.4"><h2 data-number="14.4" class="anchored" data-anchor-id="sec-remedmeasure">
<span class="header-section-number">14.4</span> Remedial measures</h2>
<p>If the model fails diagnostics, one possible remedial measure is to transform the response variable. This can be particularly helpful if only assumption 4 (equal variance or spread) is not met and/or if the small sampled data are skewed. A transformation is a rescaling of the data. Below are some standard transformations for the response variable that may help the data (on a transformed scale) better meet the assumptions<a href="#fn8" class="footnote-ref" id="fnref8" role="doc-noteref"><sup>8</sup></a>:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 17%">
<col style="width: 18%">
<col style="width: 63%">
</colgroup>
<thead><tr class="header">
<th>Transformation</th>
<th>Formula</th>
<th>Description</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>Square root</td>
<td><span class="math inline">\(y' = \sqrt{y}\)</span></td>
<td>Square root of the response</td>
</tr>
<tr class="even">
<td>Natural log</td>
<td><span class="math inline">\(y' = \ln(y)\)</span></td>
<td>Natural log of the response</td>
</tr>
<tr class="odd">
<td>Square</td>
<td><span class="math inline">\(y' = y^2\)</span></td>
<td>Square of the response</td>
</tr>
<tr class="even">
<td>Inverse</td>
<td><span class="math inline">\(y' = \frac{1}{y}\)</span></td>
<td>Inverse of the response</td>
</tr>
</tbody>
</table>
<p>The function <code><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate()</a></code> from the <code>dplyr</code> package will be used to add transform variables to a data frame.</p>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>R functions
</div>
</div>
<div class="callout-body-container callout-body">
<pre><code>### mutate( data frame ,'new variable' = 'function of variable in data frame', ...)
# data frame: Replace with the name of the data frame
# 'new variable': Replace with the name of the new variable
# 'function of variable in data frame': Replace with a function 
# of a variable pesent in the data frame.
# </code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>The residual plots suggest that spread varies across predicted values, making the constant-variance assumption questionable. We illustrate transforming PM10 using <code><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate()</a></code>; a transformation should be followed by renewed model diagnostics and does not automatically remove dependence.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist">
<li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-9-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-9-1" role="tab" aria-controls="tabset-9-1" aria-selected="true" href="">R code</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-9-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-9-2" role="tab" aria-controls="tabset-9-2" aria-selected="false" href="">Video</a></li>
</ul>
<div class="tab-content">
<div id="tabset-9-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-9-1-tab">
<div class="cell" data-layout-align="center">
<details open="" class="code-fold"><summary>Code</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb13"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Source the function so that it's R's memory.</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://dplyr.tidyverse.org">dplyr</a></span><span class="op">)</span> <span class="co"># provides mutate()</span></span>
<span></span>
<span><span class="co"># Below we create a modified version of the PM10df,</span></span>
<span><span class="co"># called PM10mod, that contains the transformed response</span></span>
<span><span class="va">PM10dfmod</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span> <span class="va">PM10df</span>,</span>
<span>           sqrty <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span> <span class="va">PM10</span> <span class="op">)</span> , <span class="co"># square root transformed</span></span>
<span>           invy <span class="op">=</span> <span class="fl">1</span><span class="op">/</span><span class="va">PM10</span> ,    <span class="co"># inverse transformed</span></span>
<span>           ysq <span class="op">=</span>  <span class="va">PM10</span><span class="op">^</span><span class="fl">2</span> <span class="op">)</span>    <span class="co"># squared transformed</span></span>
<span><span class="co"># natural log and inverse considered due to 0's. </span></span>
<span></span>
<span><span class="co"># The data frame contains the transformed variables</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span> <span class="va">PM10dfmod</span> <span class="op">)</span></span>
<span><span class="co">#&gt;  [1] "PM10"      "AQI"       "temp"      "Latitude"  "Longitude" "windspeed"</span></span>
<span><span class="co">#&gt;  [7] "state"     "county"    "City.Name" "sqrty"     "invy"      "ysq"</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</div>
<div id="tabset-9-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-9-2-tab">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="vembedr">
<div>
<iframe src="https://www.youtube.com/embed/I0UOPc1ykc0" width="533" height="300" frameborder="0" allowfullscreen="" data-external="1"></iframe>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
<p>Now, plot the transformed variables against the explanatory:</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist">
<li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-10-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-10-1" role="tab" aria-controls="tabset-10-1" aria-selected="true" href="">R code</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-10-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-10-2" role="tab" aria-controls="tabset-10-2" aria-selected="false" href="">Video</a></li>
</ul>
<div class="tab-content">
<div id="tabset-10-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-10-1-tab">
<details open="" class="code-fold"><summary>Code</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb14"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/pkg/lattice/man/xyplot.html">xyplot</a></span><span class="op">(</span> <span class="va">PM10</span> <span class="op">~</span> <span class="va">temp</span>, </span>
<span>    data<span class="op">=</span> <span class="va">PM10dfmod</span>, </span>
<span>    xlab<span class="op">=</span> <span class="st">"Temperature"</span>, </span>
<span>    ylab<span class="op">=</span> <span class="st">"Original scale"</span><span class="op">)</span> </span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/lattice/man/xyplot.html">xyplot</a></span><span class="op">(</span> <span class="va">sqrty</span> <span class="op">~</span> <span class="va">temp</span> , </span>
<span>    data<span class="op">=</span> <span class="va">PM10dfmod</span> , </span>
<span>    xlab<span class="op">=</span> <span class="st">"Temperature"</span> , </span>
<span>    ylab<span class="op">=</span> <span class="st">"Square root scale"</span> <span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/lattice/man/xyplot.html">xyplot</a></span><span class="op">(</span> <span class="va">invy</span> <span class="op">~</span> <span class="va">temp</span> , </span>
<span>    data<span class="op">=</span> <span class="va">PM10dfmod</span> , </span>
<span>    xlab<span class="op">=</span> <span class="st">"Temperature"</span> , </span>
<span>    ylab<span class="op">=</span> <span class="st">"Inverse scale"</span> <span class="op">)</span></span>
<span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/lattice/man/xyplot.html">xyplot</a></span><span class="op">(</span> <span class="va">ysq</span> <span class="op">~</span> <span class="va">temp</span> , </span>
<span>    data<span class="op">=</span> <span class="va">PM10dfmod</span> , </span>
<span>    xlab<span class="op">=</span> <span class="st">"Temperature"</span> , </span>
<span>    ylab<span class="op">=</span> <span class="st">"Squared scale"</span> <span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details><div class="cell quarto-layout-panel" data-layout-ncol="2" data-layout-align="center">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="lr_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="lr_files/figure-html/unnamed-chunk-15-2.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="lr_files/figure-html/unnamed-chunk-15-3.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="lr_files/figure-html/unnamed-chunk-15-4.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
<div id="tabset-10-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-10-2-tab">
<p>See previous video.</p>
</div>
</div>
</div>
</div>
</div>
<p>The square root transformation appears to reduce the impact of outliers and make the linear trend more evident. Next, the SLR model would be fitted using <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code> with the formula <code>sqrty ~ temp</code> and <code>data = PM10dfmod argument</code>. After fitting the model, the residuals would be assessed to determine if the transformed data are appropriate for the model.</p>
</section><section id="sample-size-estimation-and-power-analysis-for-slr" class="level2" data-number="14.5"><h2 data-number="14.5" class="anchored" data-anchor-id="sample-size-estimation-and-power-analysis-for-slr">
<span class="header-section-number">14.5</span> Sample size estimation and power analysis for SLR</h2>
<p>Ideally, estimating the sample size for a study is one of the first things that researchers do prior to collecting data. Knowing the sample size required to detect a desired effect at the beginning of a project allows one to manage their data collection efforts. Further, this allows for one to determine how much statistical power the test will have to detect an effect if it exists.</p>
<p>The R function <code><a href="https://rdrr.io/pkg/pwr/man/pwr.f2.test.html">pwr.f2.test()</a></code> from the <code>pwr</code> R package provides statistical power calculations for a SLR model when the sample size, significance level (<span class="math inline">\(\alpha\)</span>), and effect size are provided. It is assumed the appropriate assumptions about the data for the t-test are met.</p>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>R functions
</div>
</div>
<div class="callout-body-container callout-body">
<pre><code>### pwr.f2.test( u, v, f2, sig.level , 
###           power)
# u: Set equal 2.
# v: Set equal to n-2, where n is the 
#   sample size.
# f2: Set equal to the desired effect size
# sig.level: Set equal to the desired alpha value (significance level)
# power: Set equal to the desired power (a number between 0 and 1). 
#</code></pre>
</div>
</div>
<!-- The effect size, `f2`, is a function of $R^2$, $f2=\frac{R^2}{1-R^2}$. For example, if a SLR is sought that we explain 60% of the variation in the response, then -->
<!-- $$f2=.60/.40=1.5$$ -->
<p><span class="math inline">\(f2\)</span> is a called Cohen’s <span class="math inline">\(f2\)</span> and is typically interpreted as follows:</p>
<ul>
<li><p>Small effect size: <span class="math inline">\(f2 = 0.02\)</span></p></li>
<li><p>Medium effect size: <span class="math inline">\(f2 = 0.15\)</span></p></li>
<li><p>Large effect size: <span class="math inline">\(f2 = 0.35\)</span> or higher.</p></li>
</ul>
<p>These are suggested guidelines and may vary slightly depending on the specific field of research or context of the study.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Suppose we want to determine the statistical power to detect a medium-sized effect assuming a sample size of 30 observations at significance level of <span class="math inline">\(\alpha=.001\)</span>.</p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold"><summary>Code</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb16"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/heliosdrm/pwr">pwr</a></span><span class="op">)</span> <span class="co"># provides power.f2.test</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/pwr/man/pwr.f2.test.html">pwr.f2.test</a></span><span class="op">(</span>u <span class="op">=</span> <span class="fl">2</span> , </span>
<span>      v <span class="op">=</span> <span class="fl">28</span> , <span class="co"># 30 - 2 </span></span>
<span>      f2 <span class="op">=</span> <span class="fl">.02</span> , </span>
<span>      sig.level <span class="op">=</span> <span class="fl">.001</span> <span class="op">)</span> </span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;      Multiple regression power calculation </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;               u = 2</span></span>
<span><span class="co">#&gt;               v = 28</span></span>
<span><span class="co">#&gt;              f2 = 0.02</span></span>
<span><span class="co">#&gt;       sig.level = 0.001</span></span>
<span><span class="co">#&gt;           power = 0.003225818</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>The statistical power of this test is rather low, although not surprising given the sample size, <span class="math inline">\(\alpha\)</span> specified, and size of the effect. To increase the power, one may increase the effect size (the larger it is, the easier it is to detect), increase <span class="math inline">\(\alpha\)</span> (make it easier to reject <span class="math inline">\(H_0\)</span> and find a significant effect), and/or increase the number of observations per group.</p>
<p>If instead you sought to collect a sample that would provide a power of <span class="math inline">\(.90\)</span> for detecting a small effect at <span class="math inline">\(\alpha=.001\)</span>, we use the <code>power</code> argument but not specifying <span class="math inline">\(v\)</span>:</p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold"><summary>Code</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb17"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/pkg/pwr/man/pwr.f2.test.html">pwr.f2.test</a></span><span class="op">(</span>u <span class="op">=</span> <span class="fl">2</span> , </span>
<span>      power <span class="op">=</span> <span class="fl">.90</span> ,  </span>
<span>      f2 <span class="op">=</span> <span class="fl">.02</span> , </span>
<span>      sig.level <span class="op">=</span> <span class="fl">.001</span> <span class="op">)</span> </span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;      Multiple regression power calculation </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;               u = 2</span></span>
<span><span class="co">#&gt;               v = 1194.778</span></span>
<span><span class="co">#&gt;              f2 = 0.02</span></span>
<span><span class="co">#&gt;       sig.level = 0.001</span></span>
<span><span class="co">#&gt;           power = 0.9</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>Thus, to ensure a power of at least .90, a sample of size 1195 should be collected.</p>
</div>
</div>


</section><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><hr>
<ol>
<li id="fn1"><p>The estimated intercept is the predicted mean response when <span class="math inline">\(x=0\)</span>. Its practical interpretation depends on whether zero is meaningful and lies within the range relevant to the study.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>An influential observation substantially changes the fitted coefficients when it is omitted. Such an observation is not necessarily an error or evidence of a bad model; examine its validity and its impact on the conclusions.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>A lowess smoother is a method used to smooth out noisy data by fitting a curve to the data points based on a local neighborhood around each point, where closer points have a higher influence on the resulting curve. It helps to identify trends and patterns in the data that might not be immediately visible.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>QQ-plots are discussed in the Basic Exploratory Data Analysis module.<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p>Cook’s distance is a measure of both the leverage and influence of a data point on the regression coefficients. This measure is often used to identify potentially influential observations (typically those with a Cook’s distance exceeding 1). Note that Cook’s distance is just one tool (of many others) for identifying influential observations.<a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn6"><p>Readers may have heard of a correlation test, which is equivalent to a t-test for the slope in SLR, but a correlation test requires the normality assumption even for large samples.<a href="#fnref6" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn7"><p>The standard error of the slope estimate quantifies how much <span class="math inline">\(b_1\)</span> will vary across different samples if the study were replicated many times. A smaller standard error means that the estimate is more precise and varies less across different samples, while a larger standard error means the opposite.<a href="#fnref7" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn8"><p>The explanatory variable may also be transformed to address issues with the model’s assumptions or to better capture the relationship between variables. However, for brevity, we will only focus on transforming the response variable.<a href="#fnref8" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol></section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/emontoya2\.github\.io\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./anova.html" class="pagination-link" aria-label="Analysis of variance (ANOVA)">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Analysis of variance (ANOVA)</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./logisticreg.html" class="pagination-link" aria-label="Simple logistic regression">
        <span class="nav-page-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Simple logistic regression</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/emontoya2/edit/master/lr.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li></ul></div></div></div></footer></body></html>