<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>12&nbsp; Two sample methods – Training modules on selected statistical methods</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./anovalin.html" rel="next">
<link href="./siframework.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark-0a6b7249c26820e032cb0bd839ff02b1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-4b058e8f47af081303ddb0b93c0d0d5f.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="dark"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><link href="site_libs/vembedr-0.1.5/css/vembedr.css" rel="stylesheet">
<script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script><script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>
</head>
<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./twosample.html">Module: Two sample methods</a></li><li class="breadcrumb-item"><a href="./twoindptmeans.html"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Two sample methods</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Training modules on selected statistical methods</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/emontoya2" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
    <div class="dropdown">
      <a href="" title="Share" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" role="link" aria-label="Share"><i class="bi bi-share"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-0">
<li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://twitter.com/intent/tweet?url=|url|">
              <i class="bi bi-twitter pe-1"></i>
            Twitter
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://www.facebook.com/sharer/sharer.php?u=|url|">
              <i class="bi bi-facebook pe-1"></i>
            Facebook
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://www.linkedin.com/sharing/share-offsite/?url=|url|">
              <i class="bi bi-linkedin pe-1"></i>
            LinkedIn
            </a>
          </li>
      </ul>
</div>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./casestudies.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module: Case Studies</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./datacs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Case study 1</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./datacs2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Case study 2</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./datacs3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Case study 3</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./datacs4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Case study 4</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./datacs5.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Case study 5</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./datacs6.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Case study 6</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module: Data basics and drawing statistical conclusions</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Basics of data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./drawingconclusions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Drawing statistical conclusions</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./summaries.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module:  Basic Exploratory  Data Analysis</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./catsum.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Summarizing categorical data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./numsum.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Summarizing numerical data</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./twosample.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module: Two sample methods</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./siframework.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Statistical inference framework via a case study</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./twoindptmeans.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Two sample methods</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./anovalin.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module: ANOVA, linear regression, and logistic regression</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./anova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Analysis of variance (ANOVA)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./lr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Simple linear regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./logisticreg.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Simple logistic regression</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./eda.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module: Advanced Exploratory Data Analysis</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./pca.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">PCA</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./a1-startingR.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Installing or accessing R and RStudio</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./a2-firstR.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">A first session in RStudio</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./a3-basicsR.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Some basic tasks in R</span></span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Table of contents</h2>
   
  <ul>
<li><a href="#two-sample-t-based-methods-for-comparing-two-means" id="toc-two-sample-t-based-methods-for-comparing-two-means" class="nav-link active" data-scroll-target="#two-sample-t-based-methods-for-comparing-two-means"><span class="header-section-number">12.1</span> Two sample t-based methods for comparing two means</a></li>
  <li><a href="#wilcoxon-based-methods-for-comparing-locations" id="toc-wilcoxon-based-methods-for-comparing-locations" class="nav-link" data-scroll-target="#wilcoxon-based-methods-for-comparing-locations"><span class="header-section-number">12.2</span> Wilcoxon-based methods for comparing locations</a></li>
  <li>
<a href="#a-randomization-test-using-a-t-test-test-statistic" id="toc-a-randomization-test-using-a-t-test-test-statistic" class="nav-link" data-scroll-target="#a-randomization-test-using-a-t-test-test-statistic"><span class="header-section-number">12.3</span> A randomization test using a t-test test statistic</a>
  <ul class="collapse">
<li><a href="#comparing-means" id="toc-comparing-means" class="nav-link" data-scroll-target="#comparing-means">Comparing means</a></li>
  <li><a href="#comparing-medians" id="toc-comparing-medians" class="nav-link" data-scroll-target="#comparing-medians">Comparing medians</a></li>
  </ul>
</li>
  <li><a href="#sample-size-estimation-and-power-analysis" id="toc-sample-size-estimation-and-power-analysis" class="nav-link" data-scroll-target="#sample-size-estimation-and-power-analysis"><span class="header-section-number">12.4</span> Sample size estimation and power analysis</a></li>
  </ul><div class="toc-actions"><ul><li><a href="https://github.com/emontoya2/edit/master/twoindptmeans.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./twosample.html">Module: Two sample methods</a></li><li class="breadcrumb-item"><a href="./twoindptmeans.html"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Two sample methods</span></a></li></ol></nav><div class="quarto-title">
<h1 class="title"><span id="sec-indpttwosamp" class="quarto-section-identifier"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Two sample methods</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header><div id="fig-hist_art" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-hist_art-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/twosampmod/histart.jpg" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-hist_art-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;12.1: AI art generated by keywords “two-sample t-test”
</figcaption></figure>
</div>
<p>Consider comparing independent populations in regard to the mean or median of some attribute, or two treatments by comparing the true mean or median response under each treatment in an experiment. In this section, the following hypothesis tests (HT) for such comparisons are illustrated:</p>
<ul>
<li><p><em>t</em>-based or t-test based for comparing two means</p></li>
<li><p>Wilcoxon rank sum test for comparing distributions or location shifts</p></li>
<li><p>Randomization test for comparing two means or two medians</p></li>
</ul>
<p>For confidence intervals (CIs), an overview of the two-sample <span class="math inline">\(t\)</span>-based CI for comparing means and Wilcoxon-based CI for comparing medians is provided. Equations/formulas used in HT or CIs will be kept at a minimum as the focus is on using software to carry out these methods. That being said, those new to or not comfortable with HT or CIs should consider reviewing <a href="siframework.html" class="quarto-xref"><span>Chapter 11</span></a>. These methods will be illustrated using a case study.</p>
<p>For any statistical inferential method to provide meaningful results, several assumptions are made about the data on which the method is intended to be used.</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Data assumptions
</div>
</div>
<div class="callout-body-container callout-body">
<p>The methods discussed in this section require one or more of the following assumptions about the data.</p>
<ul>
<li><p><strong>Assumption 1</strong>. Observations must be independent within each sample and between the two samples. Shared conditions, repeated measurements, or pairing can violate this assumption.</p></li>
<li><p><strong>Assumption 2</strong>. <em>No clear outliers</em> in either sample.</p></li>
<li><p><strong>Assumption 3</strong>. <em>Normality</em> or <em>large sample</em>. The data for each sample should be roughly normally distributed. If the sample size is large enough, the normality assumption is not needed.</p></li>
<li><p><strong>Assumption 4</strong>. <em>Equal variance or spread</em>. The variability in each sample should be about the same.</p></li>
</ul>
<p>While these assumptions are assessed within the illustrations of the inferential methods using a case study, assumption 1 can be assessed based on study design, histograms and boxplots for assumption 2, quantile-quantile plots for normality component of assumption 3, and boxplots, histograms, and sample standard deviation for assumption 4.</p>
</div>
</div>
<p>In these sections, we use R functions to conduct the inferential methods described earlier and provide detailed explanations of their use. While other functions may be used for tasks such as importing data and summarizing data numerically or graphically, we do not discuss them in this section as they have been covered in a previous module.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Notation
</div>
</div>
<div class="callout-body-container callout-body">
<p>To improve readability, we minimize the use of notation. However, when comparing two populations or treatments denoted by A and B, we use the following notation:</p>
<ul>
<li><p><span class="math inline">\(\mu_A\)</span> and <span class="math inline">\(\mu_B\)</span> denote the population or true mean response under A and B, respectively.</p></li>
<li><p><span class="math inline">\(\bar{y}_A\)</span> and <span class="math inline">\(\bar{y}_B\)</span> denote the sample mean of the corresponding samples obtained from A and B.</p></li>
<li><p><span class="math inline">\(\eta_A\)</span> and <span class="math inline">\(\eta_B\)</span> denote the population or true median response under A and B, respectively.</p></li>
<li><p><span class="math inline">\(m_A\)</span> and <span class="math inline">\(m_B\)</span> denote the sample median of the corresponding samples obtained from A and B.</p></li>
</ul>
</div>
</div>
<section id="two-sample-t-based-methods-for-comparing-two-means" class="level2" data-number="12.1"><h2 data-number="12.1" class="anchored" data-anchor-id="two-sample-t-based-methods-for-comparing-two-means">
<span class="header-section-number">12.1</span> Two sample t-based methods for comparing two means</h2>
<p>The independent two-sample t-test is a commonly used hypothesis test for comparing two groups or populations. There are two versions of this test: Student’s t-test and Welch’s t-test. Both tests can be used to compare whether the difference between the true averages (from two independent populations) is statistically significant or to determine if an effect (when comparing two treatments) is significant. This helps to determine if the difference or effect is due to chance or not. The t-based confidence interval for the difference in true averages provides a range of plausible values for the difference at a specified level of significance. These methods are generally referred to as t-based methods.</p>
<p>Student’s two-sample t-based methods assume assumptions 1, 2, 3, and 4 hold. The version of the t-based methods used here are called the Welch two-sample t-based methods, which do not require homogeneity of variances assumption. The Welch two-sample t-test statistic takes the following form:</p>
<p><span class="math display">\[T=\frac{(\bar{y}_{A}-\bar{y}_{B}) -\Delta_0}{\sqrt{\frac{s_{A}^2}{n_{A}}+\frac{s_{B}^2}{n_{B}}}},\]</span> where <span class="math inline">\(n\)</span> and <span class="math inline">\(s\)</span> denote sample size and standard deviation, and <span class="math inline">\(\Delta_0\)</span> is the mean difference specified by the null (zero here).</p>
<p>The data should consist of two variables of interest: a numerical variable that measures the outcome or response of interest and a factor or grouping variable with two levels. The grouping variable distinguishes the different populations or treatments (A or B). The hypothesis takes the form</p>
<p><span class="math display">\[H_0: \mu_A - \mu_B=0 \qquad H_a: \mu_A -\mu_B \neq 0\]</span></p>
<p>One may also consider the test in terms of an effect <span class="math inline">\(\delta_\mu=\mu_A - \mu_B\)</span>,</p>
<p><span class="math display">\[H_0: \delta_\mu=0 \qquad H_a: \delta_\mu \neq 0\]</span></p>
<p>Under <span class="math inline">\(H_0\)</span>, the null distribution of Welch’s T is approximated by a t-distribution with a certain degree of freedom<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>, and it is used to compute the p-value. The function <code>two.mean.test()</code><a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a> computes the test statistic and p-value for the two-sample t-test, as well as provide a confidence interval for <span class="math inline">\(\mu_A - \mu_B\)</span>.</p>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>R functions
</div>
</div>
<div class="callout-body-container callout-body">
<pre><code>### two.mean.test( y ~ x , data , first.level,
###            direction, conf.level,
###            welch)
# y: Replace y with the name of the response (measured)
#  variable of interest.
# x: Replace x with the name of the factor or grouping
#  variable that distinguishes the different populations 
#  or treatments.
# data: Set equal to the data frame name.
# first.level: Set equal to the level/category from the 
#       grouping variable. It determines how the difference 
#       in sample means is computed.  It should be consistent 
#       with the formulation of the hypothesis.
# direction: Set equal to the sign in the alternative: "two.sided",
#             "greater" , or "less".
# conf.level: Set equal to the confidence level for the CI (default is .95). 
#               The function will always provide a CI by default.
# welch: Set equal to TRUE (default) for Welch's t-test. Set
#        to FALSE for Student's t-test.</code></pre>
</div>
</div>
<p>Many of the R functions used in this resource will have identical arguments. Therefore, while the arguments will be provided for any functions used, common arguments such as <code>data</code>, <code>direction</code>, … will generally only be described once within a given module.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>We apply two-sample t-based methods (hypothesis testing and CI) to the data described in the case study provided in <a href="datacs3.html" class="quarto-xref"><span>Chapter 3</span></a>. The goal is to determine if there is a significant difference in PM10 concentration between Kern and Fresno counties and to estimate the difference between the true means.</p>
<p>The data provided in the case study consists of several variables (<code>PM10</code>, <code>AQI</code>, …, <code>county</code>, and <code>City.Name</code>). A subset of the data were created so that it included only <code>PM10</code> (daily PM10 levels) and <code>county</code> (county in which the monitoring site is located) for the two counties of interest. To start, the data are imported and numerical and graphical summaries of the data would be created. However, graphical and numerical data summaries are covered in other modules. The focus here is to assess model assumptions either numerically or graphically.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist">
<li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-1-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-1" role="tab" aria-controls="tabset-1-1" aria-selected="true" href="" aria-current="page">R code</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-2" role="tab" aria-controls="tabset-1-2" aria-selected="false" href="">Video</a></li>
</ul>
<div class="tab-content">
<div id="tabset-1-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-1-1-tab">
<div class="cell" data-layout-align="center">
<details open="" class="code-fold"><summary>Code</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Import the data and save the data in a </span></span>
<span><span class="co"># data frame called 'KernFresnoPM10df'</span></span>
<span><span class="va">KernFresnoPM10df</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/utils/read.table.html">read.csv</a></span><span class="op">(</span><span class="st">"datasets/KernFresnoDailyPM10.2021.csv"</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Load the 'dplyr' package, which provides the 'mutate()' function.</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://dplyr.tidyverse.org">dplyr</a></span><span class="op">)</span> </span>
<span></span>
<span><span class="co"># Tell R that 'county' should be treated as a factor variable by using mutate().</span></span>
<span><span class="va">KernFresnoPM10df</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span> <span class="va">KernFresnoPM10df</span>, </span>
<span>              county<span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">as.factor</a></span><span class="op">(</span> <span class="va">county</span> <span class="op">)</span> <span class="op">)</span></span>
<span></span>
<span></span>
<span><span class="co"># Print a summary of the data frame, including </span></span>
<span><span class="co"># variable names and other information.</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span> <span class="va">KernFresnoPM10df</span> <span class="op">)</span> </span>
<span><span class="co">#&gt;       PM10             AQI             temp           Latitude    </span></span>
<span><span class="co">#&gt;  Min.   :  0.00   Min.   :  0.0   Min.   : 35.13   Min.   :35.05  </span></span>
<span><span class="co">#&gt;  1st Qu.: 18.00   1st Qu.: 17.0   1st Qu.: 54.04   1st Qu.:35.44  </span></span>
<span><span class="co">#&gt;  Median : 31.00   Median : 29.0   Median : 64.64   Median :35.64  </span></span>
<span><span class="co">#&gt;  Mean   : 37.34   Mean   : 32.1   Mean   : 66.78   Mean   :35.98  </span></span>
<span><span class="co">#&gt;  3rd Qu.: 48.00   3rd Qu.: 44.0   3rd Qu.: 80.00   3rd Qu.:36.79  </span></span>
<span><span class="co">#&gt;  Max.   :437.00   Max.   :316.0   Max.   :102.00   Max.   :36.99  </span></span>
<span><span class="co">#&gt;                                   NAs    :391                     </span></span>
<span><span class="co">#&gt;    Longitude        windspeed             state         county    </span></span>
<span><span class="co">#&gt;  Min.   :-119.8   Min.   : 0.7708   Length   :2773   Fresno:1046  </span></span>
<span><span class="co">#&gt;  1st Qu.:-119.7   1st Qu.: 2.4333   N.unique :   1   Kern  :1727  </span></span>
<span><span class="co">#&gt;  Median :-119.0   Median : 3.6500   N.blank  :   0                </span></span>
<span><span class="co">#&gt;  Mean   :-118.9   Mean   : 4.4577   Min.nchar:  10                </span></span>
<span><span class="co">#&gt;  3rd Qu.:-118.1   3rd Qu.: 5.2583   Max.nchar:  10                </span></span>
<span><span class="co">#&gt;  Max.   :-117.7   Max.   :22.4625                                 </span></span>
<span><span class="co">#&gt;                                                                   </span></span>
<span><span class="co">#&gt;      City.Name   </span></span>
<span><span class="co">#&gt;  Length   :2773  </span></span>
<span><span class="co">#&gt;  N.unique :   7  </span></span>
<span><span class="co">#&gt;  N.blank  :   0  </span></span>
<span><span class="co">#&gt;  Min.nchar:   6  </span></span>
<span><span class="co">#&gt;  Max.nchar:  13  </span></span>
<span><span class="co">#&gt;                  </span></span>
<span><span class="co">#&gt; </span></span>
<span></span>
<span></span>
<span><span class="co"># Load the 'lattice' package, which provides the 'bwplot()' function.</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://lattice.r-forge.r-project.org/">lattice</a></span><span class="op">)</span> </span>
<span></span>
<span><span class="co"># Create a box plot of Air Quality Index (AQI) by county levels using the 'bwplot()' function</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/lattice/man/xyplot.html">bwplot</a></span><span class="op">(</span><span class="va">PM10</span> <span class="op">~</span> <span class="va">county</span>,                   <span class="co">#  y ~ x</span></span>
<span>       data <span class="op">=</span> <span class="va">KernFresnoPM10df</span>,        <span class="co"># set the data frame to use</span></span>
<span>       xlab <span class="op">=</span> <span class="st">"County"</span>,                <span class="co"># set the x-axis label</span></span>
<span>       ylab <span class="op">=</span> <span class="st">"PM10"</span>,                   <span class="co"># set the y-axis label</span></span>
<span>       main <span class="op">=</span> <span class="st">"PM10 Distribution by County"</span>, <span class="co"># set the plot title</span></span>
<span>       fill <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"gray"</span>, <span class="st">"brown"</span><span class="op">)</span><span class="op">)</span>      <span class="co"># fill the boxes with specified colors</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details><div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="twoindptmeans_files/figure-html/unnamed-chunk-1-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
<details open="" class="code-fold"><summary>Code</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb3"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span></span>
<span><span class="co"># Load the 'mosaic' package, which allows using </span></span>
<span><span class="co"># formula expressions in 'mean()' and 'sd()'</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span> <span class="va"><a href="https://github.com/ProjectMOSAIC/mosaic">mosaic</a></span> <span class="op">)</span> </span>
<span></span>
<span><span class="co"># Compute the sample mean for each county</span></span>
<span><span class="fu">mean</span><span class="op">(</span> <span class="va">PM10</span> <span class="op">~</span> <span class="va">county</span> ,</span>
<span>   data<span class="op">=</span> <span class="va">KernFresnoPM10df</span> <span class="op">)</span></span>
<span><span class="co">#&gt;   Fresno     Kern </span></span>
<span><span class="co">#&gt; 41.09943 35.06717</span></span>
<span></span>
<span><span class="co"># Compute the sample standard deviation for each county</span></span>
<span><span class="fu"><a href="https://www.mosaic-web.org/mosaic/reference/aggregating.html">sd</a></span><span class="op">(</span> <span class="va">PM10</span> <span class="op">~</span> <span class="va">county</span> ,</span>
<span>  data<span class="op">=</span> <span class="va">KernFresnoPM10df</span> <span class="op">)</span></span>
<span><span class="co">#&gt;   Fresno     Kern </span></span>
<span><span class="co">#&gt; 31.88051 32.26383</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</div>
<div id="tabset-1-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-2-tab">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="vembedr">
<div>
<iframe src="https://www.youtube.com/embed/zFTeJ559NIY" width="533" height="300" frameborder="0" allowfullscreen="" data-external="1"></iframe>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
<p>The difference in samples means between Kern and Fresno county is</p>
<p><span class="math display">\[35.067-41.099=\bar{x}_K-\bar{x}_F=-6.032.\]</span></p>
<p>The estimated mean difference is -6.032 PM10 units. The following CI and test illustrate an independent-observation model. Independence requires assessment: daily measurements can be correlated over time and across counties through shared weather. Different county labels do not establish independence. Large sample sizes do not repair dependence, and broader population inference requires a suitable sampling or statistical model<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a>.</p>
<p>Graphical summaries show spread and unusual values in each county. The sample standard deviations should be computed for PM10, as in the code above, rather than for AQI. A ratio of standard deviations is at most a rough guide to comparable spread; it does not establish independence or guarantee validity.</p>
<p>Independence remains unverified, and neither rank tests nor arbitrary shuffling resolve dependence. For but for illustration we analyze the data using the two-sample t-based methods. Let <span class="math inline">\(\mu_K\)</span> denote the true mean PM10 levels in Kern county. <span class="math inline">\(\mu_F\)</span> is defined analogously for Fresno county. Since an aim is to determine if there is significant difference between PM10 levels in Kern and Fresno county, the hypothesis is</p>
<p><span class="math display">\[H_0: \mu_K - \mu_F=0 \qquad H_a: \mu_K- \mu_F \neq 0\]</span></p>
<p>The following code uses <code>two.mean.test()</code> to compute the test statistic, the corresponding p-value, and a 99% confidence interval:</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist">
<li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-2-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-1" role="tab" aria-controls="tabset-2-1" aria-selected="true" href="">R code</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-2-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-2" role="tab" aria-controls="tabset-2-2" aria-selected="false" href="">Video</a></li>
</ul>
<div class="tab-content">
<div id="tabset-2-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-2-1-tab">
<details open="" class="code-fold"><summary>Code</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb4"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">pm10_fit</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://www.mosaic-web.org/mosaic/reference/ttest.html">t.test</a></span><span class="op">(</span></span>
<span>  <span class="va">KernFresnoPM10df</span><span class="op">$</span><span class="va">PM10</span><span class="op">[</span><span class="va">KernFresnoPM10df</span><span class="op">$</span><span class="va">county</span> <span class="op">==</span> <span class="st">"Kern"</span><span class="op">]</span>,</span>
<span>  <span class="va">KernFresnoPM10df</span><span class="op">$</span><span class="va">PM10</span><span class="op">[</span><span class="va">KernFresnoPM10df</span><span class="op">$</span><span class="va">county</span> <span class="op">==</span> <span class="st">"Fresno"</span><span class="op">]</span>,</span>
<span>  conf.level<span class="op">=</span><span class="fl">.99</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Source the function two.mean.test() so that it's R's memory.</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/source.html">source</a></span><span class="op">(</span><span class="st">"rfuns/two.mean.test.R"</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Recall that the data were imported and stored in "KernFresnoPM10df"</span></span>
<span></span>
<span><span class="co"># The function will require the following information:</span></span>
<span><span class="co"># y: Replace with 'PM10'</span></span>
<span><span class="co"># x: Replace with 'county'</span></span>
<span><span class="co"># data: Set equal to a 'KernFresnoPM10df'</span></span>
<span><span class="co"># first.level: The county that appears first in the hypothesis</span></span>
<span><span class="co">#                (Kern county), so set equal to "Kern"</span></span>
<span><span class="co"># direction: It is a two-sided alternative, so set equal to "two.sided"</span></span>
<span><span class="co"># conf.level: Set equal .99 since we seek a 99% CI</span></span>
<span><span class="co"># welch: The Welch t-test is the default method here, so using </span></span>
<span><span class="co">#     the default value (TRUE)</span></span>
<span></span>
<span></span>
<span><span class="fu">two.mean.test</span><span class="op">(</span> <span class="va">PM10</span> <span class="op">~</span> <span class="va">county</span> ,          <span class="co"># y ~ x</span></span>
<span>               data <span class="op">=</span> <span class="va">KernFresnoPM10df</span> ,<span class="co"># specify the data frame to use</span></span>
<span>               first.level <span class="op">=</span> <span class="st">"Kern"</span> ,   <span class="co"># specify the first level in the hypothesis</span></span>
<span>               direction <span class="op">=</span> <span class="st">"two.sided"</span> ,<span class="co"># specify a two-sided alternative</span></span>
<span>               conf.level <span class="op">=</span> <span class="fl">.99</span> <span class="op">)</span>       <span class="co"># set the confidence level to .99</span></span>
<span><span class="co">#&gt;      Theoretical-based two-sample test for independent samples </span></span>
<span><span class="co">#&gt;                               </span></span>
<span><span class="co">#&gt; formula:  PM10 ~ county </span></span>
<span><span class="co">#&gt; sample mean of  Kern  group: 35.06717 </span></span>
<span><span class="co">#&gt; sample mean of  Fresno  group: 41.09943 </span></span>
<span><span class="co">#&gt; sample sd of  Kern  group: 32.26383 </span></span>
<span><span class="co">#&gt; sample sd of  Fresno  group: 31.88051 </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; difference between groups: ( Kern  group ) - (  Fresno  group ) </span></span>
<span><span class="co">#&gt; obs t-test statistic: -4.807498              p-value = 1.63e-06 </span></span>
<span><span class="co">#&gt; df=  2225.184 </span></span>
<span><span class="co">#&gt; direction: two.sided </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Confidence level:  0.99 </span></span>
<span><span class="co">#&gt; CI:(  -9.267081 ,  -2.797435 )</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details><div class="cell quarto-layout-panel" data-layout-align="center" data-layout-ncol="1">

</div>
</div>
<div id="tabset-2-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-2-2-tab">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="vembedr">
<div>
<iframe src="https://www.youtube.com/embed/CoCyvWPDEPs" width="533" height="300" frameborder="0" allowfullscreen="" data-external="1"></iframe>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
<p>The output includes the following information:</p>
<ul>
<li><p>The sample mean and standard deviation under each level of the grouping/factor variable.</p></li>
<li><p>The value of the observed statistic: <span class="math inline">\(T=-4.8075\)</span></p></li>
<li><p>p-value</p></li>
<li><p>A confidence interval</p></li>
</ul>
<p>The nominal Welch statistic is <span class="math inline">\(T=-4.8075\)</span>, with p approximately <span class="math inline">\(1.63\times10^{-6}\)</span>. It rejects a zero mean difference at <span class="math inline">\(\alpha=.01\)</span> under the independent-observation model. Dependence among daily readings can affect this calculation, so the result does not establish a validated county effect.</p>
<p>The nominal 99% CI for Kern minus Fresno mean PM10 is (-9.267, -2.797). Its negative bounds indicate a higher estimated mean at the Fresno sites under the model. These uncertainty estimates require independent observations; temporal dependence and site selection limit inference.</p>
</div>
</div>
</section><section id="wilcoxon-based-methods-for-comparing-locations" class="level2" data-number="12.2"><h2 data-number="12.2" class="anchored" data-anchor-id="wilcoxon-based-methods-for-comparing-locations">
<span class="header-section-number">12.2</span> Wilcoxon-based methods for comparing locations</h2>
<p>Outliers or departures from normality do not automatically invalidate t-based methods; their importance depends on sample size, severity, and robustness. Rank-based methods use ordering and are less sensitive to extreme magnitudes, but are not unaffected by unusual observations. Wilcoxon methods require independent observations and a suitable null distribution<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a>. A common-shape shift model supports interpreting them as median comparisons. There is no universal minimum of ten observations for an exact rank test<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a>.</p>
<p>The Wilcoxon rank sum (Mann–Whitney) test compares ranks between two independent samples. Under a common-shape location-shift model, it tests a zero location shift, equivalent to equal population medians. With different shapes, rejection can reflect other distributional differences.</p>
<p>The test statistic for the Wilcoxon rank sum test depends on the ranks of the observed data, and its value will be provided by software. However, some details regarding the computation of the test statistic are provided below:</p>
<ol type="1">
<li><p>List the observations for both samples from smallest to largest across both groups.</p></li>
<li><p>Assign the numbers <span class="math inline">\(1\)</span> to <span class="math inline">\(n_A+n_B=N\)</span> to the observations (across both groups) with 1 assigned to the smallest observations and <span class="math inline">\(N\)</span> to the largest observation. These are called ranks of the observations.</p></li>
<li><p>If there are ties (due to repeated values) in the combined data set, the ranks for the observations in a tie are taken to be the average of the ranks for those observations.</p></li>
<li><p>Let <span class="math inline">\(W\)</span> denote the sum of the ranks for the observations from group A.</p></li>
</ol>
<p>The test statistic then takes the form</p>
<p><span class="math display">\[U=W-\frac{n_A(n_A+1)}{2}\]</span> Whereas the null hypothesis of the two-sample t test is equal means, under the common-shape shift model the Wilcoxon null<a href="#fn6" class="footnote-ref" id="fnref6" role="doc-noteref"><sup>6</sup></a> can be expressed as equal medians:</p>
<p><span class="math display">\[H_0: \eta_A - \eta_B=0 \qquad H_a: \eta_A -\eta_B \neq 0\]</span></p>
<p>One may also consider the test in terms of an effect <span class="math inline">\(\delta_\eta=\eta_A - \eta_B\)</span>,</p>
<p><span class="math display">\[H_0: \delta_\eta=0 \qquad H_a: \delta_\eta \neq 0\]</span></p>
<p>Under <span class="math inline">\(H_0\)</span>, the null distribution of U is called the Wilcoxon distribution and it is used to compute the p-value<a href="#fn7" class="footnote-ref" id="fnref7" role="doc-noteref"><sup>7</sup></a>. The function <code>two.wilcox.test()</code><a href="#fn8" class="footnote-ref" id="fnref8" role="doc-noteref"><sup>8</sup></a> computes the test statistic and p-value<a href="#fn9" class="footnote-ref" id="fnref9" role="doc-noteref"><sup>9</sup></a>, as well as a CI.</p>
<p>The CI estimates the location shift using the median of pairwise differences between the groups<a href="#fn10" class="footnote-ref" id="fnref10" role="doc-noteref"><sup>10</sup></a>. It is not an interval for an individual future pair, nor generally the difference of sample medians. A common-shape shift model, without requiring symmetry, supports the difference-in-population-medians interpretation.</p>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>R functions
</div>
</div>
<div class="callout-body-container callout-body">
<pre><code>### two.wilcox.test( y ~ x , data , first.level,
###            direction, conf.level)
# y: Replace y with the name of the response (measured)
#  variable of interest
# x: Replace x with the name of the factor or grouping
#  variable that distinguishes the different populations 
#  or treatments
# data: Set equal to the data frame being used.
# first.level: Set equal to a level/category from the grouping 
#              variable. It determines how the difference in 
#              sample means is computed.  It should be consistent
#              with the formulation of the hypothesis.
# direction: Set equal to the sign in the alternative: "two.sided", 
#            "greater" , or "less"
# conf.level: Set equal to the confidence level for the CI (default 
#             is .95). The function will always provide a CI by default.</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>The PM10 example illustrates a Wilcoxon location comparison and CI. Repeated daily observations leave independence unverified. Rank methods do not fix that dependence. Violin plots help examine whether a common-shape shift interpretation is plausible, but cannot establish it.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist">
<li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-3-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-1" role="tab" aria-controls="tabset-3-1" aria-selected="true" href="">R code</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-3-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-2" role="tab" aria-controls="tabset-3-2" aria-selected="false" href="">Video</a></li>
</ul>
<div class="tab-content">
<div id="tabset-3-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-3-1-tab">
<div class="cell" data-layout-align="center">
<details open="" class="code-fold"><summary>Code</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb6"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://lattice.r-forge.r-project.org/">lattice</a></span><span class="op">)</span> <span class="co"># Provides the bwplot() function</span></span>
<span></span>
<span><span class="co"># Create a violin plot </span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/lattice/man/xyplot.html">bwplot</a></span><span class="op">(</span> <span class="va">PM10</span> <span class="op">~</span> <span class="va">county</span> , </span>
<span>    data<span class="op">=</span> <span class="va">KernFresnoPM10df</span> , </span>
<span>    xlab<span class="op">=</span> <span class="st">"County"</span> , </span>
<span>    ylab<span class="op">=</span> <span class="st">"PM10"</span> ,</span>
<span>    main<span class="op">=</span> <span class="st">"PM10 vs county"</span> , </span>
<span>    panel<span class="op">=</span> <span class="va">panel.violin</span> <span class="op">)</span> <span class="co"># set equal to panel.violin to create violin plot</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details><div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="twoindptmeans_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</div>
<div id="tabset-3-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-3-2-tab">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="vembedr">
<div>
<iframe src="https://www.youtube.com/embed/CxlMXEWbi3U" width="533" height="300" frameborder="0" allowfullscreen="" data-external="1"></iframe>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
<p>The violin boxplot makes it clearer that the distribution of PM10 in both counties approximately have the same shape.</p>
<p>Let <span class="math inline">\(\eta_K\)</span> denote the true median PM10 levels in Kern county. <span class="math inline">\(\eta_F\)</span> is defined analogously for Fresno county. Since an aim is to determine if there is significant difference between PM10 levels in Kern and Fresno county, the hypothesis is</p>
<p><span class="math display">\[H_0: \eta_K - \eta_F=0 \qquad H_a: \eta_K- \eta_F \neq 0\]</span></p>
<p>The following code uses <code>two.wilcox.test()</code> to compute the test statistic, the corresponding p-value, and a 99% confidence interval:</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist">
<li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-4-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-4-1" role="tab" aria-controls="tabset-4-1" aria-selected="true" href="">R code</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-4-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-4-2" role="tab" aria-controls="tabset-4-2" aria-selected="false" href="">Video</a></li>
</ul>
<div class="tab-content">
<div id="tabset-4-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-4-1-tab">
<details open="" class="code-fold"><summary>Code</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb7"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Source the function two.wilcox.test() so that it's R's memory.</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/source.html">source</a></span><span class="op">(</span><span class="st">"rfuns/two.wilcox.test.R"</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># The function will require the following information:</span></span>
<span><span class="co"># y: Replace with 'PM10'</span></span>
<span><span class="co"># x: Replace with 'county'</span></span>
<span><span class="co"># data: Set equal to a 'KernFresnoPM10df'</span></span>
<span><span class="co"># first.level: The county that appears first in the hypothesis</span></span>
<span><span class="co">#                (Kern county), set equal to "Kern"</span></span>
<span><span class="co"># direction: It is a two-sided alternative, so set equal to "two.sided"</span></span>
<span></span>
<span></span>
<span><span class="fu">two.wilcox.test</span><span class="op">(</span><span class="va">PM10</span> <span class="op">~</span> <span class="va">county</span> ,           <span class="co"># y ~ x</span></span>
<span>                data <span class="op">=</span> <span class="va">KernFresnoPM10df</span> , <span class="co"># Specify the data frame to use</span></span>
<span>                first.level <span class="op">=</span> <span class="st">"Kern"</span> ,    <span class="co"># Specify the first level in the hypothesis</span></span>
<span>                direction <span class="op">=</span> <span class="st">"two.sided"</span> , <span class="co"># Specify a two-sided alternative</span></span>
<span>                conf.level <span class="op">=</span> <span class="fl">.99</span> <span class="op">)</span>        <span class="co"># Set the confidence level to .99</span></span>
<span><span class="co">#&gt;      Theoretical-based two-sample test for independent samples </span></span>
<span><span class="co">#&gt;                               </span></span>
<span><span class="co">#&gt; formula:  PM10 ~ county </span></span>
<span><span class="co">#&gt; sample median of  Kern  group: 28 </span></span>
<span><span class="co">#&gt; sample median of  Fresno  group: 34 </span></span>
<span><span class="co">#&gt; sample IQR of  Kern  group: 30 </span></span>
<span><span class="co">#&gt; sample IQR of  Fresno  group: 29 </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; method:  Wilcoxon rank sum test with continuity correction </span></span>
<span><span class="co">#&gt; difference between groups: ( Kern  group ) - (  Fresno  group ) </span></span>
<span><span class="co">#&gt; obs test statistic: U=  759219.5              p-value = 1.821e-12 </span></span>
<span><span class="co">#&gt; obs standardized test statistic: Z=  -7.048 </span></span>
<span><span class="co">#&gt; direction: two.sided </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; difference in location (pseudomedian):  -6.000007 </span></span>
<span><span class="co">#&gt; confidence level:  0.99 </span></span>
<span><span class="co">#&gt; CI:(  -8.000049 ,  -3.999966 )</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details><div class="cell quarto-layout-panel" data-layout-align="center" data-layout-ncol="1">

</div>
</div>
<div id="tabset-4-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-4-2-tab">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="vembedr">
<div>
<iframe src="https://www.youtube.com/embed/75m-E5v5w20" width="533" height="300" frameborder="0" allowfullscreen="" data-external="1"></iframe>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
<p>The output includes the following information:</p>
<ul>
<li><p>The sample median and IQR under each level of the grouping/factor variable.</p></li>
<li><p>The value of the observed statistic</p></li>
<li><p>p-value</p></li>
<li><p>A confidence interval</p></li>
</ul>
<p>Based on the output, the observed value of the test statistic is <span class="math inline">\(U=759219.5\)</span>. The p-value is small and positive; use the unrounded R result rather than reporting a rounded zero. Since p-value<span class="math inline">\(\leq\alpha=.01\)</span>, we have significant evidence to reject <span class="math inline">\(H_0\)</span>. Therefore, we have strong evidence that there is significant difference between PM10 levels in Kern and Fresno county at the designated monitoring sites.</p>
<p>The nominal 99% CI for the location shift is (-8.000, -4.000), estimated from between-group pairwise differences. Under a common-shape shift model this describes the population-median difference, not the difference between two future readings. Dependence among daily records could change uncertainty, so this is an illustration conditional on independent-observation assumptions.</p>
</div>
</div>
</section><section id="a-randomization-test-using-a-t-test-test-statistic" class="level2" data-number="12.3"><h2 data-number="12.3" class="anchored" data-anchor-id="a-randomization-test-using-a-t-test-test-statistic">
<span class="header-section-number">12.3</span> A randomization test using a t-test test statistic</h2>
<p>Randomization tests compare the observed statistic with its distribution under a null and the study’s actual assignment mechanism. For observational data, a permutation test instead needs a defensible exchangeability argument. Equality of means or medians alone does not imply that all label permutations are valid.</p>
<p>Randomization tests require assumptions. Under a sharp null of no individual treatment effect, reassign treatments according to the actual randomization design. For observational comparisons, unrestricted shuffling requires exchangeability under the null. A studentized statistic can support asymptotic validity under additional conditions, but does not justify arbitrary shuffling. Small samples also limit attainable p-values and power.</p>
<section id="comparing-means" class="level3 unnumbered"><h3 class="unnumbered anchored" data-anchor-id="comparing-means">Comparing means</h3>
<p>Here the statistic is Welch’s studentized difference in means. The shuffling is valid only under the design or exchangeability conditions just described. Extreme observations can affect this statistic; a categorical “no outliers” rule is not by itself a justification for the test.</p>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>R functions
</div>
</div>
<div class="callout-body-container callout-body">
<pre><code>### two.mean.test( y ~ x , data , first.level,
###            direction, randtest, 
###            nshuffles)
# randtest: Set equal to TRUE to obtain the test statistic and p-value
#      for the randomization test (for comparing means).
# nshuffles: Set equal to the desired number of randomizations. </code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>This example illustrates label shuffling for a difference in county means. Outliers alone do not determine its validity. Exchangeability of daily county records is unverified, so the result is a teaching calculation rather than a validated test of a county effect. Let <span class="math inline">\(\delta_\mu=\mu_K-\mu_F\)</span>. The hypotheses are:</p>
<p><span class="math display">\[H_0: \delta_\mu=0 \qquad H_a: \delta_\mu \neq 0\]</span></p>
<p>The following code uses <code>two.mean.test()</code> to compute the test statistic and the corresponding p-value for a randomization test involving a difference in means.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist">
<li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-5-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-5-1" role="tab" aria-controls="tabset-5-1" aria-selected="true" href="">R code</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-5-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-5-2" role="tab" aria-controls="tabset-5-2" aria-selected="false" href="">Video</a></li>
</ul>
<div class="tab-content">
<div id="tabset-5-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-5-1-tab">
<details open="" class="code-fold"><summary>Code</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb9"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Data was imported earlier in the section </span></span>
<span><span class="co"># and 'mutate' converted 'county' into a factor variable.</span></span>
<span></span>
<span><span class="co"># Source the function two.mean.test() so that it's R's memory.</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/source.html">source</a></span><span class="op">(</span><span class="st">"rfuns/two.mean.test.R"</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># The function will require the following information:</span></span>
<span><span class="co"># y: Replace with 'PM10'</span></span>
<span><span class="co"># x: Replace with 'county'</span></span>
<span><span class="co"># data: Set equal to a 'KernFresnoPM10df'</span></span>
<span><span class="co"># first.level: In the hypothesis, Kern county appeared first in the</span></span>
<span><span class="co">#       difference, so set equal to "Kern"</span></span>
<span><span class="co"># direction: It is a two-sided alternative, so set equal to "two.sided"</span></span>
<span><span class="co"># randtest: Set equal to TRUE. </span></span>
<span><span class="co"># nshuffles: Set equal to 30,000 </span></span>
<span></span>
<span></span>
<span><span class="fu">two.mean.test</span><span class="op">(</span><span class="va">PM10</span> <span class="op">~</span> <span class="va">county</span> ,           <span class="co"># specify the variables for the test</span></span>
<span>              data <span class="op">=</span> <span class="va">KernFresnoPM10df</span> , <span class="co"># specify the data frame to use</span></span>
<span>              first.level <span class="op">=</span> <span class="st">"Kern"</span> ,    <span class="co"># specify the first level in the hypothesis</span></span>
<span>              direction <span class="op">=</span> <span class="st">"two.sided"</span> , <span class="co"># specify a two-sided alternative</span></span>
<span>              randtest <span class="op">=</span> <span class="cn">TRUE</span> ,         <span class="co"># perform a simulation-based test</span></span>
<span>              nshuffles <span class="op">=</span> <span class="fl">30000</span> <span class="op">)</span>       <span class="co"># set the number of randomizations to 30,000</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details><div class="cell quarto-layout-panel" data-layout-align="center" data-layout-ncol="1">

</div>
</div>
<div id="tabset-5-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-5-2-tab">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="vembedr">
<div>
<iframe src="https://www.youtube.com/embed/Kbkt9vf7eiU" width="533" height="300" frameborder="0" allowfullscreen="" data-external="1"></iframe>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
<p>The output reports summaries, the observed studentized difference, and a Monte Carlo p-value. This wrapper does not construct a randomization CI; the estimated difference still describes effect size. The shuffling exercise does not address the dependence concerns in these daily records.</p>
</div>
</div>
</section><section id="comparing-medians" class="level3 unnumbered"><h3 class="unnumbered anchored" data-anchor-id="comparing-medians">Comparing medians</h3>
<p>Here the shuffled statistic is the Wilcoxon rank statistic, not the sample-median difference. Under an exchangeable common-shape shift model it can support a median/location comparison; unequal shapes can change that interpretation.</p>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>R functions
</div>
</div>
<div class="callout-body-container callout-body">
<pre><code>### two.wilcox.test( y ~ x , data , first.level,
###            direction, conf.level)
###            randtest, nshuffles)
# randtest: Set equal to TRUE to obtain the test statistic and p-value
#      for the randomization test (for comparing medians).
# nshuffles: Set equal to the desired number of randomizations. </code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>The following shuffling exercise illustrates a permutation calculation with tied PM10 observations. Ties alone do not make this more accurate than a tie-adjusted normal approximation. Unrestricted county-label shuffling requires exchangeability, which shared weather and serial dependence may violate. It does not validate the earlier inferential conclusions.</p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold"><summary>Code</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb11"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Data was imported earlier in the section </span></span>
<span><span class="co"># and 'mutate' converted 'county' into a factor variable.</span></span>
<span></span>
<span><span class="co"># Load the 'lattice' package</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://lattice.r-forge.r-project.org/">lattice</a></span><span class="op">)</span> <span class="co"># provides the histogram() function</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/lattice/man/histogram.html">histogram</a></span><span class="op">(</span><span class="op">~</span> <span class="va">PM10</span> <span class="op">|</span> <span class="va">county</span> ,         <span class="co"># ~ "variable" | "grouping factor"</span></span>
<span>          data <span class="op">=</span> <span class="va">KernFresnoPM10df</span> , <span class="co"># Specify the data frame to use</span></span>
<span>          xlab <span class="op">=</span> <span class="st">"PM10"</span> ,           <span class="co"># Label the x-axis</span></span>
<span>          ylab <span class="op">=</span> <span class="st">"Frequency"</span> ,      <span class="co"># Label the y-axis</span></span>
<span>          main <span class="op">=</span> <span class="st">"PM10 by county"</span> <span class="op">)</span> <span class="co"># Add a title to the plot</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details><div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="twoindptmeans_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>To determine if there is significant county effect on PM10 levels when comparing Kern and Fresno county, let <span class="math inline">\(\delta_\eta=\eta_K - \eta_F\)</span>. The hypotheses are</p>
<p><span class="math display">\[H_0: \delta_\eta=0 \qquad H_a: \delta_\eta \neq 0\]</span></p>
<p>The following code uses <code>two.wilcox.test()</code> to compute the test statistic and the corresponding p-value for a randomization test involving a difference in medians</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist">
<li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-6-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-6-1" role="tab" aria-controls="tabset-6-1" aria-selected="true" href="">R code</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-6-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-6-2" role="tab" aria-controls="tabset-6-2" aria-selected="false" href="">Video</a></li>
</ul>
<div class="tab-content">
<div id="tabset-6-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-6-1-tab">
<details open="" class="code-fold"><summary>Code</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb12"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Data was imported earlier in the section </span></span>
<span><span class="co"># and 'mutate' converted 'county' into a factor variable.</span></span>
<span></span>
<span><span class="co"># Source the function two.wilcox.test() so that it's R's memory.</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/source.html">source</a></span><span class="op">(</span><span class="st">"rfuns/two.wilcox.test.R"</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># The function will require the following information:</span></span>
<span><span class="co"># y: replace with 'PM10'</span></span>
<span><span class="co"># x: replace with 'county'</span></span>
<span><span class="co"># data: set equal to a 'KernFresnoPM10df'</span></span>
<span><span class="co"># first.level: In the hypothesis, Kern county appeared first in the</span></span>
<span><span class="co">#       difference, so set equal to "Kern"</span></span>
<span><span class="co"># direction: It is a two-sided alternative, so set equal to "two.sided"</span></span>
<span><span class="co"># randtest: Set equal to TRUE. </span></span>
<span><span class="co"># nshuffles: Set equal to 30,000 </span></span>
<span></span>
<span><span class="fu">two.wilcox.test</span><span class="op">(</span><span class="va">PM10</span> <span class="op">~</span> <span class="va">county</span> ,           <span class="co"># Specify the variables for the test</span></span>
<span>                data <span class="op">=</span> <span class="va">KernFresnoPM10df</span> , <span class="co"># Specify the data frame to use</span></span>
<span>                first.level <span class="op">=</span> <span class="st">"Kern"</span> ,    <span class="co"># Specify the first level in the hypothesis</span></span>
<span>                direction <span class="op">=</span> <span class="st">"two.sided"</span> , <span class="co"># Specify a two-sided alternative</span></span>
<span>                randtest <span class="op">=</span> <span class="cn">TRUE</span> ,         <span class="co"># Perform a simulation-based test</span></span>
<span>                nshuffles <span class="op">=</span> <span class="fl">30000</span> <span class="op">)</span>       <span class="co"># Set the number of randomizations to 30,000</span></span>
<span>              </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details><div class="cell quarto-layout-panel" data-layout-align="center" data-layout-ncol="1">

</div>
</div>
<div id="tabset-6-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-6-2-tab">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="vembedr">
<div>
<iframe src="https://www.youtube.com/embed/JkBLLFUfkbg" width="533" height="300" frameborder="0" allowfullscreen="" data-external="1"></iframe>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
<p>The output reports summaries, the observed rank statistic, and a Monte Carlo p-value. This wrapper does not construct a randomization CI. Its validity still requires the exchangeability conditions discussed above.</p>
</div>
</div>
</section></section><section id="sample-size-estimation-and-power-analysis" class="level2" data-number="12.4"><h2 data-number="12.4" class="anchored" data-anchor-id="sample-size-estimation-and-power-analysis">
<span class="header-section-number">12.4</span> Sample size estimation and power analysis</h2>
<p>Ideally, estimating sample size for a study is one of the first steps that researchers take prior to collecting data. Knowing the sample size required to detect a desired effect at the beginning of a project allows one to manage their data collection efforts. Further, this allows for one to determine how much statistical power the test will have to detect an effect.</p>
<p>The R function <code><a href="https://rdrr.io/pkg/pwr/man/pwr.t2n.test.html">pwr.t2n.test()</a></code> from the <code>pwr</code> R package can be used to calculate statistical power for a two sample t-test when the sample sizes, significance level (<span class="math inline">\(\alpha\)</span>), and effect size are provided. The function <code>pwr.t.test</code> from the same package will provide the sample sizes required for a given power level, significance level (<span class="math inline">\(\alpha\)</span>), and effect size. Note that variability in each sample is assumed to be about the same. It is assumed the appropriate assumptions about the data are met<a href="#fn11" class="footnote-ref" id="fnref11" role="doc-noteref"><sup>11</sup></a>.</p>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>R functions
</div>
</div>
<div class="callout-body-container callout-body">
<pre><code>### power.t2n.test( n1 , n2 , d , sig.level , 
###                    power, alternative)
# n1: Set equal to the number of observations in first sample.
# n2: Set equal to the effect size.
# d: Set equal to the effect size.
# sig.level: Set equal to the desired alpha value (significance level)
# power: Set equal to the desired power (a number between 0 and 1). 
# alternative: The direction of the alternative. Set equal to "two.sided".
#
#
### power.t.test(power, d , sig.level , 
###                  alternative , type)
# power: Set equal to the desired power.
# type: Set equal to "two.sample" .
#</code></pre>
</div>
</div>
<p>The effect size refers to Cohen’s <span class="math inline">\(d\)</span>, which is defined as the difference between the true means divided by the pooled standard deviation. Cohen’s <span class="math inline">\(d\)</span> is typically interpreted as follows:</p>
<ul>
<li><p>Small effect size: <span class="math inline">\(d = 0.20\)</span></p></li>
<li><p>Medium effect size: <span class="math inline">\(d = 0.50\)</span></p></li>
<li><p>Large effect size: <span class="math inline">\(d = 0.80\)</span> or higher.</p></li>
</ul>
<p>These are suggested guidelines and may vary slightly depending on the specific field of research or context of the study.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Refer to the data described in the case study provided in <a href="datacs3.html" class="quarto-xref"><span>Chapter 3</span></a>. Let’s suppose the goal is to determine the statistical power of a two sample t-test if one wanted to detect a medium-sized effect when the sample size from each county is 100 at <span class="math inline">\(\alpha=.01\)</span>.</p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold"><summary>Code</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb14"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/heliosdrm/pwr">pwr</a></span><span class="op">)</span> <span class="co"># provides pwr.t2n.test</span></span>
<span></span>
<span><span class="co"># Note:  The output of this function call will be the statistical power for the t-test.</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/pwr/man/pwr.t2n.test.html">pwr.t2n.test</a></span><span class="op">(</span>n1 <span class="op">=</span> <span class="fl">100</span> ,          <span class="co"># Set the sample size for group 1</span></span>
<span>             n2 <span class="op">=</span> <span class="fl">100</span> ,          <span class="co"># Set the sample size for group 2</span></span>
<span>             d <span class="op">=</span> <span class="fl">0.50</span> ,          <span class="co"># Set Cohen's d</span></span>
<span>             sig.level <span class="op">=</span> <span class="fl">0.01</span> ,  <span class="co"># Set the significance level for the test</span></span>
<span>             alternative <span class="op">=</span> <span class="st">"two.sided"</span><span class="op">)</span> <span class="co"># Specify a two-sided alternative hypothesis</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;      t test power calculation </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;              n1 = 100</span></span>
<span><span class="co">#&gt;              n2 = 100</span></span>
<span><span class="co">#&gt;               d = 0.5</span></span>
<span><span class="co">#&gt;       sig.level = 0.01</span></span>
<span><span class="co">#&gt;           power = 0.8238225</span></span>
<span><span class="co">#&gt;     alternative = two.sided</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>The statistical power of this test is <span class="math inline">\(.824\)</span>. To further increase the power, one may increase the effect size (the larger it is, the easier it is to detect), increase the value of <span class="math inline">\(\alpha\)</span> (make it easier to reject <span class="math inline">\(H_0\)</span> and find a significant effect), and/or increase the sample sizes. The sample data consisted of at least 1000 observations from each county, so set each sample to <span class="math inline">\(1000\)</span>:</p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold"><summary>Code</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb15"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/pkg/pwr/man/pwr.t2n.test.html">pwr.t2n.test</a></span><span class="op">(</span>n1 <span class="op">=</span> <span class="fl">1000</span> ,</span>
<span>             n2 <span class="op">=</span> <span class="fl">1000</span> , </span>
<span>             d <span class="op">=</span> <span class="fl">.50</span> , </span>
<span>             sig.level <span class="op">=</span> <span class="fl">0.01</span> ,</span>
<span>             alternative <span class="op">=</span> <span class="st">"two.sided"</span> <span class="op">)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;      t test power calculation </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;              n1 = 1000</span></span>
<span><span class="co">#&gt;              n2 = 1000</span></span>
<span><span class="co">#&gt;               d = 0.5</span></span>
<span><span class="co">#&gt;       sig.level = 0.01</span></span>
<span><span class="co">#&gt;           power = 1</span></span>
<span><span class="co">#&gt;     alternative = two.sided</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>If instead you seek the required sample size for a given power, the argument <code>power</code> could be set to the desired power in the function <code><a href="https://rdrr.io/pkg/pwr/man/pwr.t.test.html">pwr.t.test()</a></code>:</p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold"><summary>Code</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb16"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Note:  The output of this function call will be the required sample size for the t-test.</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/pwr/man/pwr.t.test.html">pwr.t.test</a></span><span class="op">(</span>power <span class="op">=</span> <span class="fl">0.90</span> ,         <span class="co"># Set the desired power level</span></span>
<span>           d <span class="op">=</span> <span class="fl">0.50</span> ,             <span class="co"># Set the standardized mean difference between groups</span></span>
<span>           sig.level <span class="op">=</span> <span class="fl">0.01</span> ,     <span class="co"># Set the significance level for the test</span></span>
<span>           type <span class="op">=</span> <span class="st">"two.sample"</span> ,  <span class="co"># Set a two-sample t-test</span></span>
<span>           alternative <span class="op">=</span> <span class="st">"two.sided"</span><span class="op">)</span> <span class="co"># Specify a two-sided alternative hypothesis</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;      Two-sample t test power calculation </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;               n = 120.7055</span></span>
<span><span class="co">#&gt;               d = 0.5</span></span>
<span><span class="co">#&gt;       sig.level = 0.01</span></span>
<span><span class="co">#&gt;           power = 0.9</span></span>
<span><span class="co">#&gt;     alternative = two.sided</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; NOTE: n is number in *each* group</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</div>
</div>
<p>Relative power depends on the distributions, the effect, and the chosen tests. Rank tests can outperform t-tests for some non-normal distributions. Select methods using the scientific question, study design, target parameter, and relevant assumptions.</p>


</section><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><hr>
<ol>
<li id="fn1"><p>For the Welch t-test, the degree of freedom can be tedious to compute. Software will provide the corresponding degrees of freedom and p-value.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>For a two-sample t-test, <code>two.mean.test()</code> is a wrapper function of the R function <code>t.test</code>, but <code>two.mean.test</code> allows the user to choose the order of the difference.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>Randomization inference also requires an actual assignment mechanism or a defensible exchangeability argument; arbitrary shuffling of daily county observations is not automatically valid.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>Known distributions are parametric distributions in that they can be expressed using math formulas. Parametric methods assume that the underlying population data follow a known distribution<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p>Non-parametric methods assume fewer things about the data compare to parametric methods.<a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn6"><p>With unequal distribution shapes, equal medians alone do not supply the usual rank-test null distribution. Do not automatically reinterpret this as a test of a zero pseudomedian.<a href="#fnref6" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn7"><p>The exact rank distribution is discrete; software can use an exact calculation or a normal approximation with tie adjustments, depending on sample size, ties, and its implementation.<a href="#fnref7" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn8"><p>The R function <code>two.wilcox.test</code> is a wrapper function for the R function <code><a href="https://rdrr.io/r/stats/wilcox.test.html">wilcox.test()</a></code>.<a href="#fnref8" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn9"><p>When an asymptotic calculation is used, the p-value uses a normal approximation, generally with tie and continuity corrections. Assess approximation quality for the particular data rather than relying on a universal sample-size cutoff.<a href="#fnref9" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn10"><p>The two-sample Hodges–Lehmann estimate is the median of all between-group pairwise differences. It estimates the location shift under a shift model.<a href="#fnref10" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn11"><p>The R function <code>power.welch.t.test()</code> and <code>sim.ssize.wilcox.test()</code> from the <code>MKpower</code> R package provides statistical power calculations for the two-sample Welch t-test and two-sample Wilcox rank sum test, respectively. However, these functions may be difficult to use for those not familiar with power analysis.<a href="#fnref11" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol></section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/emontoya2\.github\.io\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./siframework.html" class="pagination-link" aria-label="Statistical inference framework via a case study">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Statistical inference framework via a case study</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./anovalin.html" class="pagination-link" aria-label="Module: ANOVA, linear regression, and logistic regression">
        <span class="nav-page-text">Module: ANOVA, linear regression, and logistic regression</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/emontoya2/edit/master/twoindptmeans.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li></ul></div></div></div></footer></body></html>